### ISSUE TITLE
Jicofo failing to startup

### ISSUE THREAD

**Issue by debendraoli** [jitsi/docker-jitsi-meet#1007]
I recently upgraded to the latest version, and encountered jicofo starting issue.

It was change where JICOFO_COMPONENT_SECRET is removed, but the value still present on docker-compose for prosody service.

```
Jicofo 2021-04-07 18:24:39.798 SEVERE: [1] org.jitsi.jicofo.Main.log() An uncaught exception occurred in thread=Thread[main,5,main]
jicofo_1   | org.jitsi.cmd.ParseException: Some of required arguments were not specified: [secret]
jicofo_1   | 	at org.jitsi.cmd.CmdLine.parse(CmdLine.java:130)
jicofo_1   | 	at org.jitsi.jicofo.Main.setSystemProperties(Main.java:182)
jicofo_1   | 	at org.jitsi.jicofo.Main.main(Main.java:56)
```

Also there are couple of errors on prosody service when starting due to missing modules.

I guess due to missing package.

prosody_1  | modulemanager       error	Unable to load module 'roster_command': 

`/usr/lib/prosody/modules/mod_roster_command.lua: No such file or directory`

`prosody_1  | modulemanager                                                  error	Unable to load module 'client_proxy': /usr/lib/prosody/modules/mod_client_proxy.lua: No such file or directory`

**Comment by saghul** [comment]
Search for similar issues before opening a new one please.

**Comment by YarekTyshchenko** [comment]
@saghul Which similar issue are you refering to?

**Comment by debendraoli** [comment]
@YarekTyshchenko https://github.com/jitsi/docker-jitsi-meet/issues/1006

**Comment by YarekTyshchenko** [comment]
@debendraoli They don't seem related. I'm getting the `mod_roster_command.lua: No such file or directory` when doing an install from apt.

**Comment by YarekTyshchenko** [comment]
Oh dear. I'm sorry, totally missed the repo name!

**Comment by ghenry** [comment]
sudo apt-get --purge remove jitsi-meet-prosody
