### ISSUE TITLE
Room randomly crashes after joining

### ISSUE THREAD

**Issue by Inglebard** [jitsi/docker-jitsi-meet#1037]
Hi,

We notice today and month ago jitsi a crash after someone join the room.
It seems to be random and I am not able to reproduce the issue. Restart the stack seems to "fix" temporary the issue.
I was not able to capture the log until today.

We only use rooms with auth.

We use the "stable-5390-3" version but the issue appear multiple times since 1 year (I think).
I notice the following in the log : 
`
jicofo_1   | Jicofo 2021-04-22 09:59:11.063 SEVERE: [291] org.jitsi.jicofo.AbstractChannelAllocator.log() jvbbrewery@internal-muc.meet.jitsi/046ae4fc108c - failed to allocate channels, will consider the bridge faulty: Timed out waiting for a response.
jicofo_1   | org.jitsi.protocol.xmpp.colibri.exception.TimeoutException: Timed out waiting for a response.
jicofo_1   | 	at org.jitsi.impl.protocol.xmpp.colibri.ColibriConferenceImpl.maybeThrowOperationFailed(ColibriConferenceImpl.java:328)
jicofo_1   | 	at org.jitsi.impl.protocol.xmpp.colibri.ColibriConferenceImpl.createColibriChannels(ColibriConferenceImpl.java:268)
jicofo_1   | 	at org.jitsi.protocol.xmpp.colibri.ColibriConference.createColibriChannels(ColibriConference.java:102)
jicofo_1   | 	at org.jitsi.jicofo.ParticipantChannelAllocator.doAllocateChannels(ParticipantChannelAllocator.java:110)
jicofo_1   | 	at org.jitsi.jicofo.AbstractChannelAllocator.allocateChannels(AbstractChannelAllocator.java:271)
jicofo_1   | 	at org.jitsi.jicofo.AbstractChannelAllocator.doRun(AbstractChannelAllocator.java:190)
jicofo_1   | 	at org.jitsi.jicofo.AbstractChannelAllocator.run(AbstractChannelAllocator.java:150)
jicofo_1   | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
jicofo_1   | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
jicofo_1   | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
jicofo_1   | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
jicofo_1   | 	at java.lang.Thread.run(Thread.java:748)
`

When the room begin to crash, it crashes every time. I have not tested what happens if we create another room.

**Comment by saghul** [comment]
That looks like a communication problem between the JVB and Prosody.

**Comment by Inglebard** [comment]
@saghul 

> That looks like a communication problem between the JVB and Prosody.

An idea to know why and how to fix this ?

**Comment by saghul** [comment]
Check the JVB logs.

**Comment by Inglebard** [comment]
@saghul 
Hmmm... seems some logs are missing.
I will wait to happen again and post relevant log.

**Comment by Inglebard** [comment]
Hi,

Here is a new part of a log : 
https://pastebin.com/Wqgc0iG3

**Comment by Inglebard** [comment]
@saghul  
I have encounter the issue today do you know what is wrong ?

**Comment by Inglebard** [comment]
Still happening.
