### ISSUE TITLE
jibri still not work at latest build

### ISSUE THREAD

**Issue by yelban** [jitsi/docker-jitsi-meet#1054]
log.0.txt

> 2021-05-20 19:50:23.432 FINE: [1] org.jitsi.jibri.config.log() ConfigSourceSupplier: Trying to retrieve key 'internal_http_port' from source 'command line args' as type kotlin.Int
2021-05-20 19:50:23.433 FINE: [1] org.jitsi.jibri.config.log() FallbackSupplier: failed to find value via ConfigSourceSupplier: key: 'internal_http_port', type: 'kotlin.Int', source: 'command line args': org.jitsi.metaconfig.ConfigException$UnableToRetrieve$NotFound: not found
...
2021-05-20 19:50:23.945 FINE: [1] org.jitsi.jibri.config.log() ConfigSourceSupplier: Trying to retrieve key 'http_api_port' from source 'command line args' as type kotlin.Int
2021-05-20 19:50:23.945 FINE: [1] org.jitsi.jibri.config.log() FallbackSupplier: failed to find value via ConfigSourceSupplier: key: 'http_api_port', type: 'kotlin.Int', source: 'command line args': org.jitsi.metaconfig.ConfigException$UnableToRetrieve$NotFound: not found
...
2021-05-20 19:50:23.988 FINE: [26] org.jitsi.xmpp.mucclient.MucClient.log() About to connect and login.
2021-05-20 19:50:24.301 INFO: [26] org.jitsi.xmpp.mucclient.MucClient.log() Connected.
2021-05-20 19:50:24.301 INFO: [26] org.jitsi.xmpp.mucclient.MucClient.log() Logging in.
2021-05-20 19:50:24.360 FINE: [26] org.jitsi.xmpp.mucclient.MucClient.log() Authenticated, b=false
2021-05-20 19:50:24.361 FINE: [26] org.jitsi.xmpp.mucclient.MucClient.log() About to join MUCs: [jibribrewery@internal-muc.meet.jitsi]
2021-05-20 19:50:24.390 INFO: [26] org.jitsi.xmpp.mucclient.MucClient.log() Joined MUC: jibribrewery@internal-muc.meet.jitsi
2021-05-20 19:50:24.396 FINE: [33] org.jitsi.xmpp.extensions.DefaultPacketExtensionProvider.parse() Could not add a provider for element busy-status from namespace http://jitsi.org/protocol/jibri
2021-05-20 19:50:24.396 FINE: [33] org.jitsi.xmpp.extensions.DefaultPacketExtensionProvider.parse() Could not add a provider for element health-status from namespace http://jitsi.org/protocol/health
...
2021-05-20 19:52:26.042 SEVERE: [56] org.jitsi.jibri.selenium.JibriSelenium.log() An error occurred while joining the call
org.openqa.selenium.TimeoutException: timeout: Timed out receiving message from renderer: -0.000
  (Session info: chrome=90.0.4430.212)
  (Driver info: chromedriver=90.0.4430.24 (4c6d850f087da467d926e8eddb76550aed655991-refs/branch-heads/4430@{#429}),platform=Linux 5.4.0-73-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'aad340967e86', ip: '192.168.112.6', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-73-generic', java.version: '1.8.0_292'
...
2021-05-20 19:52:26.240 INFO: [56] org.jitsi.jibri.service.impl.FileRecordingJibriService.log() Finalizing the recording
2021-05-20 19:52:26.242 SEVERE: [56] org.jitsi.jibri.service.impl.FileRecordingJibriService.log() Failed to run finalize script
java.io.IOException: Cannot run program "/path/to/finalize": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at org.jitsi.jibri.util.ProcessWrapper.start(ProcessWrapper.kt:88)
...
2021-05-20 19:52:26.246 INFO: [56] org.jitsi.jibri.api.xmpp.XmppApi.log() Jibri reports its status is now JibriStatus(busyStatus=IDLE, health=OverallHealth(healthStatus=HEALTHY, details={})), publishing presence to connections
2021-05-20 19:52:26.246 FINE: [56] org.jitsi.xmpp.mucclient.MucClientManager.log() Setting a presence extension: org.jitsi.xmpp.extensions.jibri.JibriStatusPacketExt@5faa270b
2021-05-20 19:52:26.247 FINE: [56] org.jitsi.xmpp.mucclient.MucClientManager.log() Replacing presence extension: org.jitsi.xmpp.extensions.jibri.JibriStatusPacketExt@b8cde11
2021-05-20 19:52:26.251 FINE: [33] org.jitsi.xmpp.extensions.DefaultPacketExtensionProvider.parse() Could not add a provider for element busy-status from namespace http://jitsi.org/protocol/jibri
2021-05-20 19:52:26.251 FINE: [33] org.jitsi.xmpp.extensions.DefaultPacketExtensionProvider.parse() Could not add a provider for element health-status from namespace http://jitsi.org/protocol/health
2021-05-20 19:53:23.423 FINE: [17] org.jitsi.jibri.webhooks.v1.WebhookClient.log() Updating 0 subscribers of status
2021-05-20 19:54:23.422 FINE: [17] org.jitsi.jibri.webhooks.v1.WebhookClient.log() Updating 0 subscribers of status

**Comment by saghul** [comment]
Is your PUBLIC_URL env variable properly configured?

**Comment by saghul** [comment]
Yeah config is in /etc/jitsi/jibri on this one. We should change that maybe.

**Comment by yelban** [comment]
The problem is with SSL, if the PUBLIC_URL uses https://, you need to turn on ENABLE_LETSENCRYPT at the same time, otherwise chrome 90 will complain that the certificate is invalid.

Thank you saghul.
