### ISSUE TITLE
Jibri timeout after 30 sec 

### ISSUE THREAD

**Issue by riderx** [jitsi/docker-jitsi-meet#1146]
I used your deploy file to create a docker compose but jibri struggle to connect to the jitsi instance, i cannot et why even after check all issue there .
You can find my full config there :
https://github.com/riderx/lemverse-deploy
Here are my logs :
```
2021-10-18 18:08:55.489 FINE: [134] org.jitsi.jibri.statsd.JibriStatsDClient.log() Incrementing statsd counter: start:recording
2021-10-18 18:08:55.490 INFO: [134] org.jitsi.jibri.status.JibriStatusManager.log() Busy status has changed: IDLE -> BUSY
2021-10-18 18:08:55.491 FINE: [134] org.jitsi.jibri.webhooks.v1.WebhookClient.log() Updating 0 subscribers of status
2021-10-18 18:08:55.491 INFO: [134] org.jitsi.jibri.api.xmpp.XmppApi.log() Jibri reports its status is now JibriStatus(busyStatus=BUSY, health=OverallHealth(healthStatus=HEALTHY, details={})), publishing presence to connections
2021-10-18 18:08:55.493 FINE: [134] org.jitsi.xmpp.mucclient.MucClientManager.log() Setting a presence extension: org.jitsi.xmpp.extensions.jibri.JibriStatusPacketExt@5abc9af0
2021-10-18 18:08:55.493 FINE: [134] org.jitsi.xmpp.mucclient.MucClientManager.log() Replacing presence extension: org.jitsi.xmpp.extensions.jibri.JibriStatusPacketExt@51035818
2021-10-18 18:08:55.496 INFO: [134] org.jitsi.jibri.api.xmpp.XmppApi.log() Sending 'pending' response to start IQ
2021-10-18 18:08:55.499 FINE: [37] org.jitsi.xmpp.extensions.DefaultPacketExtensionProvider.parse() Could not add a provider for element busy-status from namespace http://jitsi.org/protocol/jibri
2021-10-18 18:08:55.499 FINE: [37] org.jitsi.xmpp.extensions.DefaultPacketExtensionProvider.parse() Could not add a provider for element health-status from namespace http://jitsi.org/protocol/health
2021-10-18 18:08:55.501 INFO: [146] org.jitsi.jibri.selenium.pageobjects.HomePage.log() Visiting url https://video.indiemakers.space
2021-10-18 18:09:01.318 FINE: [134] org.jitsi.xmpp.mucclient.MucClient.log() Received an IQ with type set: IQ Stanza (jibri http://jitsi.org/protocol/jibri) [to=jibri@auth.meet.jitsi/dUupE-pk,from=jibribrewery@internal-muc.meet.jitsi/focus,id=amlicmlAYXV0aC5tZWV0LmppdHNpL2RVdXBFLXBrAGhBc0hHLTk1MQB9MKAL27uLVhq/q96wolfF,type=set,]
2021-10-18 18:09:01.320 INFO: [134] org.jitsi.jibri.api.xmpp.XmppApi.log() Received JibriIq <iq to='jibri@auth.meet.jitsi/dUupE-pk' from='jibribrewery@internal-muc.meet.jitsi/focus' id='amlicmlAYXV0aC5tZWV0LmppdHNpL2RVdXBFLXBrAGhBc0hHLTk1MQB9MKAL27uLVhq/q96wolfF' type='set'><jibri xmlns='http://jitsi.org/protocol/jibri' action='stop' session_id='sbukdnoccscwtnhf'/></iq> from environment [MucClient id=xmpp.meet.jitsi hostname=xmpp.meet.jitsi]
2021-10-18 18:09:01.320 FINE: [134] org.jitsi.jibri.statsd.JibriStatsDClient.log() Incrementing statsd counter: stop:recording
2021-10-18 18:09:01.321 INFO: [134] org.jitsi.jibri.JibriManager.log() Stopping the current service
2021-10-18 18:09:01.321 INFO: [134] org.jitsi.jibri.service.impl.FileRecordingJibriService.log() Stopping capturer
2021-10-18 18:09:01.322 INFO: [134] org.jitsi.jibri.util.JibriSubprocess.log() Stopping ffmpeg process
2021-10-18 18:09:01.322 INFO: [134] org.jitsi.jibri.util.JibriSubprocess.log() ffmpeg exited with value null
2021-10-18 18:09:01.323 INFO: [134] org.jitsi.jibri.service.impl.FileRecordingJibriService.log() Quitting selenium
2021-10-18 18:09:16.188 FINE: [16] org.jitsi.jibri.webhooks.v1.WebhookClient.log() Updating 0 subscribers of status
2021-10-18 18:09:55.528 SEVERE: [146] org.jitsi.jibri.selenium.JibriSelenium.log() An error occurred while joining the call
org.openqa.selenium.TimeoutException: timeout: Timed out receiving message from renderer: -0.000
  (Session info: chrome=90.0.4430.212)
  (Driver info: chromedriver=90.0.4430.24 (4c6d850f087da467d926e8eddb76550aed655991-refs/branch-heads/4430@{#429}),platform=Linux 5.4.0-84-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'c6f020b3e0ab', ip: '172.21.0.6', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-84-generic', java.version: '1.8.0_292'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 90.0.4430.24 (4c6d850f087da..., userDataDir: /tmp/.com.google.Chrome.TxFX5n}, cssSelectorsEnabled: true, databaseEnabled: false, goog:chromeOptions: {debuggerAddress: localhost:42257}, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), rotatable: false, setWindowRect: true, strictFileInteractability: false, takesHeapSnapshot: true, takesScreenshot: true, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unexpectedAlertBehaviour: ignore, unhandledPromptBehavior: ignore, version: 90.0.4430.212, webStorageEnabled: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 60e4d4eea866f87d26fea8bddd904da5
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
        at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
        at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
        at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
        at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
        at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:271)
        at org.jitsi.jibri.selenium.pageobjects.AbstractPageObject.visit(AbstractPageObject.kt:35)
        at org.jitsi.jibri.selenium.JibriSelenium$joinCall$1.run(JibriSelenium.kt:278)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2021-10-18 18:09:55.535 INFO: [146] org.jitsi.jibri.selenium.JibriSelenium.log() Transitioning from state Starting up to Error: FailedToJoinCall SESSION Failed to join the call
2021-10-18 18:09:55.536 INFO: [146] org.jitsi.jibri.service.impl.FileRecordingJibriService.log() File recording service transitioning from state Starting up to Error: FailedToJoinCall SESSION Failed to join the call
2021-10-18 18:09:55.537 INFO: [146] org.jitsi.jibri.api.xmpp.XmppApi.log() Current service had an error Error: FailedToJoinCall SESSION Failed to join the call, sending error iq <iq to='jibribrewery@internal-muc.meet.jitsi/focus' id='mj0M0-169' type='set'><jibri xmlns='http://jitsi.org/protocol/jibri' status='off' failure_reason='error' should_retry='true'/></iq>
2021-10-18 18:09:55.559 INFO: [134] org.jitsi.jibri.service.impl.FileRecordingJibriService.log() Participants in this recording: []
2021-10-18 18:09:55.567 INFO: [134] org.jitsi.jibri.selenium.JibriSelenium.log() Leaving call and quitting browser
2021-10-18 18:09:55.568 INFO: [134] org.jitsi.jibri.selenium.JibriSelenium.log() Recurring call status checks cancelled
2021-10-18 18:09:55.588 INFO: [134] org.jitsi.jibri.selenium.JibriSelenium.log() Got 0 log entries for type browser
2021-10-18 18:09:55.600 INFO: [134] org.jitsi.jibri.selenium.JibriSelenium.log() Got 87 log entries for type driver
2021-10-18 18:09:55.613 INFO: [134] org.jitsi.jibri.selenium.JibriSelenium.log() Got 0 log entries for type client
2021-10-18 18:09:55.646 INFO: [134] org.jitsi.jibri.selenium.JibriSelenium.log() Leaving web call
2021-10-18 18:09:55.675 INFO: [134] org.jitsi.jibri.selenium.JibriSelenium.log() Quitting chrome driver
2021-10-18 18:09:55.748 INFO: [134] org.jitsi.jibri.selenium.JibriSelenium.log() Chrome driver quit
```

**Comment by riderx** [comment]
@prayagsingh install jitsi on raw ubuntu on digitalocean and install docker myself fix the issue .
I will move my server to this one i think.
There is what you asked :
```
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
206.189.29.12   video.indiemakers.space
172.18.0.6      f9804b6673dd
```
