### ISSUE TITLE
Unable to record with latest Docker image (stable-6726)

### ISSUE THREAD

**Issue by moufmouf** [jitsi/docker-jitsi-meet#1167]
## Description

The latest version of the Jibri docker image (stable-6726) does not work. It seems to be related to the version of Chrome it ships with.
The previous version (jibri:stable-6433) was working correctly.

## Current behavior

I just upgraded from jibri:stable-6433 to jibri:stable-6726.
Recording does not work any more.

In the logs, I can see this message:

```
2021-12-13 12:47:54.932 FINE: [66] org.jitsi.jibri.config.log() ConfigSourceSupplier: Trying to retrieve key 'jibri.call-status-checks.default-call-empty-timeout' from source 'config' as type java.time.Duration
2021-12-13 12:47:54.934 FINE: [66] org.jitsi.jibri.config.log() ConfigSourceSupplier: Successfully retrieved key 'jibri.call-status-checks.default-call-empty-timeout' from source 'config' as type java.time.Duration
2021-12-13 12:47:54.940 FINE: [66] org.jitsi.jibri.config.log() ConfigSourceSupplier: Trying to retrieve key 'jibri.chrome.flags' from source 'config' as type kotlin.collections.List<kotlin.String>
2021-12-13 12:47:54.941 FINE: [66] org.jitsi.jibri.config.log() ConfigSourceSupplier: Successfully retrieved key 'jibri.chrome.flags' from source 'config' as type kotlin.collections.List<kotlin.String>
2021-12-13 12:47:56.414 SEVERE: [66] org.jitsi.jibri.api.xmpp.XmppApi.log() Error starting Jibri service 
org.openqa.selenium.SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 96
Current browser version is 94.0.4606.61 with binary path /usr/bin/google-chrome
  (Driver info: chromedriver=96.0.4664.45 (76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}),platform=Linux 4.15.0-163-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.18 seconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'ded96705c909', ip: '172.18.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-163-generic', java.version: '11.0.13'
Driver info: driver.version: ChromeDriver
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$new$0(JsonWireProtocolResponse.java:53)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$getResponseFunction$2(JsonWireProtocolResponse.java:91)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:207)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
	at org.jitsi.jibri.selenium.JibriSelenium.<init>(JibriSelenium.kt:196)
	at org.jitsi.jibri.selenium.JibriSelenium.<init>(JibriSelenium.kt:166)
	at org.jitsi.jibri.service.impl.FileRecordingJibriService.<init>(FileRecordingJibriService.kt:109)
	at org.jitsi.jibri.service.impl.FileRecordingJibriService.<init>(FileRecordingJibriService.kt:102)
	at org.jitsi.jibri.JibriManager.startFileRecording(JibriManager.kt:139)
	at org.jitsi.jibri.api.xmpp.XmppApi.handleStartService(XmppApi.kt:308)
	at org.jitsi.jibri.api.xmpp.XmppApi.handleStartJibriIq(XmppApi.kt:206)
	at org.jitsi.jibri.api.xmpp.XmppApi.handleJibriIq(XmppApi.kt:178)
	at org.jitsi.jibri.api.xmpp.XmppApi.handleIq(XmppApi.kt:160)
	at org.jitsi.xmpp.mucclient.MucClient.handleIq(MucClient.java:533)
	at org.jitsi.xmpp.mucclient.MucClient.access$300(MucClient.java:51)
	at org.jitsi.xmpp.mucclient.MucClient$3.handleIQRequest(MucClient.java:496)
	at org.jivesoftware.smack.AbstractXMPPConnection$3.run(AbstractXMPPConnection.java:1568)
	at org.jivesoftware.smack.AbstractXMPPConnection$10.run(AbstractXMPPConnection.java:2146)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

## Expected Behavior

Recording works ;)

## Possible Solution

I suspect this is linked to the version of Chrome shipped in the image.

## Steps to reproduce

I did nothing special. I simply upgraded Jibri to the latest version (using the Docker image)

I suspect (though I'm not sure), that the latest version was probably rushed to fix the Log4J CVE, and maybe the Docker image was left untested?

Any way, thanks a lot for your work and for this great software!

**Comment by GaLaXy102** [comment]
I had the same issue today. A quick fix would be to just overwrite the currently installed chromedriver by running
```
curl -4Ls "https://chromedriver.storage.googleapis.com/94.0.4606.113/chromedriver_linux64.zip" | zcat > /usr/bin/chromedriver
chmod +x /usr/bin/chromedriver
```

Apparently there must have been an uncommitted commenting error in the corresponding Dockerfile, a Build-Args hiccup or (unprobable, but not impossible) a bad response from `curl -4Ls https://chromedriver.storage.googleapis.com/LATEST_RELEASE_94`

Either way, thanks folks for the work with Jitsi! :)

**Comment by saghul** [comment]
Not sure how that could've failed, nothing has changed on our end. Oh well. I took the chance to update to M96 while at it and checked the images were built correctly:

```
...
#5 54.29 Get:11 /tmp/google-chrome-stable_96.0.4664.45-1_amd64.deb google-chrome-stable amd64 96.0.4664.45-1 [90.8 MB]
...
#5 73.73 ChromeDriver 96.0.4664.45 (76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947})
...
```

This is now released: https://github.com/jitsi/docker-jitsi-meet/releases/tag/stable-6726-1
