### ISSUE TITLE
cannot start recording in 6726-1 (XMPPError: not-allowed - cancel [Room creation is restricted])

### ISSUE THREAD

**Issue by mhow2** [jitsi/docker-jitsi-meet#1174]
I unzip'ed `6726-1` and copied over the `.env` file from previous release `6433` and restarted the stack with the usual `docker-compose -f docker-compose.yml -f jibri.yml up` I got the frontend working, but when I start the recording I got a "failed" message in the frontend and the following log in the jibri container.

```
2021-12-15 11:32:53.852 INFO: [1] org.jitsi.jibri.api.xmpp.XmppApi.log() Connecting to xmpp environment on xmpp.meet.jitsi with config XmppEnvironmentConfig(name=<no value>, xmppServerHosts=[xmpp.meet.jitsi], xmppDomain=meet.jitsi, baseUrl=https://jitsi2.hivane.net, controlLogin=XmppCredentials(domain=auth.meet.jitsi, port=null, username=jibri, password=*****), controlMuc=XmppMuc(domain=internal-muc.meet.jitsi, roomName=jibribrewery, nickname=jibri-324951754), sipControlMuc=null, callLogin=XmppCredentials(domain=recorder.meet.jitsi, port=null, username=recorder, password=*****), stripFromRoomDomain=muc., usageTimeoutMins=0, trustAllXmppCerts=true, securityMode=null)
2021-12-15 11:32:53.854 INFO: [1] org.jitsi.jibri.api.xmpp.XmppApi.log() The trustAllXmppCerts config is enabled for this domain, all XMPP server provided certificates will be accepted
2021-12-15 11:32:53.891 INFO: [31] org.jitsi.xmpp.mucclient.MucClient.log() Initializing a new MucClient for [ org.jitsi.xmpp.mucclient.MucClientConfiguration id=xmpp.meet.jitsi domain=auth.meet.jitsi hostname=xmpp.meet.jitsi port=null username=jibri mucs=[jibribrewery@internal-muc.meet.jitsi] mucNickname=jibri-324951754 disableCertificateVerification=true]
2021-12-15 11:32:53.895 FINE: [1] org.jitsi.jibri.config.log() FallbackSupplier: checking for value via suppliers:
  ConfigSourceSupplier: key: 'http_api_port', type: 'kotlin.Int', source: 'command line args'
  ConfigSourceSupplier: key: 'jibri.api.http.external-api-port', type: 'kotlin.Int', source: 'config'
2021-12-15 11:32:53.896 FINE: [1] org.jitsi.jibri.config.log() ConfigSourceSupplier: Trying to retrieve key 'http_api_port' from source 'command line args' as type kotlin.Int
2021-12-15 11:32:53.896 FINE: [1] org.jitsi.jibri.config.log() FallbackSupplier: failed to find value via ConfigSourceSupplier: key: 'http_api_port', type: 'kotlin.Int', source: 'command line args': org.jitsi.metaconfig.ConfigException$UnableToRetrieve$NotFound: not found
2021-12-15 11:32:53.897 FINE: [1] org.jitsi.jibri.config.log() ConfigSourceSupplier: Trying to retrieve key 'jibri.api.http.external-api-port' from source 'config' as type kotlin.Int
2021-12-15 11:32:53.897 FINE: [1] org.jitsi.jibri.config.log() ConfigSourceSupplier: Successfully retrieved key 'jibri.api.http.external-api-port' from source 'config' as type kotlin.Int
2021-12-15 11:32:53.898 FINE: [1] org.jitsi.jibri.config.log() FallbackSupplier: value found via ConfigSourceSupplier: key: 'jibri.api.http.external-api-port', type: 'kotlin.Int', source: 'config'
2021-12-15 11:32:53.898 INFO: [1] org.jitsi.jibri.Main.log() Using port 2222 for HTTP API
2021-12-15 11:32:53.940 WARNING: [31] org.jitsi.xmpp.mucclient.MucClient.log() Disabling certificate verification!
2021-12-15 11:32:54.005 INFO: [31] org.jitsi.xmpp.mucclient.MucClient.log() Dispatching a thread to connect and login.
2021-12-15 11:32:54.296 INFO: [31] org.jitsi.xmpp.mucclient.MucClient.log() Connected.
2021-12-15 11:32:54.296 INFO: [31] org.jitsi.xmpp.mucclient.MucClient.log() Logging in.
2021-12-15 11:32:54.366 INFO: [31] org.jitsi.xmpp.mucclient.MucClient.log() Authenticated, b=false
2021-12-15 11:32:54.371 FINE: [31] org.jitsi.xmpp.mucclient.MucClient.log() Resetting lastPresenceSent
2021-12-15 11:32:54.438 WARNING: [31] org.jitsi.xmpp.mucclient.MucClient.log() Failed to join the MUCs.
org.jivesoftware.smack.XMPPException$XMPPErrorException: XMPP error reply received from jibribrewery@internal-muc.meet.jitsi/jibri-324951754: XMPPError: not-allowed - cancel [Room creation is restricted]
	at org.jivesoftware.smack.XMPPException$XMPPErrorException.ifHasErrorThenThrow(XMPPException.java:171)
	at org.jivesoftware.smack.XMPPException$XMPPErrorException.ifHasErrorThenThrow(XMPPException.java:165)
	at org.jivesoftware.smack.StanzaCollector.nextResultOrThrow(StanzaCollector.java:284)
	at org.jivesoftware.smackx.muc.MultiUserChat.enter(MultiUserChat.java:405)
	at org.jivesoftware.smackx.muc.MultiUserChat.createOrJoin(MultiUserChat.java:543)
	at org.jivesoftware.smackx.muc.MultiUserChat.createOrJoin(MultiUserChat.java:518)
	at org.jitsi.xmpp.mucclient.MucClient$MucWrapper.join(MucClient.java:735)
	at org.jitsi.xmpp.mucclient.MucClient$MucWrapper.access$200(MucClient.java:666)
	at org.jitsi.xmpp.mucclient.MucClient.joinMucs(MucClient.java:351)
	at org.jitsi.xmpp.mucclient.MucClient.lambda$getConnectAndLoginCallable$8(MucClient.java:649)
	at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:167)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021-12-15 11:33:53.270 FINE: [20] org.jitsi.jibri.webhooks.v1.WebhookClient.log() Updating 0 subscribers of status
```

**Comment by mhow2** [comment]
Gosh. It was disabled in the config file. Sorry for the noise.

**Comment by artkaas** [comment]
I am getting the same error after the upgrade just today. What was actually wrong in your case? How did you fix it?

**Comment by mhow2** [comment]
> Gosh. It was disabled in the config file. Sorry for the noise.

My answer was probably missing some material : the option `ENABLE_RECORDING` in `.env` wasn't set to `1` (but the related option menu still visible in Jitsi web frontend for some reason)
