### ISSUE TITLE
Jicofo can't connect to XMPP

### ISSUE THREAD

**Issue by alsan1997** [jitsi/docker-jitsi-meet#1180]
Here's the log:

```
Jicofo 2021-12-24 06:58:26.655 SEVERE: [35] org.jitsi.health.HealthChecker.log() Health check failed in PT0S:
java.lang.RuntimeException: Jicofo XMPP component not connected
        at org.jitsi.jicofo.health.Health.check(Health.java:170)
        at org.jitsi.jicofo.health.Health.performCheck(Health.java:133)
        at org.jitsi.health.AbstractHealthCheckService$healthCheck$1.invoke(AbstractHealthCheckService.kt:63)
        at org.jitsi.health.AbstractHealthCheckService$healthCheck$1.invoke(AbstractHealthCheckService.kt:27)
        at org.jitsi.health.HealthChecker.run(HealthChecker.kt:142)
        at org.jitsi.utils.concurrent.RecurringRunnableExecutor.run(RecurringRunnableExecutor.java:216)
        at org.jitsi.utils.concurrent.RecurringRunnableExecutor.runInThread(RecurringRunnableExecutor.java:292)
        at org.jitsi.utils.concurrent.RecurringRunnableExecutor.access$000(RecurringRunnableExecutor.java:36)
        at org.jitsi.utils.concurrent.RecurringRunnableExecutor$1.run(RecurringRunnableExecutor.java:328)
Jicofo 2021-12-24 06:58:26.660 SEVERE: [36] org.jitsi.xmpp.component.ComponentBase.log() Failed to send ping
java.lang.NullPointerException
        at org.xmpp.component.AbstractComponent.send(AbstractComponent.java:925)
        at org.jitsi.xmpp.component.ComponentBase.access$400(ComponentBase.java:36)
        at org.jitsi.xmpp.component.ComponentBase$PingTask.run(ComponentBase.java:577)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
Jicofo 2021-12-24 06:58:26.702 SEVERE: [37] org.jitsi.meet.ComponentMain.log() conflict, host:10.191.2.22, port:5347
org.xmpp.component.ComponentException: conflict
        at org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:243)
        at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:242)
        at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:222)
        at org.jitsi.meet.ComponentMain.lambda$getConnectCallable$0(ComponentMain.java:285)
        at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Jicofo 2021-12-24 06:58:31.704 SEVERE: [37] org.jitsi.meet.ComponentMain.log() conflict, host:10.191.2.22, port:5347
org.xmpp.component.ComponentException: conflict
        at org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:243)
        at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:242)
        at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:222)
        at org.jitsi.meet.ComponentMain.lambda$getConnectCallable$0(ComponentMain.java:285)
        at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by saghul** [comment]
We no longer use component connections on Jicofo, please update your Docker release.
