### ISSUE TITLE
Unable to record with latest Docker image (stable-6726-2)

### ISSUE THREAD

**Issue by moufmouf** [jitsi/docker-jitsi-meet#1197]
## Description

The latest version of the Jibri docker image (stable-6726-2) does not work. It seems to be related to the version of Chrome it ships with.
The previous version (jibri:stable-6726-1) was working correctly.

This is not the first time the problem pops up. It already happened during the release of stable-6726. Please see #1167 

## Current behavior

I just upgraded from jibri:stable-6726-1 to jibri:stable-6726-2.
Recording does not work any more.

In the logs, I can see this message:

```
2022-01-15 22:49:36.436 SEVERE: [46] org.jitsi.jibri.api.xmpp.XmppApi.log() Error starting Jibri service 
org.openqa.selenium.SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 97
Current browser version is 96.0.4664.45 with binary path /usr/bin/google-chrome
  (Driver info: chromedriver=97.0.4692.71 (adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}),platform=Linux 4.15.0-166-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 261 milliseconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'b242431d378f', ip: '172.18.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-166-generic', java.version: '11.0.13'
Driver info: driver.version: ChromeDriver
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$new$0(JsonWireProtocolResponse.java:53)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$getResponseFunction$2(JsonWireProtocolResponse.java:91)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:207)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
	at org.jitsi.jibri.selenium.JibriSelenium.<init>(JibriSelenium.kt:196)
	at org.jitsi.jibri.selenium.JibriSelenium.<init>(JibriSelenium.kt:166)
	at org.jitsi.jibri.service.impl.FileRecordingJibriService.<init>(FileRecordingJibriService.kt:109)
	at org.jitsi.jibri.service.impl.FileRecordingJibriService.<init>(FileRecordingJibriService.kt:102)
	at org.jitsi.jibri.JibriManager.startFileRecording(JibriManager.kt:139)
	at org.jitsi.jibri.api.xmpp.XmppApi.handleStartService(XmppApi.kt:308)
	at org.jitsi.jibri.api.xmpp.XmppApi.handleStartJibriIq(XmppApi.kt:206)
	at org.jitsi.jibri.api.xmpp.XmppApi.handleJibriIq(XmppApi.kt:178)
	at org.jitsi.jibri.api.xmpp.XmppApi.handleIq(XmppApi.kt:160)
	at org.jitsi.xmpp.mucclient.MucClient.handleIq(MucClient.java:533)
	at org.jitsi.xmpp.mucclient.MucClient.access$300(MucClient.java:51)
	at org.jitsi.xmpp.mucclient.MucClient$3.handleIQRequest(MucClient.java:496)
	at org.jivesoftware.smack.AbstractXMPPConnection$3.run(AbstractXMPPConnection.java:1568)
	at org.jivesoftware.smack.AbstractXMPPConnection$10.run(AbstractXMPPConnection.java:2146)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

## Steps to reproduce

I did nothing special. I simply upgraded Jibri to the latest version (using the Docker image)

Any way, thanks again for your work and for this great software!

**Comment by saghul** [comment]
Ah bummer. https://github.com/jitsi/docker-jitsi-meet/pull/1168 should fix it, which I just merged. I'll make a -3 release.

**Comment by saghul** [comment]
Fixed in stable-6826

**Comment by moufmouf** [comment]
Thanks!
