### ISSUE TITLE
Transcription enabled, but throws null pointer with google cloud configured

### ISSUE THREAD

**Issue by mrWodoo** [jitsi/docker-jitsi-meet#1232]
branch: master
docker-jitsi-meet-jicofo-1   | Jicofo 2022-02-28 16:11:36.491 INFO: [68] [room=keenjunctionsgiveindoors@muc.meet.jitsi meeting_id=281cd05b-71bb-4d7c-8b60-cd9e24c2a89a] TranscriberManager.selectTranscriber#182: Attempting to invite transcriber
docker-jitsi-meet-jicofo-1   | Jicofo 2022-02-28 16:11:36.492 SEVERE: [68] Main.lambda$main$0#52: An uncaught exception occurred in thread=Thread[pool-7-thread-1,5,main]
docker-jitsi-meet-jicofo-1   | java.lang.NullPointerException
docker-jitsi-meet-jicofo-1   |  at org.jitsi.jicofo.jigasi.TranscriberManager.selectTranscriber(TranscriberManager.java:184)
docker-jitsi-meet-jicofo-1   |  at org.jitsi.jicofo.jigasi.TranscriberManager.startTranscribing(TranscriberManager.java:166)
docker-jitsi-meet-jicofo-1   |  at org.jitsi.jicofo.jigasi.TranscriberManager.lambda$memberPresenceChanged$0(TranscriberManager.java:138)
docker-jitsi-meet-jicofo-1   |  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
docker-jitsi-meet-jicofo-1   |  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
docker-jitsi-meet-jicofo-1   |  at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by damencho** [comment]
I think we need to update jigasi version there, this is known issue that was fixed.

**Comment by damencho** [comment]
I have no experience with docker, but if you can use the latest jigasi from unstable.

**Comment by bharatentropik** [comment]
I am getting the below error when I click on the CC button. I am using the latest code.

jicofo_1   | 2022-05-31T15:27:30.794085828Z Jicofo 2022-05-31 15:27:30.793 INFO: [45] [room=patientpromotionsruincynically@muc.meet.jitsi meeting_id=0856c568-1886-4b82-ba56-5505284cf3f0] TranscriberManager.selectTranscriber#182: Attempting to invite transcriber
jicofo_1   | 2022-05-31T15:27:30.794713989Z Jicofo 2022-05-31 15:27:30.794 SEVERE: [45] Main.lambda$main$0#52: An uncaught exception occurred in thread=Thread[pool-7-thread-4,5,main]
jicofo_1   | 2022-05-31T15:27:30.794731284Z java.lang.NullPointerException
jicofo_1   | 2022-05-31T15:27:30.794737343Z 	at org.jitsi.jicofo.jigasi.TranscriberManager.selectTranscriber(TranscriberManager.java:184)
jicofo_1   | 2022-05-31T15:27:30.794743089Z 	at org.jitsi.jicofo.jigasi.TranscriberManager.startTranscribing(TranscriberManager.java:166)
jicofo_1   | 2022-05-31T15:27:30.794748230Z 	at org.jitsi.jicofo.jigasi.TranscriberManager.lambda$memberPresenceChanged$0(TranscriberManager.java:138)
jicofo_1   | 2022-05-31T15:27:30.794765846Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
jicofo_1   | 2022-05-31T15:27:30.794772288Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
jicofo_1   | 2022-05-31T15:27:30.794776750Z 	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by bgrozev** [comment]
@bharatentropik do you have the jigasi detector configured?

**Comment by filwu8** [comment]
me too



> 
Vidoe-jicofo-1    | Jicofo 2022-08-10 14:20:55.908 INFO: [54] [room=%e6%a0%bc%e7%95%8c%e4%ba%91%e8%a7%86%e5%bc%80%e5%8f%91@muc.meet.jitsi meeting_id=05e03abf-7d4e-445e-8e89-7466b3878566] TranscriberManager.selectTranscriber#182: Attempting to invite transcriber
Vidoe-jicofo-1    | Jicofo 2022-08-10 14:20:55.908 SEVERE: [54] Main.lambda$main$0#52: An uncaught exception occurred in thread=Thread[pool-6-thread-2,5,main]
Vidoe-jicofo-1    | java.lang.NullPointerException
Vidoe-jicofo-1    |     at org.jitsi.jicofo.jigasi.TranscriberManager.selectTranscriber(TranscriberManager.java:184)
Vidoe-jicofo-1    |     at org.jitsi.jicofo.jigasi.TranscriberManager.startTranscribing(TranscriberManager.java:166)
Vidoe-jicofo-1    |     at org.jitsi.jicofo.jigasi.TranscriberManager.lambda$memberPresenceChanged$0(TranscriberManager.java:138)
Vidoe-jicofo-1    |     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Vidoe-jicofo-1    |     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Vidoe-jicofo-1    |     at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by filwu8** [comment]
> @bharatentropik do you have the jigasi detector configured?

how to check  jigasi detector configured?
