### ISSUE TITLE
Second JVB unable to connect to xmpp

### ISSUE THREAD

**Issue by pandel** [jitsi/docker-jitsi-meet#1258]
Hi!

Today I updated my setup (one server with full stack, second only with a JVB, everything running via docker) and now the second videobridge is not able to connect to Jicofo/Prosody anymore. Everything was working fine until now. I get the following errors in the log of the 2nd JVB (xxx=mydomain 😁 ):

```
JVB 2022-04-12 16:40:44.416 WARNING: [30] [hostname=xmpp.video.xxx.de id=shard] MucClient.setPresenceExtensions#449: Cannot set presence extension: not connected.
JVB 2022-04-12 16:40:44.592 WARNING: [22] [hostname=xmpp.video.xxx.de id=shard] MucClient.lambda$getConnectAndLoginCallable$7#622: [MucClient id=shard hostname=xmpp.video.xxx.de] error connecting
org.jivesoftware.smack.SmackException$NoResponseException: No response received within reply timeout. Timeout was 5000ms (~5s). While waiting for establishing TLS [XMPPTCPConnection[not-authenticated] (0)]
        at org.jivesoftware.smack.SmackException$NoResponseException.newWith(SmackException.java:99)
        at org.jivesoftware.smack.AbstractXMPPConnection.waitForConditionOrConnectionException(AbstractXMPPConnection.java:732)
        at org.jivesoftware.smack.AbstractXMPPConnection.waitForConditionOrThrowConnectionException(AbstractXMPPConnection.java:737)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:854)
        at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:529)
        at org.jitsi.xmpp.mucclient.MucClient.lambda$getConnectAndLoginCallable$7(MucClient.java:617)
        at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:167)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
JVB 2022-04-12 16:40:49.416 WARNING: [30] [hostname=xmpp.video.xxx.de id=shard] MucClient.setPresenceExtensions#449: Cannot set presence extension: not connected.
JVB 2022-04-12 16:40:49.516 WARNING: [14] org.jivesoftware.smackx.ping.PingManager.pingServerIfNecessary: XMPPTCPConnection[not-authenticated] (0) was not authenticated
```

I noticed that something regarding TCP has been disabled in the JVB's config. Can this lead to the problem?

EDIT: If I install ping on the second JVB's container and try to `ping xmpp.video.xxx.de` prosody container responds. So generally, a connection should be possible. But, I get no entry in the prosody log regarding the second JVB...

Regards,
Holger

**Comment by bgrozev** [comment]
> I noticed that something regarding TCP has been disabled in the JVB's config. Can this lead to the problem?

No, that's noot related at all.

**Comment by saghul** [comment]
Are they in the same Docker network?

**Comment by pandel** [comment]
Yes, they are. JVB2 is running on Docker slave, main Jitsi as master. I use this setup over a year now and it was working perfectly. In fact, this is my test system. I have an identical setup running in production, which is still working as I did not update it yet.

**Comment by pandel** [comment]
I set the log level of JVB2 to ALL and noticed the following lines:
```
{"log":"JVB 2022-04-13 11:06:38.077 WARNING: [30] [hostname=xmpp.video.xxx.de id=shard] MucClient.setPresenceExtensions#449: Cannot set presence extension: not connected.\n","stream":"stderr","time":"2022-04-13T09:06:38.0778313Z"}
{"log":"JVB 2022-04-13 11:06:38.140 FINER: [22] org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration: Trying to establish TCP connection to xmpp.video.xxx.de/10.0.3.12:5222\n","stream":"stderr","time":"2022-04-13T09:06:38.141049863Z"}                                                                                                              
{"log":"JVB 2022-04-13 11:06:38.142 FINER: [22] org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration: Established TCP connection to xmpp.video.xxx.de/10.0.3.12:5222\n","stream":"stderr","time":"2022-04-13T09:06:38.142525326Z"}
```

The last two lines are telling me, that the bridge is able to find Prosody through the Docker network. 

I compared both jvb.conf files, on main instance and on jvb2, and the only differences are MUC_NICKNAME and server-id for Websocket, which is absolutely fine.

If nothing helps I will reset the whole Docker network, separate the nodes and start all over again. But I would prefer not to do so but to find the problem...

**Comment by saghul** [comment]
Can you telnet to port 5222 of the prosody server from JVB 2?

**Comment by saghul** [comment]
Maybe it didn't get the resolver? What's in /etc/resolv.conf on jvb2?

**Comment by pandel** [comment]
In the JVB2 Docker container? Content is:
```
nameserver 127.0.0.11
options ndots:0
```

**Comment by saghul** [comment]
Right. Then I'm out of ideas sorry :-/

**Comment by FERCHOTRIX** [comment]
i solved
revisa la contraseña en el JMS y en JVB

  cat /etc/jitsi/videobridge/config | grep JVB_SECRET

en el JVB se debe reemplazar por la que tiene JMS
también revisa los puertos para ambos servidores

ufw allow 5347/tcp
ufw allow 5222/tcp
ufw allow 8888/tcp
ufw allow 8888/udp
ufw allow 8080/tcp
ufw allow 8080/udp
ufw allow 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp
ufw allow 4443/tcp
ufw allow 10000/udp
ufw allow 10000:20000/udp
ufw allow ssh
ufw default allow incoming && ufw enable && service ufw restart

luego ejecuta estos comandos en los servidores
JMS:
prosodyctl restart
systemctl start prosody

JVB:
sudo systemctl daemon-reload
/etc/init.d/jitsi-videobridge2 restart

espero te ayude

**Comment by benydc** [comment]
I'm having the same issue and error message, my setup, latest images and debian 11 Hosts:

Docker swarm with overlay network:

- Leader Host we have prosody(0.0.0.0:5222->5222/tcp, 0.0.0.0:5280->5280/tcp, 0.0.0.0:5347->5347/tcp) , web(0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp), jicofo and jvb(0.0.0.0:10000->10000/udp) containers
- Worker Host we have jvb(0.0.0.0:10000->10000/udp, 0.0.0.0:443->443/tcp)
- Leader JVB has the same Envs config as Worker JVB except the `JVB_MUC_NICKNAME` which is a unique name and `JVB_WS_SERVER_ID` as the internal private IP of the Worker JVB container.

The Leader JVB it's working fine but the Worker JVB logs I get error: 
```
JVB 2023-05-12 15:12:23.971 WARNING: [21] [hostname=prosody.vitahealth id=shard0] MucClient.lambda$getConnectAndLoginCallable$9#640: Error connecting:
org.jivesoftware.smack.SmackException$NoResponseException: No response received within reply timeout. Timeout was 5000ms (~5s). While waiting for establishing TLS [XMPPTCPConnection[not-authenticated] (0)]
	at org.jivesoftware.smack.SmackException$NoResponseException.newWith(SmackException.java:99)
```
No internal firewall on the Hosts
I can ping and telnet XMPP to the prosody from the Worker JVB Container successfully. 
The `JVB_AUTH_USER` and `JVB_AUTH_PASSWORD` have been set the same as Leader JVB and match the prosody env config.

I don't know what else to do and how can I debug it more.

**Comment by pdarcos** [comment]
We're seeing the exact same issue with the "MucClient.setPresenceExtensions#467: Cannot set presence extension: not connected. error message" on the second jvb. 
Has anyone managed to solve this?

**Comment by benydc** [comment]
> We're seeing the exact same issue with the "MucClient.setPresenceExtensions#467: Cannot set presence extension: not connected. error message" on the second jvb. Has anyone managed to solve this?

I solved my issue with docker MTU: https://forums.docker.com/t/tls-handshake-issues-in-docker-swarm-with-overlay-network/136065/2

**Comment by pdarcos** [comment]
> > We're seeing the exact same issue with the "MucClient.setPresenceExtensions#467: Cannot set presence extension: not connected. error message" on the second jvb. Has anyone managed to solve this?
> 
> I solved my issue with docker MTU: https://forums.docker.com/t/tls-handshake-issues-in-docker-swarm-with-overlay-network/136065/2

Thanks for the tip. Going to look into that

**Comment by pdarcos** [comment]
Unfortunately that docker MTU tip was not the solution for us.

We have tested with and without docker and we experience the same problem even when the second jvb runs in a normal (non-docker) instance., so the origin of this bug remains elusive.
