### ISSUE TITLE
Got jibri status off and failure error

### ISSUE THREAD

**Issue by kinseii** [jitsi/docker-jitsi-meet#1291]
I installed jitsi for docker-compose according to the manual. Video conferencing works fine. But I can't get the recording and broadcasting to work. There is a problem with jibri.

Here logs from `docker-compose logs`
```
jicofo_1   | Jicofo 2022-05-25 09:29:33.543 INFO: [33] [room=freebur@muc.meet.jitsi meeting_id=66ca1082-b1f6-43ba-ab5d-29ac6e73f0db] BaseJibri.handleJibriRequest#75: Accepted jibri request: <iq xmlns='jabber:client' to='focus@auth.meet.jitsi/focus' from='freebur@muc.meet.jitsi/17dbd0db' id='Zm9jdXNAYXV0aC5tZWV0LmppdHNpL2ZvY3VzADM0YTUzMTI1LTY3OGQtNGZlNi1iODg5LTY5Mjg0MWQ4M2NiMTpzZW5kSVEAmN63Q/5oMUs=' type='set'><jibri xmlns='http://jitsi.org/protocol/jibri' action='start' recording_mode='file' app_data='{"file_recording_metadata":{"share":true}}'/></iq>
jicofo_1   | Jicofo 2022-05-25 09:29:33.570 INFO: [40] [room=freebur@muc.meet.jitsi meeting_id=66ca1082-b1f6-43ba-ab5d-29ac6e73f0db] JibriSession.startInternal#319: Starting session with Jibri jibribrewery@internal-muc.meet.jitsi/jibri-774872007
jicofo_1   | Jicofo 2022-05-25 09:29:33.589 INFO: [40] [room=freebur@muc.meet.jitsi meeting_id=66ca1082-b1f6-43ba-ab5d-29ac6e73f0db] JibriSession.sendJibriStartIq#473: Starting Jibri jibribrewery@internal-muc.meet.jitsi/jibri-774872007 for stream ID: null in room: freebur@muc.meet.jitsi
jvb_1      | JVB 2022-05-25 09:29:34.548 INFO: [25] VideobridgeExpireThread.expire#140: Running expire()
jicofo_1   | Jicofo 2022-05-25 09:29:36.013 INFO: [40] [room=freebur@muc.meet.jitsi meeting_id=66ca1082-b1f6-43ba-ab5d-29ac6e73f0db] JibriSession.processJibriIqFromJibri#434: Updating status from JIBRI: <iq xmlns='jabber:client' to='focus@auth.meet.jitsi/focus' from='jibribrewery@internal-muc.meet.jitsi/jibri-774872007' id='W62UH-42' type='result'><jibri xmlns='http://jitsi.org/protocol/jibri' status='pending'/></iq> for freebur@muc.meet.jitsi
jicofo_1   | Jicofo 2022-05-25 09:29:36.050 INFO: [40] [room=freebur@muc.meet.jitsi meeting_id=66ca1082-b1f6-43ba-ab5d-29ac6e73f0db] JibriSession.handleJibriStatusUpdate#622: Got Jibri status update: Jibri jibribrewery@internal-muc.meet.jitsi/jibri-774872007 has status pending and failure reason null, current Jibri jid is jibribrewery@internal-muc.meet.jitsi/jibri-774872007
jicofo_1   | Jicofo 2022-05-25 09:29:36.051 INFO: [40] [room=freebur@muc.meet.jitsi meeting_id=66ca1082-b1f6-43ba-ab5d-29ac6e73f0db] JibriRecorder.handleStartRequest#113: Started Jibri session
jicofo_1   | Jicofo 2022-05-25 09:29:36.426 INFO: [33] [room=freebur@muc.meet.jitsi meeting_id=66ca1082-b1f6-43ba-ab5d-29ac6e73f0db] BaseJibri.handleJibriRequest#75: Accepted jibri request: <iq xmlns='jabber:client' to='focus@auth.meet.jitsi/focus' from='jibribrewery@internal-muc.meet.jitsi/jibri-774872007' id='Zm9jdXNAYXV0aC5tZWV0LmppdHNpL2ZvY3VzAFFZSElZLTkA5F8AFDSTWJM=' type='set'><jibri xmlns='http://jitsi.org/protocol/jibri' status='off' failure_reason='error' should_retry='true'/></iq>
jicofo_1   | Jicofo 2022-05-25 09:29:36.427 INFO: [40] [room=freebur@muc.meet.jitsi meeting_id=66ca1082-b1f6-43ba-ab5d-29ac6e73f0db] JibriSession.processJibriIqFromJibri#434: Updating status from JIBRI: <iq xmlns='jabber:client' to='focus@auth.meet.jitsi/focus' from='jibribrewery@internal-muc.meet.jitsi/jibri-774872007' id='Zm9jdXNAYXV0aC5tZWV0LmppdHNpL2ZvY3VzAFFZSElZLTkA5F8AFDSTWJM=' type='set'><jibri xmlns='http://jitsi.org/protocol/jibri' status='off' failure_reason='error' should_retry='true'/></iq> for freebur@muc.meet.jitsi
jicofo_1   | Jicofo 2022-05-25 09:29:36.427 INFO: [40] [room=freebur@muc.meet.jitsi meeting_id=66ca1082-b1f6-43ba-ab5d-29ac6e73f0db] JibriSession.handleJibriStatusUpdate#622: Got Jibri status update: Jibri jibribrewery@internal-muc.meet.jitsi/jibri-774872007 has status off and failure reason error, current Jibri jid is jibribrewery@internal-muc.meet.jitsi/jibri-774872007
jicofo_1   | Jicofo 2022-05-25 09:29:36.428 INFO: [40] [room=freebur@muc.meet.jitsi meeting_id=66ca1082-b1f6-43ba-ab5d-29ac6e73f0db] JibriSession.handleJibriStatusUpdate#661: Jibri failed, trying to fall back to another Jibri
jicofo_1   | Jicofo 2022-05-25 09:29:36.428 SEVERE: [40] [room=freebur@muc.meet.jitsi meeting_id=66ca1082-b1f6-43ba-ab5d-29ac6e73f0db] JibriSession.startInternal#307: Unable to find an available Jibri, can't start
jicofo_1   | Jicofo 2022-05-25 09:29:36.430 WARNING: [40] [room=freebur@muc.meet.jitsi meeting_id=66ca1082-b1f6-43ba-ab5d-29ac6e73f0db] JibriSession.handleJibriStatusUpdate#672: Failed to fall back to another Jibri, this session has now failed: org.jitsi.jicofo.jibri.JibriSession$StartException$AllBusy: All jibri instances are busy
jicofo_1   | org.jitsi.jicofo.jibri.JibriSession$StartException$AllBusy: All jibri instances are busy
jicofo_1   |    at org.jitsi.jicofo.jibri.JibriSession.startInternal(JibriSession.java:311)
jicofo_1   |    at org.jitsi.jicofo.jibri.JibriSession.start(JibriSession.java:285)
jicofo_1   |    at org.jitsi.jicofo.jibri.JibriSession.retryRequestWithAnotherJibri(JibriSession.java:598)
jicofo_1   |    at org.jitsi.jicofo.jibri.JibriSession.handleJibriStatusUpdate(JibriSession.java:665)
jicofo_1   |    at org.jitsi.jicofo.jibri.JibriSession.processJibriIqFromJibri(JibriSession.java:436)
jicofo_1   |    at org.jitsi.jicofo.jibri.JibriSession.processJibriIqRequestFromJibri(JibriSession.java:420)
jicofo_1   |    at org.jitsi.jicofo.jibri.BaseJibri.doHandleIQRequest(BaseJibri.kt:156)
jicofo_1   |    at org.jitsi.jicofo.jibri.BaseJibri.incomingIqQueue$lambda-0(BaseJibri.kt:56)
jicofo_1   |    at org.jitsi.utils.queue.PacketQueue$HandlerAdapter.handleItem(PacketQueue.java:416)
jicofo_1   |    at org.jitsi.utils.queue.AsyncQueueHandler$1.run(AsyncQueueHandler.java:136)
jicofo_1   |    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
jicofo_1   |    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
jicofo_1   |    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
jicofo_1   |    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
jicofo_1   |    at java.base/java.lang.Thread.run(Thread.java:829)
jicofo_1   | Jicofo 2022-05-25 09:29:36.432 INFO: [40] [room=freebur@muc.meet.jitsi meeting_id=66ca1082-b1f6-43ba-ab5d-29ac6e73f0db] JibriRecorder.publishJibriRecordingStatus#158: Got jibri status off and failure error
jicofo_1   | Jicofo 2022-05-25 09:29:36.434 INFO: [40] [room=freebur@muc.meet.jitsi meeting_id=66ca1082-b1f6-43ba-ab5d-29ac6e73f0db] JibriRecorder.publishJibriRecordingStatus#183: Publishing new jibri-recording-status: <jibri-recording-status xmlns='http://jitsi.org/protocol/jibri' status='off' failure_reason='error' session_id='xsxdixykpydpvqyo' recording_mode='file'/> in: freebur@muc.meet.jitsi
jicofo_1   | Jicofo 2022-05-25 09:29:36.436 INFO: [40] [room=freebur@muc.meet.jitsi meeting_id=66ca1082-b1f6-43ba-ab5d-29ac6e73f0db] JibriSession.cleanupSession#389: Cleaning up current JibriSession
jicofo_1   | Jicofo 2022-05-25 09:29:44.047 INFO: [33] [room=freebur@muc.meet.jitsi meeting_id=66ca1082-b1f6-43ba-ab5d-29ac6e73f0db] BaseJibri.handleJibriRequest#75: Accepted jibri request: <iq xmlns='jabber:client' to='focus@auth.meet.jitsi/focus' from='freebur@muc.meet.jitsi/17dbd0db' id='Zm9jdXNAYXV0aC5tZWV0LmppdHNpL2ZvY3VzADIwNTk5YzVjLTA2Y2EtNDM5YS1hZGJlLTNjODczYTFiNTcyODpzZW5kSVEAmN63Q/5oMUs=' type='set'><jibri xmlns='http://jitsi.org/protocol/jibri' action='start' recording_mode='stream' streamid='gftr-9f0f-yv3h-9j69-1xse'/></iq>
jicofo_1   | Jicofo 2022-05-25 09:29:44.049 INFO: [40] [room=freebur@muc.meet.jitsi meeting_id=66ca1082-b1f6-43ba-ab5d-29ac6e73f0db] JibriSession.startInternal#319: Starting session with Jibri jibribrewery@internal-muc.meet.jitsi/jibri-774872007
jicofo_1   | Jicofo 2022-05-25 09:29:44.050 INFO: [40] [room=freebur@muc.meet.jitsi meeting_id=66ca1082-b1f6-43ba-ab5d-29ac6e73f0db] JibriSession.sendJibriStartIq#473: Starting Jibri jibribrewery@internal-muc.meet.jitsi/jibri-774872007 for stream ID: gftr-9f0f-yv3h-9j69-1xse in room: freebur@muc.meet.jitsi
jicofo_1   | Jicofo 2022-05-25 09:29:45.385 INFO: [40] [room=freebur@muc.meet.jitsi meeting_id=66ca1082-b1f6-43ba-ab5d-29ac6e73f0db] JibriSession.processJibriIqFromJibri#434: Updating status from JIBRI: <iq xmlns='jabber:client' to='focus@auth.meet.jitsi/focus' from='jibribrewery@internal-muc.meet.jitsi/jibri-774872007' id='W62UH-49' type='result'><jibri xmlns='http://jitsi.org/protocol/jibri' status='pending'/></iq> for freebur@muc.meet.jitsi
jicofo_1   | Jicofo 2022-05-25 09:29:45.385 INFO: [40] [room=freebur@muc.meet.jitsi meeting_id=66ca1082-b1f6-43ba-ab5d-29ac6e73f0db] JibriSession.handleJibriStatusUpdate#622: Got Jibri status update: Jibri jibribrewery@internal-muc.meet.jitsi/jibri-774872007 has status pending and failure reason null, current Jibri jid is jibribrewery@internal-muc.meet.jitsi/jibri-774872007
jicofo_1   | Jicofo 2022-05-25 09:29:45.386 INFO: [40] [room=freebur@muc.meet.jitsi meeting_id=66ca1082-b1f6-43ba-ab5d-29ac6e73f0db] JibriRecorder.handleStartRequest#113: Started Jibri session
jicofo_1   | Jicofo 2022-05-25 09:29:45.913 INFO: [23] [room=freebur@muc.meet.jitsi meeting_id=66ca1082-b1f6-43ba-ab5d-29ac6e73f0db] BaseJibri.handleJibriRequest#75: Accepted jibri request: <iq xmlns='jabber:client' to='focus@auth.meet.jitsi/focus' from='jibribrewery@internal-muc.meet.jitsi/jibri-774872007' id='Zm9jdXNAYXV0aC5tZWV0LmppdHNpL2ZvY3VzAFFZSElZLTEzAORfABQ0k1iT' type='set'><jibri xmlns='http://jitsi.org/protocol/jibri' status='off' failure_reason='error' should_retry='true'/></iq>
jicofo_1   | Jicofo 2022-05-25 09:29:45.915 INFO: [40] [room=freebur@muc.meet.jitsi meeting_id=66ca1082-b1f6-43ba-ab5d-29ac6e73f0db] JibriSession.processJibriIqFromJibri#434: Updating status from JIBRI: <iq xmlns='jabber:client' to='focus@auth.meet.jitsi/focus' from='jibribrewery@internal-muc.meet.jitsi/jibri-774872007' id='Zm9jdXNAYXV0aC5tZWV0LmppdHNpL2ZvY3VzAFFZSElZLTEzAORfABQ0k1iT' type='set'><jibri xmlns='http://jitsi.org/protocol/jibri' status='off' failure_reason='error' should_retry='true'/></iq> for freebur@muc.meet.jitsi
jicofo_1   | Jicofo 2022-05-25 09:29:45.915 INFO: [40] [room=freebur@muc.meet.jitsi meeting_id=66ca1082-b1f6-43ba-ab5d-29ac6e73f0db] JibriSession.handleJibriStatusUpdate#622: Got Jibri status update: Jibri jibribrewery@internal-muc.meet.jitsi/jibri-774872007 has status off and failure reason error, current Jibri jid is jibribrewery@internal-muc.meet.jitsi/jibri-774872007
jicofo_1   | Jicofo 2022-05-25 09:29:45.916 INFO: [40] [room=freebur@muc.meet.jitsi meeting_id=66ca1082-b1f6-43ba-ab5d-29ac6e73f0db] JibriSession.handleJibriStatusUpdate#661: Jibri failed, trying to fall back to another Jibri
jicofo_1   | Jicofo 2022-05-25 09:29:45.916 SEVERE: [40] [room=freebur@muc.meet.jitsi meeting_id=66ca1082-b1f6-43ba-ab5d-29ac6e73f0db] JibriSession.startInternal#307: Unable to find an available Jibri, can't start
jicofo_1   | Jicofo 2022-05-25 09:29:45.916 WARNING: [40] [room=freebur@muc.meet.jitsi meeting_id=66ca1082-b1f6-43ba-ab5d-29ac6e73f0db] JibriSession.handleJibriStatusUpdate#672: Failed to fall back to another Jibri, this session has now failed: org.jitsi.jicofo.jibri.JibriSession$StartException$AllBusy: All jibri instances are busy
jicofo_1   | org.jitsi.jicofo.jibri.JibriSession$StartException$AllBusy: All jibri instances are busy
jicofo_1   |    at org.jitsi.jicofo.jibri.JibriSession.startInternal(JibriSession.java:311)
jicofo_1   |    at org.jitsi.jicofo.jibri.JibriSession.start(JibriSession.java:285)
jicofo_1   |    at org.jitsi.jicofo.jibri.JibriSession.retryRequestWithAnotherJibri(JibriSession.java:598)
jicofo_1   |    at org.jitsi.jicofo.jibri.JibriSession.handleJibriStatusUpdate(JibriSession.java:665)
jicofo_1   |    at org.jitsi.jicofo.jibri.JibriSession.processJibriIqFromJibri(JibriSession.java:436)
jicofo_1   |    at org.jitsi.jicofo.jibri.JibriSession.processJibriIqRequestFromJibri(JibriSession.java:420)
jicofo_1   |    at org.jitsi.jicofo.jibri.BaseJibri.doHandleIQRequest(BaseJibri.kt:156)
jicofo_1   |    at org.jitsi.jicofo.jibri.BaseJibri.incomingIqQueue$lambda-0(BaseJibri.kt:56)
jicofo_1   |    at org.jitsi.utils.queue.PacketQueue$HandlerAdapter.handleItem(PacketQueue.java:416)
jicofo_1   |    at org.jitsi.utils.queue.AsyncQueueHandler$1.run(AsyncQueueHandler.java:136)
jicofo_1   |    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
jicofo_1   |    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
jicofo_1   |    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
jicofo_1   |    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
jicofo_1   |    at java.base/java.lang.Thread.run(Thread.java:829)
jicofo_1   | Jicofo 2022-05-25 09:29:45.917 INFO: [40] [room=freebur@muc.meet.jitsi meeting_id=66ca1082-b1f6-43ba-ab5d-29ac6e73f0db] JibriRecorder.publishJibriRecordingStatus#158: Got jibri status off and failure error
jicofo_1   | Jicofo 2022-05-25 09:29:45.917 INFO: [40] [room=freebur@muc.meet.jitsi meeting_id=66ca1082-b1f6-43ba-ab5d-29ac6e73f0db] JibriRecorder.publishJibriRecordingStatus#183: Publishing new jibri-recording-status: <jibri-recording-status xmlns='http://jitsi.org/protocol/jibri' status='off' failure_reason='error' session_id='foheawislzsaqinw' recording_mode='stream'/> in: freebur@muc.meet.jitsi
jicofo_1   | Jicofo 2022-05-25 09:29:45.919 INFO: [40] [room=freebur@muc.meet.jitsi meeting_id=66ca1082-b1f6-43ba-ab5d-29ac6e73f0db] JibriSession.cleanupSession#389: Cleaning up current JibriSession
```

And yet one log from jibri:
```
Jibri 2022-05-25 09:29:45.896 SEVERE: [58] [session_id=foheawislzsaqinw] JibriSelenium$joinCall$1.run#325: An error occurred while joining the call
org.openqa.selenium.WebDriverException: unknown error: net::ERR_CONNECTION_REFUSED
  (Session info: chrome=101.0.4951.41)
  (Driver info: chromedriver=101.0.4951.41 (93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}),platform=Linux 5.18.0-051800-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'eddaf042ab94', ip: '172.28.0.6', os.name: 'Linux', os.arch: 'amd64', os.version: '5.18.0-051800-generic', java.version: '11.0.15'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 101.0.4951.41 (93c720db8323..., userDataDir: /tmp/.com.google.Chrome.4iOXyB}, cssSelectorsEnabled: true, databaseEnabled: false, goog:chromeOptions: {debuggerAddress: localhost:35167}, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), rotatable: false, setWindowRect: true, strictFileInteractability: false, takesHeapSnapshot: true, takesScreenshot: true, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unexpectedAlertBehaviour: ignore, unhandledPromptBehavior: ignore, version: 101.0.4951.41, webStorageEnabled: true, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: cdc34dc57d89ff12053d4feb73643bb1
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
        at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
        at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
        at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
        at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
        at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:271)
        at org.jitsi.jibri.selenium.pageobjects.AbstractPageObject.visit(AbstractPageObject.kt:35)
        at org.jitsi.jibri.selenium.JibriSelenium$joinCall$1.run(JibriSelenium.kt:293)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Jibri 2022-05-25 09:29:45.897 INFO: [58] [session_id=foheawislzsaqinw] JibriSelenium.onSeleniumStateChange#215: Transitioning from state Starting up to Error: FailedToJoinCall SESSION Failed to join the call
Jibri 2022-05-25 09:29:45.897 INFO: [58] [session_id=foheawislzsaqinw] StatefulJibriService.onServiceStateChange#39: Streaming service transitioning from state Starting up to Error: FailedToJoinCall SESSION Failed to join the call
Jibri 2022-05-25 09:29:45.898 INFO: [58] XmppApi$createServiceStatusHandler$1.invoke#311: Current service had an error Error: FailedToJoinCall SESSION Failed to join the call, sending error iq <iq xmlns='jabber:client' to='jibribrewery@internal-muc.meet.jitsi/focus' id='QYHIY-13' type='set'><jibri xmlns='http://jitsi.org/protocol/jibri' status='off' failure_reason='error' should_retry='true'/></iq>
Jibri 2022-05-25 09:29:45.899 FINE: [58] JibriStatsDClient.incrementCounter#38: Incrementing statsd counter: stop:live_stream
Jibri 2022-05-25 09:29:45.899 INFO: [58] JibriManager.stopService#260: Stopping the current service
Jibri 2022-05-25 09:29:45.900 INFO: [58] [session_id=foheawislzsaqinw] StreamingJibriService.stop#137: Stopping capturer
Jibri 2022-05-25 09:29:45.900 INFO: [58] [session_id=foheawislzsaqinw] JibriSubprocess.stop#75: Stopping ffmpeg process
Jibri 2022-05-25 09:29:45.900 INFO: [58] [session_id=foheawislzsaqinw] JibriSubprocess.stop#89: ffmpeg exited with value null
Jibri 2022-05-25 09:29:45.901 INFO: [58] [session_id=foheawislzsaqinw] StreamingJibriService.stop#139: Stopped capturer
Jibri 2022-05-25 09:29:45.901 INFO: [58] [session_id=foheawislzsaqinw] StreamingJibriService.stop#140: Quitting selenium
Jibri 2022-05-25 09:29:45.902 INFO: [58] [session_id=foheawislzsaqinw] JibriSelenium.leaveCallAndQuitBrowser#336: Leaving call and quitting browser
Jibri 2022-05-25 09:29:45.902 INFO: [58] [session_id=foheawislzsaqinw] JibriSelenium.leaveCallAndQuitBrowser#339: Recurring call status checks cancelled
Jibri 2022-05-25 09:29:45.935 INFO: [58] [session_id=foheawislzsaqinw] JibriSelenium.leaveCallAndQuitBrowser#345: Got 3 log entries for type browser
Jibri 2022-05-25 09:29:45.996 INFO: [58] [session_id=foheawislzsaqinw] JibriSelenium.leaveCallAndQuitBrowser#345: Got 468 log entries for type driver
Jibri 2022-05-25 09:29:46.079 INFO: [58] [session_id=foheawislzsaqinw] JibriSelenium.leaveCallAndQuitBrowser#345: Got 0 log entries for type client
Jibri 2022-05-25 09:29:46.081 INFO: [58] [session_id=foheawislzsaqinw] JibriSelenium.leaveCallAndQuitBrowser#354: Leaving web call
Jibri 2022-05-25 09:29:46.125 INFO: [58] [session_id=foheawislzsaqinw] JibriSelenium.leaveCallAndQuitBrowser#361: Quitting chrome driver
Jibri 2022-05-25 09:29:46.203 INFO: [58] [session_id=foheawislzsaqinw] JibriSelenium.leaveCallAndQuitBrowser#363: Chrome driver quit
Jibri 2022-05-25 09:29:46.203 INFO: [58] [session_id=foheawislzsaqinw] StreamingJibriService.stop#142: Quit selenium
Jibri 2022-05-25 09:29:46.204 INFO: [58] JibriStatusManager$$special$$inlined$observable$1.afterChange#72: Busy status has changed: BUSY -> IDLE
Jibri 2022-05-25 09:29:46.204 FINE: [58] WebhookClient$updateStatus$1.invokeSuspend#107: Updating 0 subscribers of status
Jibri 2022-05-25 09:29:46.205 INFO: [58] XmppApi.updatePresence#203: Jibri reports its status is now JibriStatus(busyStatus=IDLE, health=OverallHealth(healthStatus=HEALTHY, details={})), publishing presence to connections
Jibri 2022-05-25 09:29:46.205 FINE: [58] MucClientManager.setPresenceExtension#160: Setting a presence extension: org.jitsi.xmpp.extensions.jibri.JibriStatusPacketExt@eb6f763
Jibri 2022-05-25 09:29:46.205 FINE: [58] MucClientManager.saveExtension#185: Replacing presence extension: org.jitsi.xmpp.extensions.jibri.JibriStatusPacketExt@17d49392
Jibri 2022-05-25 09:29:46.213 FINE: [44] org.jitsi.xmpp.extensions.DefaultPacketExtensionProvider.parse: Could not add a provider for element busy-status from namespace http://jitsi.org/protocol/jibri
Jibri 2022-05-25 09:29:46.215 FINE: [44] org.jitsi.xmpp.extensions.DefaultPacketExtensionProvider.parse: Could not add a provider for element health-status from namespace http://jitsi.org/protocol/health
Jibri 2022-05-25 09:30:35.108 FINE: [20] WebhookClient$updateStatus$1.invokeSuspend#107: Updating 0 subscribers of status
```

browser.txt file is very large, but I found these lines:
```
                     "attributes": [ "class", "suggestions", "jsselect", "suggestionsDetails", "jstcache", "3", "jsinstance", "1" ],
                     "backendNodeId": 349,
                     "childNodeCount": 2,
                     "children": [ {
                        "attributes": [ "class", "suggestion-header", "jsvalues", ".innerHTML:header", "jstcache", "7" ],
                        "backendNodeId": 368,
                        "childNodeCount": 1,
                        "children": [ {
                           "backendNodeId": 369,
                           "localName": "",
                           "nodeId": 674,
                           "nodeName": "#text",
                           "nodeType": 3,
                           "nodeValue": "Allow Chrome to access the network in your firewall or antivirus\n          settings.",
                           "parentId": 673
                        } ],
                        "localName": "div",
                        "nodeId": 673,
                        "nodeName": "DIV",
                        "nodeType": 1,
                        "nodeValue": "",
                        "parentId": 672
                     }, {
                        "attributes": [ "class", "suggestion-body", "jsvalues", ".innerHTML:body", "jstcache", "8" ],
                        "backendNodeId": 370,
                        "childNodeCount": 1,
                        "children": [ {
                           "backendNodeId": 371,
                           "localName": "",
                           "nodeId": 676,
                           "nodeName": "#text",
                           "nodeType": 3,
                           "nodeValue": "If it is already listed as a program allowed to access the network, try\n      removing it from the list and adding it again.",
                           "parentId": 675
                        } ],
                        "localName": "div",
                        "nodeId": 675,
                        "nodeName": "DIV",
                        "nodeType": 1,
                        "nodeValue": "",
                        "parentId": 672
                     } ],
                     "localName": "div",
                     "nodeId": 672,
                     "nodeName": "DIV",
                     "nodeType": 1,
                     "nodeValue": "",
                     "parentId": 666
                  }, {
                     "attributes": [ "class", "suggestions", "jsselect", "suggestionsDetails", "jstcache", "3", "jsinstance", "*2" ],
                     "backendNodeId": 321,
                     "childNodeCount": 2,
                     "children": [ {
                        "attributes": [ "class", "suggestion-header", "jsvalues", ".innerHTML:header", "jstcache", "7" ],
                        "backendNodeId": 322,
                        "childNodeCount": 1,
                        "children": [ {
                           "backendNodeId": 350,
                           "localName": "",
                           "nodeId": 679,
                           "nodeName": "#text",
                           "nodeType": 3,
                           "nodeValue": "If you use a proxy server?",
                           "parentId": 678
                        } ],
                        "localName": "div",
                        "nodeId": 678,
                        "nodeName": "DIV",
                        "nodeType": 1,
                        "nodeValue": "",
                        "parentId": 677
                     }, {
                        "attributes": [ "class", "suggestion-body", "jsvalues", ".innerHTML:body", "jstcache", "8" ],
                        "backendNodeId": 323,
                        "childNodeCount": 7,
                        "children": [ {
                           "backendNodeId": 351,
                           "localName": "",
                           "nodeId": 681,
                           "nodeName": "#text",
                           "nodeType": 3,
                           "nodeValue": "Check your proxy settings or contact your network administrator to\n      make sure the proxy server is working. If you don't believe you should\n      be using a proxy server:\n      Go to\n          ...",
```

A few days ago I installed Jitsi docker-compose on another server and everything worked fine. I just copied the project and ran it on the new server, but here Jibri doesn't work.

Please help.

**Comment by kinseii** [comment]
n addition I found a chromedriver log inside the jitsi container:

```
[1653609528.521][INFO]: Starting ChromeDriver 101.0.4951.41 (93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}) on port 23638
[1653609528.522][INFO]: Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[1653609528.526][SEVERE]: bind() failed: Cannot assign requested address (99)
[1653609528.526][INFO]: listen on IPv6 failed with error ERR_ADDRESS_INVALID
```

**Comment by nepobo** [comment]
> The problem was solved by removing from the /etc/hosts file the domain which was the main one for jitsi.
Great thanks. I has same problem. You save my work time.

**Comment by liangguohao66** [comment]
> The problem was solved by removing from the /etc/hosts file the domain which was the main one for jitsi.

why?
