### ISSUE TITLE
Session disconnects immidiatly

### ISSUE THREAD

**Issue by joukj** [jitsi/docker-jitsi-meet#1383]
Since installing version 7648-3  I experience the following:

When trying to open a meeting it immediately is disconnected giving a screen like the picture shown
![Screenshot from 2022-08-23 10-18-45](https://user-images.githubusercontent.com/11192357/186190782-59fa4764-590e-49b0-bdc5-1a71b7f7425e.png)
If tryiing to reconnect (or wait out the tiimeout) the same happens.

I'm running docker-jitsi on a Fedora 36 system with Moby as the docker-stack.

The JS-console-logs are as follows when  it happens:

2022-08-23T09:48:53.254Z [modules/xmpp/strophe.util.js] <79/sa/ut.Strophe.log>: Strophe: Disconnect was called because: undefined Logger.js:154:22
2022-08-23T09:48:53.255Z [modules/xmpp/strophe.util.js] <79/sa/ut.Strophe.log>: Strophe: Disconnect was called before Strophe connected to the server Logger.js:154:22
2022-08-23T09:48:53.257Z [modules/xmpp/xmpp.js] : (TIME) Strophe disconnected: 25359 Logger.js:154:22
2022-08-23T09:48:53.258Z [modules/statistics/statistics.js] <79/Tn.sendAnalyticsAndLog>: {"type":"operational","action":"connection.failed","attributes":{"error_type":"connection.otherError","error_message":"The WebSocket connection could not be established or was disconnected.","suspend_time":0,"time_since_last_success":null}} Logger.js:154:22
This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “”.
[test](https://vleegert.nano.tudelft.nl:8443/test#config.startWithAudioMuted=false&config.startWithVideoMuted=true)
(TIME) index.html loaded: 1716 [test:62:17](https://vleegert.nano.tudelft.nl:8443/test#config.startWithAudioMuted=false&config.startWithVideoMuted=true)
2022-08-23T09:48:55.511Z [modules/browser/BrowserCapabilities.js] This appears to be firefox, ver: 103.0 Logger.js:154:22
2022-08-23T09:48:55.514Z [modules/statistics/LocalStatsCollector.js] <79/tn.connectAudioContext>: Connecting audio context Logger.js:154:22
An AudioContext was prevented from starting automatically. It must be created or resumed after a user gesture on the page. LocalStatsCollector.js:169:14
2022-08-23T09:48:57.048Z [features/base/redux] : redux state persisted. 30a9d6244a3b5176da863c11b5150a16 -> 2c7a6ae3b5500f2bfd84ff5a606f2eae Logger.js:152:50
2022-08-23T09:48:57.339Z [features/base/config] <5027/Qn/<>: Extending config with: {"startWithAudioMuted":false,"startWithVideoMuted":true} Logger.js:152:50
2022-08-23T09:48:57.350Z [FeatureFlags] : Source name signaling: true, Send multiple video streams: true, SSRC rewriting supported: false, uses Unified plan: true Logger.js:154:22
2022-08-23T09:48:57.352Z [modules/RTC/RTCUtils.js] : Disable AP: false Logger.js:154:22
2022-08-23T09:48:57.353Z [modules/RTC/RTCUtils.js] : Stereo: false Logger.js:154:22
2022-08-23T09:48:57.354Z [modules/connectivity/NetworkInfo.js] : updateNetworkInfo
Object { isOnline: true }
Logger.js:154:22
2022-08-23T09:48:57.374Z [features/base/media] <5027/</</</<>: Start muted: video Logger.js:152:50
2022-08-23T09:48:57.393Z [features/base/media] <5027/</</</<>: Start audio only set to false Logger.js:152:50
2022-08-23T09:48:57.398Z [modules/statistics/AnalyticsAdapter.js] : Disposing of analytics adapter. Logger.js:154:22
2022-08-23T09:48:57.399Z [features/analytics] <5027/</</</a<>: Initialized 0 analytics handlers Logger.js:152:50
2022-08-23T09:48:57.649Z [features/base/devices] : setAudioOutputDevice: undefined[default] Logger.js:152:50
2022-08-23T09:48:57.650Z [features/base/devices] : Adjusting audio output is not supported Logger.js:152:50
2022-08-23T09:48:57.674Z [index.web] <5027/<>: (TIME) document ready: 4252 Logger.js:152:50
Service worker registered.
ServiceWorkerRegistration { installing: null, waiting: null, active: ServiceWorker, navigationPreload: NavigationPreloadManager, scope: "https://vleegert.nano.tudelft.nl:8443/", updateViaCache: "imports", onupdatefound: null, pushManager: PushManager }
[test:45:33](https://vleegert.nano.tudelft.nl:8443/test#config.startWithAudioMuted=false&config.startWithVideoMuted=true)
2022-08-23T09:48:58.044Z [modules/RTC/RTCUtils.js] : list of media devices has changed:
Array [ MediaDeviceInfo ]
Logger.js:154:22
2022-08-23T09:48:58.051Z [modules/RTC/RTCUtils.js] <79/init/<>: Available devices:
Array [ MediaDeviceInfo ]
Logger.js:154:22
2022-08-23T09:48:58.226Z [features/base/devices] <5027/</</</<>: Device list updated:
audioInput:
[4bKiUxVGFMtc4rtt/htwN9FMPk1qBa5MtL/e/zhrEPM=]
audioOutput:

videoInput:
Logger.js:152:50
2022-08-23T09:48:58.433Z [features/base/connection] <5027/Hle/o<>: Using service URL wss://vleegert.nano.tudelft.nl:8443/xmpp-websocket Logger.js:152:50
2022-08-23T09:48:58.441Z [modules/xmpp/xmpp.js] <_initStrophePlugins>: P2P STUN servers:
Array [ {…} ]
Logger.js:154:22
2022-08-23T09:48:58.490Z [modules/xmpp/xmpp.js] : Source-name signaling is enabled Logger.js:154:22
2022-08-23T09:48:58.503Z [modules/xmpp/xmpp.js] : Receiving multiple video streams is enabled Logger.js:154:22
2022-08-23T09:48:58.507Z [modules/xmpp/xmpp.js] : (TIME) Strophe connecting: 5084 Logger.js:154:22
2022-08-23T09:48:58.550Z [features/prejoin] <5027/Yie/<>: Failed to execute pre call test - Error: Callstats is disabled
init PrecallTest.js:85
Yie actions.js:316
n React
5027 middleware.js:27
5027 middleware.js:32
5027 middleware.js:18
5027 middleware.web.js:26
5027 middleware.any.js:42
5027 actions.js:58
5027 middleware.js:41
5027 middleware.js:61
Logger.js:152:50
2022-08-23T09:48:58.629Z [modules/RTC/RTCUtils.js] <79/obtainAudioAndVideoPermissions/r<>: Got media constraints: {"video":false,"audio":{"autoGainControl":true,"echoCancellation":true,"noiseSuppression":true}} Logger.js:154:22
2022-08-23T09:48:58.775Z [features/base/lastn] <5027/bde<>: There is no active conference, not updating last N Logger.js:152:50
2022-08-23T09:48:59.035Z [features/base/redux] : redux state persisted. 2c7a6ae3b5500f2bfd84ff5a606f2eae -> cdf042d5ab60ec2d80c76c0fd1634324 Logger.js:152:50
2022-08-23T09:48:59.173Z [modules/RTC/RTCUtils.js] <79/_getUserMedia/</<>: onUserMediaSuccess Logger.js:154:22
2022-08-23T09:48:59.191Z [modules/RTC/JitsiLocalTrack.js] <_setStream>: Setting new MSID: {c293e472-c22a-4a8b-8cb3-38f9c69b7e1a} {263e5f3a-5264-41c9-8018-cff69dae7e92} on LocalTrack[undefined,audio] Logger.js:154:22
2022-08-23T09:48:59.607Z [modules/RTC/RTCUtils.js] : list of media devices has changed:
Array [ MediaDeviceInfo ]
Logger.js:154:22
2022-08-23T09:48:59.608Z [features/base/devices] <5027/</</</<>: Device list updated:
audioInput:
Monitor of Built-in Audio Analog Stereo[4bKiUxVGFMtc4rtt/htwN9FMPk1qBa5MtL/e/zhrEPM=]
audioOutput:

videoInput:
Logger.js:152:50
2022-08-23T09:48:59.633Z [conference.js] <5027/_onDeviceListChanged/<>: Video mute: device list changed Logger.js:152:50
2022-08-23T09:48:59.755Z [features/base/devices] <5027/</</</<>: Device list updated:
audioInput:
Monitor of Built-in Audio Analog Stereo[4bKiUxVGFMtc4rtt/htwN9FMPk1qBa5MtL/e/zhrEPM=]
audioOutput:

videoInput:
Logger.js:152:50
GETwss://vleegert.nano.tudelft.nl:8443/xmpp-websocket?room=test
[HTTP/1.1 502 Bad Gateway 17ms]

2022-08-23T09:48:59.857Z [features/base/devices] <5027/</</</<>: Device list updated:
audioInput:
Monitor of Built-in Audio Analog Stereo[4bKiUxVGFMtc4rtt/htwN9FMPk1qBa5MtL/e/zhrEPM=]
audioOutput:

videoInput:
Logger.js:152:50
Firefox can’t establish a connection to the server at wss://vleegert.nano.tudelft.nl:8443/xmpp-websocket?room=test. strophe.umd.js:5463:30
2022-08-23T09:48:59.940Z [JitsiMeetJS.js] : UnhandledError: Strophe: Websocket error [object Event] Script: null Line: null Column: null StackTrace: 79/sa/ut.Strophe.log@https://vleegert.nano.tudelft.nl:8443/libs/lib-jitsi-meet.min.js?v=6447:2:448804
error@https://vleegert.nano.tudelft.nl:8443/libs/lib-jitsi-meet.min.js?v=6447:2:146409
_onError@https://vleegert.nano.tudelft.nl:8443/libs/lib-jitsi-meet.min.js?v=6447:2:185882
EventHandlerNonNull*_connect@https://vleegert.nano.tudelft.nl:8443/libs/lib-jitsi-meet.min.js?v=6447:2:182778
connect@https://vleegert.nano.tudelft.nl:8443/libs/lib-jitsi-meet.min.js?v=6447:2:152264
_interceptConnectArgs@https://vleegert.nano.tudelft.nl:8443/libs/lib-jitsi-meet.min.js?v=6447:2:193163
connect@https://vleegert.nano.tudelft.nl:8443/libs/lib-jitsi-meet.min.js?v=6447:2:320546
_connect@https://vleegert.nano.tudelft.nl:8443/libs/lib-jitsi-meet.min.js?v=6447:2:456426
connect@https://vleegert.nano.tudelft.nl:8443/libs/lib-jitsi-meet.min.js?v=6447:2:457498
79/Oh.prototype.connect@https://vleegert.nano.tudelft.nl:8443/libs/lib-jitsi-meet.min.js?v=6447:2:728578
Ule@https://vleegert.nano.tudelft.nl:8443/libs/app.bundle.min.js?v=6447:138:711730
5027/Hle/<@https://vleegert.nano.tudelft.nl:8443/libs/app.bundle.min.js?v=6447:138:714756
Hle@https://vleegert.nano.tudelft.nl:8443/libs/app.bundle.min.js?v=6447:138:713967
Vle@https://vleegert.nano.tudelft.nl:8443/libs/app.bundle.min.js?v=6447:138:714959
Pce@https://vleegert.nano.tudelft.nl:8443/libs/app.bundle.min.js?v=6447:138:733356
init@https://vleegert.nano.tudelft.nl:8443/libs/app.bundle.min.js?v=6447:138:739655
async5027/_start/</<@https://vleegert.nano.tudelft.nl:8443/libs/app.bundle.min.js?v=6447:138:665371
promise callback5027/_start/<@https://vleegert.nano.tudelft.nl:8443/libs/app.bundle.min.js?v=6447:138:665346
1618/n/</</<@https://vleegert.nano.tudelft.nl:8443/libs/app.bundle.min.js?v=6447:138:2042063
5027/</</<@https://vleegert.nano.tudelft.nl:8443/libs/app.bundle.min.js?v=6447:138:938798
5027/</</<@https://vleegert.nano.tudelft.nl:8443/libs/app.bundle.min.js?v=6447:138:923333
5027/</</<@https://vleegert.nano.tudelft.nl:8443/libs/app.bundle.min.js?v=6447:138:922764
5027/</</<@https://vleegert.nano.tudelft.nl:8443/libs/app.bundle.min.js?v=6447:138:917406
5027/</</<@https://vleegert.nano.tudelft.nl:8443/libs/app.bundle.min.js?v=6447:138:916770
5027/</</<@https://vleegert.nano.tudelft.nl:8443/libs/app.bundle.min.js?v=6447:138:915802
5027/</</<@https://vleegert.nano.tudelft.nl:8443/libs/app.bundle.min.js?v=6447:138:914444
5027/</</<@https://vleegert.nano.tudelft.nl:8443/libs/app.bundle.min.js?v=6447:138:913583
5027/</</<@https://vleegert.nano.tudelft.nl:8443/libs/app.bundle.min.js?v=6447:138:910856
5027/</</<@https://vleegert.nano.tudelft.nl:8443/libs/app.bundle.min.js?v=6447:138:910779
5027/</</<@https://vleegert.nano.tudelft.nl:8443/libs/app.bundle.min.js?v=6447:138:897172
5027/</</<@https://vleegert.nano.tudelft.nl:8443/libs/app.bundle.min.js?v=6447:138:889057
5027/</</<@https://vleegert.nano.tudelft.nl:8443/libs/app.bundle.min.js?v=6447:138:888857
5027/</</<@https://vleegert.nano.tudelft.nl:8443/libs/app.bundle.min.js?v=6447:138:887857
5027/</</<@https://vleegert.nano.tudelft.nl:8443/libs/app.bundle.min.js?v=6447:138:883828
5027/</</<@https://vleegert.nano.tudelft.nl:8443/libs/app.bundle.min.js?v=6447:138:882491
5027/</</<@https://vleegert.nano.tudelft.nl:8443/libs/app.bundle.min.js?v=6447:138:879506
5027/</</<@https://vleegert.nano.tudelft.nl:8443/libs/app.bundle.min.js?v=6447:138:877889
5027/</</<@https://vleegert.nano.tudelft.nl:8443/libs/app.bundle.min.js?v=6447:138:877037
5027/</</<@https://vleegert.nano.tudelft.nl:8443/libs/app.bundle.min.js?v=6447:138:876707
5027/</</<@https://vleegert.nano.tudelft.nl:8443/libs/app.bundle.min.js?v=6447:138:875697
5027/</</<@https://vleegert.nano.tudelft.nl:8443/libs/app.bundle.min.js?v=6447:138:875289
5027/</</<@https://vleegert.nano.tudelft.nl:8443/libs/app.bundle.min.js?v=6447:138:872216
5027/</</<@https://vleegert.nano.tudelft.nl:8443/libs/app.bundle.min.js?v=6447:138:863642
5027/</</<@https://vleegert.nano.tudelft.nl:8443/libs/app.bundle.min.js?v=6447:138:863294
5027/</</<@https://vleegert.nano.tudelft.nl:8443/libs/app.bundle.min.js?v=6447:138:863010
5027/</</<@https://vleegert.nano.tudelft.nl:8443/libs/app.bundle.min.js?v=6447:138:862970
5027/</</<@https://vleegert.nano.tudelft.nl:8443/libs/app.bundle.min.js?v=6447:138:857403
Logger.js:154:22
2022-08-23T09:48:59.942Z [modules/xmpp/strophe.util.js] <79/sa/ut.Strophe.log>: Strophe: Websocket error [object Event] Logger.js:154:22
2022-08-23T09:48:59.943Z [modules/xmpp/xmpp.js] : (TIME) Strophe connfail[The WebSocket connection could not be established or was disconnected.]: 6521 Logger.js:154:22
2022-08-23T09:48:59.951Z [modules/xmpp/xmpp.js] : (TIME) Strophe disconnected: 6527 Logger.js:154:22
2022-08-23T09:48:59.952Z [modules/statistics/statistics.js] <79/Tn.sendAnalyticsAndLog>: {"type":"operational","action":"connection.failed","attributes":{"error_type":"connection.otherError","error_message":"The WebSocket connection could not be established or was disconnected.","suspend_time":0,"time_since_last_success":null}} Logger.js:154:22
2022-08-23T09:48:59.953Z [connection.js] CONNECTION FAILED: connection.otherError Logger.js:152:50
2022-08-23T09:48:59.968Z [features/overlay] : The conference will be reloaded after 28 seconds. Logger.js:152:50

**Comment by saghul** [comment]
> Firefox can’t establish a connection to the server at wss://vleegert.nano.tudelft.nl:8443/xmpp-websocket?room=test. strophe.umd.js:5463:30

Is the server properly proxying requests there? I suppose you are using a self-signed cert, right? I *think* some browsers will choke on it when trying to use WS.

**Comment by joukj** [comment]
The server has a signed cert, I got from the university. So not self-signed.
The server does not use a proxy, but maybe does internally using docker, but that worked properly with previous versions of Jitsi.

I got the same problem with Firefox and Chromium-freeworld

**Comment by saghul** [comment]
Is the server up and accessible so we can take a look?

**Comment by saghul** [comment]
By accessible I mean the web is reachable.

**Comment by joukj** [comment]
I just started Jitsi on the server.
https://vleegert.nano.tdelft.nl:8443

Please let me know when you are finished, so that I can shut it down again.

**Comment by joukj** [comment]
oops should be
https://vleegert.nano.tudelft.nl:8443

**Comment by joukj** [comment]
had to shut down the server.
please cotact me off-line or by phone (office hours 31-15-2782272

**Comment by saghul** [comment]
Sorry I'm not sure when I'll able to take a look. Is it possible for you to let it run?

**Comment by joukj** [comment]
I upgraded to 7648-4, but th did not help.

It is now running again. But be aware that this is my "test" machine. So it is rebooted often and than probably I forget to start Jitsi again.

**Comment by joukj** [comment]
The configuration file for this server is just the example + generated passwords and the following 2 lines added:

PUBLIC_URL=https://vleegert.nano.tudelft.nl:8443
DOCKER_HOST_ADDRESS=131.180.116.49

**Comment by saghul** [comment]
I could connect and see the error. Can you please share the prosody logs? I suspect it's not linking something about the nonstandard port somehow. This is not something we support well, btw.

Can you try setting this in the env file? `ENABLE_XMPP_WEBSOCKET=0` then recreate the containers and try again.

**Comment by joukj** [comment]
[prosody.log](https://github.com/jitsi/docker-jitsi-meet/files/9452615/prosody.log)

Attached the prosody log.
I added the ENABLE_XMPP_WEBSOCKET=0  and restarted. Soem difference but I still cannot join a meeting.

What do you mean by  non-standard port, since I thought I did everything "standard".

**Comment by saghul** [comment]
> [prosody.log](https://github.com/jitsi/docker-jitsi-meet/files/9452615/prosody.log)
> 
> Attached the prosody log.

Jackpot. The log is full of errors due to a permissions issue. Make sure you start Docker as a regular user and not root. The container needs to be able to read and write into the contents of ~/.jitsi-meet-cfg



> What do you mean by non-standard port, since I thought I did everything "standard".

8443 is not the HTTPS standard port. But never mind, the errors above explain the situation.

**Comment by joukj** [comment]
Strange I run docker-compose always as root for over 2 years now. The /.jitsi-meet-cfg is in the /root folder and owned by root

**Comment by joukj** [comment]
When running docker-compose as a "normal" user, I only see black screen when accessing the serve. I see that some files in .jitsi-meet-c are created by root. Probably because docker runs as a system-service.

I restarted the server again as root and I see something again

**Comment by saghul** [comment]
I have only experienced pain when running as root, so I can't recommend it.

If you run as a user make sure you place the jitsi-meet-cfg directory somewhere in that user's home dir.

**Comment by joukj** [comment]
I created a fresh  jitsi-meet-cfg in my home directy. I saw that i.e. the certs generated by defaultt are owned by root after startup with dovcker-compose (runned as myself)

Is it a problem that docker runs as a system-service. This is the normal way to start the docker service.

**Comment by saghul** [comment]
I am running docker as a user, which is part of the `docker` group. In your case you might need to chmod the config directory to give permissions to everyone then.

**Comment by joukj** [comment]
I found something on running "rootless" docker.. I'm going to try that first. It will take some time.

**Comment by joukj** [comment]
hmm... the moby-package does not allow for rootless and the official docker is not an option because it is normally way behind the new stuff in  Fedora.

Changed the protections of the .jitsi-meet-cfg in my home directory. That solved the problem for now.

**Comment by joukj** [comment]
Works fine now.
However, I have no idea why I get problems with the protections now after 2.5 years of running Jitsi flawlessly

**Comment by slmMuc2fly** [comment]
High
