### ISSUE TITLE
 No socket found

### ISSUE THREAD

**Issue by shuhaib3** [jitsi/docker-jitsi-meet#1402]
Hi @all,

we are getting a error like this in our jvb logs which is hosted in kubernetes.
id=Donny-bEh local_ufrag=eicrb1gcpijif8 ufrag=eicrb1gcpijif8] ConnectivityCheckClient.startCheckForPair#375: Failed to send BINDING-REQUEST(0x1)[attrib.count=6 len=92 tranID=0x03CE293383018564DB725AC1]
java.lang.IllegalArgumentException: No socket found for 10.244.2.66:31000/udp->172.27.208.5:55749/udp
        at org.ice4j.stack.NetAccessManager.sendMessage(NetAccessManager.java:631)
        at org.ice4j.stack.NetAccessManager.sendMessage(NetAccessManager.java:581)
        at org.ice4j.stack.StunClientTransaction.sendRequest0(StunClientTransaction.java:267)
        at org.ice4j.stack.StunClientTransaction.sendRequest(StunClientTransaction.java:245)
        at org.ice4j.stack.StunStack.sendRequest(StunStack.java:680)
        at org.ice4j.ice.ConnectivityCheckClient.startCheckForPair(ConnectivityCheckClient.java:333)
        at org.ice4j.ice.ConnectivityCheckClient.startCheckForPair(ConnectivityCheckClient.java:229)
        at org.ice4j.ice.ConnectivityCheckClient$PaceMaker.run(ConnectivityCheckClient.java:939)
        at org.ice4j.util.PeriodicRunnable.executeRun(PeriodicRunnable.java:206)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
JVB 2022-09-13 00:55:21.283 INFO: [143] [confId=6c55f08ff4386314

**Comment by shuhaib3** [comment]
@saghul @bgrozev is this harmful?

**Comment by saghul** [comment]
I think this is harmless and has been removed in the latest stable.

**Comment by damencho** [comment]
I have seen this kind of errors and when you put a wrong public address in jvb config.

**Comment by shuhaib3** [comment]
the red marked IP's are external IP of jvb node. i hope this is correct
![image](https://user-images.githubusercontent.com/57085593/189985094-0a9fbdc1-88fb-4c83-831d-705154f653af.png)

**Comment by bgrozev** [comment]
> @saghul @bgrozev is this harmful?

It's harmless. What version of jvb are you running? It was supposed to be fixed a while back

**Comment by rishu06** [comment]
Hi 
I am getting socket and connectivity check errors in jvb logs
`MergingDatagramSocket$SocketContainer.runInReaderThread#770: Failed to receive: java.net.SocketException: Socket closed

JVB 2023-09-20 09:34:20.831 INFO: [292270]   MergingDatagramSocket.close#142: Closing.`

`ConnectivityCheckClient.startCheckForPair#350: Could not start connectivity check: No socket found for xxxxxx:10000/udp-> xxxxxx:55571/udp`

JVB version : 7439-2
Is it fixed in latest version or something wrong with network ?
