### ISSUE TITLE
address discovery through stun failed

### ISSUE THREAD

**Issue by zhaoketong** [jitsi/docker-jitsi-meet#1405]
Sorry to bother you again. I have this problem ,address discovery through stun failed ,I hope you can help me
![Uploading 微信图片_20220919092315.jpg…]()

**Comment by saghul** [comment]
The image is broken. Plase paste text instead.

**Comment by zhaoketong** [comment]
docker-jitsi-meet-stable-7648-4-jvb-1      | java.lang.Exception: Address discovery through STUN failed
docker-jitsi-meet-stable-7648-4-jvb-1      |    at org.jitsi.videobridge.health.JvbHealthChecker.check(JvbHealthChecker.kt:39)
docker-jitsi-meet-stable-7648-4-jvb-1      |    at org.jitsi.videobridge.health.JvbHealthChecker.access$check(JvbHealthChecker.kt:25)
docker-jitsi-meet-stable-7648-4-jvb-1      |    at org.jitsi.videobridge.health.JvbHealthChecker$healthChecker$1.invoke(JvbHealthChecker.kt:31)
docker-jitsi-meet-stable-7648-4-jvb-1      |    at org.jitsi.videobridge.health.JvbHealthChecker$healthChecker$1.invoke(JvbHealthChecker.kt:31)
docker-jitsi-meet-stable-7648-4-jvb-1      |    at org.jitsi.health.HealthChecker.run(HealthChecker.kt:144)
docker-jitsi-meet-stable-7648-4-jvb-1      |    at org.jitsi.utils.concurrent.RecurringRunnableExecutor.run(RecurringRunnableExecutor.java:216)
docker-jitsi-meet-stable-7648-4-jvb-1      |    at org.jitsi.utils.concurrent.RecurringRunnableExecutor.runInThread(RecurringRunnableExecutor.java:292)
docker-jitsi-meet-stable-7648-4-jvb-1      |    at org.jitsi.utils.concurrent.RecurringRunnableExecutor$1.run(RecurringRunnableExecutor.java:328)

**Comment by saghul** [comment]
Is your setup behind a restrictive firewall?

**Comment by zhaoketong** [comment]
The firewall is inactive

**Comment by saghul** [comment]
It on your machine, on the network that gives you access to the Internet.
