### ISSUE TITLE
MUC jicofo error

### ISSUE THREAD

**Issue by hxgqh** [jitsi/docker-jitsi-meet#1426]
```log
Jicofo 2022-10-26 21:31:22.943 INFO: [45] [room=jitsixfjevfxyohbncnhctlxdgfpk@muc.meet.jitsi.dev.haomo-tech.com] JitsiMeetConferenceImpl.stop#443: Stopped.
Jicofo 2022-10-26 21:31:22.943 WARNING: [45] FocusManager.conferenceRequest#117: Exception while trying to start the conference
org.jivesoftware.smack.XMPPException$XMPPErrorException: XMPP error reply received from muc.meet.jitsi.dev.haomo-tech.com: XMPPError: not-allowed - cancel [Communication with remote domains is not enabled]
	at org.jivesoftware.smack.XMPPException$XMPPErrorException.ifHasErrorThenThrow(XMPPException.java:171)
	at org.jivesoftware.smack.XMPPException$XMPPErrorException.ifHasErrorThenThrow(XMPPException.java:165)
	at org.jivesoftware.smack.StanzaCollector.nextResultOrThrow(StanzaCollector.java:284)
	at org.jivesoftware.smack.StanzaCollector.nextResultOrThrow(StanzaCollector.java:228)
	at org.jivesoftware.smackx.disco.ServiceDiscoveryManager.discoverInfo(ServiceDiscoveryManager.java:606)
	at org.jivesoftware.smackx.disco.ServiceDiscoveryManager.discoverInfo(ServiceDiscoveryManager.java:578)
	at org.jivesoftware.smackx.muc.MultiUserChatManager.getMucServiceDiscoInfo(MultiUserChatManager.java:425)
	at org.jivesoftware.smackx.muc.MultiUserChat.enter(MultiUserChat.java:358)
	at org.jivesoftware.smackx.muc.MultiUserChat.createOrJoin(MultiUserChat.java:546)
	at org.jivesoftware.smackx.muc.MultiUserChat.createOrJoin(MultiUserChat.java:521)
	at org.jitsi.impl.protocol.xmpp.ChatRoomImpl.joinAs(ChatRoomImpl.java:293)
	at org.jitsi.impl.protocol.xmpp.ChatRoomImpl.join(ChatRoomImpl.java:224)
	at org.jitsi.jicofo.conference.JitsiMeetConferenceImpl.joinTheRoom(JitsiMeetConferenceImpl.java:493)
	at org.jitsi.jicofo.conference.JitsiMeetConferenceImpl.start(JitsiMeetConferenceImpl.java:330)
	at org.jitsi.jicofo.FocusManager.conferenceRequest(FocusManager.kt:114)
	at org.jitsi.jicofo.FocusManager.conferenceRequest$default(FocusManager.kt:95)
	at org.jitsi.jicofo.xmpp.ConferenceIqHandler.handleConferenceIq(ConferenceIqHandler.kt:77)
	at org.jitsi.jicofo.xmpp.ConferenceIqHandler.handleIQRequest$lambda-4(ConferenceIqHandler.kt:165)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by hxgqh** [comment]
Finally solved: add XMPP_MUC_DOMAIN to .env.

**Comment by UnoYakshi** [comment]
It took me almost a full day. Thank you, @hxgqh. Now, users can finally join rooms.
