### ISSUE TITLE
Disconnection is still a issue, it has been for years

### ISSUE THREAD

**Issue by mikkeljohnsen** [jitsi/docker-jitsi-meet#1438]
I have been trying to get Jitsi up an running now several times during the last couple of years. And it is always the same.

Your connection has been disconnected

I have searched and searched, all say it has something to do with PUBLIC_URL, but it has not. When will there be a fix for this, so people can actually try it.

I have just followed this: https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker/

**Comment by saghul** [comment]
Please paste some console logs. Without logs there is no way to help you.

**Comment by mikkeljohnsen** [comment]
I got a little bit further now.

Removing from docker-compose.yml under "prosody" the following. Actually made the other containers start (not just the web).
```
                aliases:
                    - ${XMPP_SERVER:-xmpp.meet.jitsi}
```

But still the same error.

I can see that it says that JVB_AUTH_PASSWORD is not set. But it is. I have run "gen-passwords.sh" and can see it is set.

```
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-set-timezone: executing... 
[cont-init.d] 01-set-timezone: exited 0.
[cont-init.d] 10-config: executing... 
FATAL ERROR: JVB auth password must be set
[cont-init.d] 10-config: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-set-timezone: executing... 
[cont-init.d] 01-set-timezone: exited 0.
[cont-init.d] 10-config: executing... 
FATAL ERROR: JVB auth password must be set
[cont-init.d] 10-config: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-set-timezone: executing... 
[cont-init.d] 01-set-timezone: exited 0.
[cont-init.d] 10-config: executing... 
FATAL ERROR: JVB auth password must be set
[cont-init.d] 10-config: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**Comment by mikkeljohnsen** [comment]
I just downloaded the newest version "docker-jitsi-meet-stable-8044", and it is the same.

It stops after starting "web" container. With:

```
Traceback (most recent call last):
  File "/usr/bin/podman-compose", line 33, in <module>
    sys.exit(load_entry_point('podman-compose==1.0.3', 'console_scripts', 'podman-compose')())
  File "/usr/lib/python3.9/site-packages/podman_compose.py", line 1774, in main
    podman_compose.run()
  File "/usr/lib/python3.9/site-packages/podman_compose.py", line 1023, in run
    cmd(self, args)
  File "/usr/lib/python3.9/site-packages/podman_compose.py", line 1247, in wrapped
    return func(*args, **kw)
  File "/usr/lib/python3.9/site-packages/podman_compose.py", line 1414, in compose_up
    podman_args = container_to_args(compose, cnt, detached=args.detach)
  File "/usr/lib/python3.9/site-packages/podman_compose.py", line 644, in container_to_args
    assert_cnt_nets(compose, cnt)
  File "/usr/lib/python3.9/site-packages/podman_compose.py", line 557, in assert_cnt_nets
    net_desc = nets[net] or {}
KeyError: "meet.jitsi={'aliases': ['xmpp.meet.jitsi']}"
```
but removing
```
                aliases:
                    - ${XMPP_SERVER:-xmpp.meet.jitsi}
```
Makes it start all containers

```
docker.io/jitsi/jvb      stable-8044  8e78ba2062f2  About an hour ago  406 MB
docker.io/jitsi/jicofo   stable-8044  d36fb4892918  About an hour ago  361 MB
docker.io/jitsi/prosody  stable-8044  10273311ceae  About an hour ago  155 MB
docker.io/jitsi/web      stable-8044  49e176fbd822  2 hours ago        272 MB
```
I run on RHEL9 using podman-compose

**Comment by saghul** [comment]
The currently ONLY pinned issue is about how Podman is NOT supported: https://github.com/jitsi/docker-jitsi-meet/issues/201

That issue has currently been open for 2 years.

`podman-compose` is not 100% compatible with `docker-compose` so use it at your own risk, but please do mention it when opening issues, it matters.
