### ISSUE TITLE
Vosk Integration won't work anymore...

### ISSUE THREAD

**Issue by pedroer** [jitsi/docker-jitsi-meet#1473]
Currently i have a working version on docker (tag: **stable-7439-2**) that the VOSK integration works fine.
When testing the new released versions, i noticed that vosk stopped working and still not working (**stable-8252**).

The error i get when trying to run the subtitles with Vosk is the one below (JIGASI logs).

```
2023-02-01 21:58:08.251 WARNING: [171] org.eclipse.jetty.util.TypeUtil.mapToService: Service Provider failed to load
java.util.ServiceConfigurationError: 
	at org.eclipse.jetty.util.ServiceLoaderSpliterator$ServiceProvider.get(ServiceLoaderSpliterator.java:101)
	at org.eclipse.jetty.util.TypeUtil.mapToService(TypeUtil.java:768)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at org.eclipse.jetty.util.ServiceLoaderSpliterator.tryAdvance(ServiceLoaderSpliterator.java:46)
	at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:326)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.eclipse.jetty.websocket.core.WebSocketExtensionRegistry.<init>(WebSocketExtensionRegistry.java:34)
	at org.eclipse.jetty.websocket.core.WebSocketComponents.<init>(WebSocketComponents.java:55)
	at org.eclipse.jetty.websocket.core.WebSocketComponents.<init>(WebSocketComponents.java:49)
	at org.eclipse.jetty.websocket.core.WebSocketComponents.<init>(WebSocketComponents.java:43)
	at org.eclipse.jetty.websocket.client.WebSocketClient.<init>(WebSocketClient.java:67)
	at org.eclipse.jetty.websocket.client.WebSocketClient.<init>(WebSocketClient.java:76)
	at org.jitsi.jigasi.transcription.VoskTranscriptionService.sendSingleRequest(VoskTranscriptionService.java:143)
	at org.jitsi.jigasi.transcription.Participant.lambda$sendRequest$1(Participant.java:697)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.ServiceConfigurationError: org.eclipse.jetty.websocket.core.Extension: Provider org.eclipse.jetty.websocket.core.internal.FragmentExtension could not be instantiated
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:582)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:804)
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:722)
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1395)
	at org.eclipse.jetty.util.ServiceLoaderSpliterator.tryAdvance(ServiceLoaderSpliterator.java:39)
	... 18 more
Caused by: java.lang.NoClassDefFoundError: org/eclipse/jetty/util/StaticException
	at org.eclipse.jetty.websocket.core.internal.FragmentExtension.<init>(FragmentExtension.java:42)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:780)
	... 21 more
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.util.StaticException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 27 more
2023-02-01 21:58:08.255 WARNING: [171] org.eclipse.jetty.util.TypeUtil.mapToService: Service Provider failed to load
java.util.ServiceConfigurationError: 
	at org.eclipse.jetty.util.ServiceLoaderSpliterator$ServiceProvider.get(ServiceLoaderSpliterator.java:101)
	at org.eclipse.jetty.util.TypeUtil.mapToService(TypeUtil.java:768)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at org.eclipse.jetty.util.ServiceLoaderSpliterator.tryAdvance(ServiceLoaderSpliterator.java:46)
	at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:326)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.eclipse.jetty.websocket.core.WebSocketExtensionRegistry.<init>(WebSocketExtensionRegistry.java:34)
	at org.eclipse.jetty.websocket.core.WebSocketComponents.<init>(WebSocketComponents.java:55)
	at org.eclipse.jetty.websocket.core.WebSocketComponents.<init>(WebSocketComponents.java:49)
	at org.eclipse.jetty.websocket.core.WebSocketComponents.<init>(WebSocketComponents.java:43)
	at org.eclipse.jetty.websocket.client.WebSocketClient.<init>(WebSocketClient.java:67)
	at org.eclipse.jetty.websocket.client.WebSocketClient.<init>(WebSocketClient.java:76)
	at org.jitsi.jigasi.transcription.VoskTranscriptionService.sendSingleRequest(VoskTranscriptionService.java:143)
	at org.jitsi.jigasi.transcription.Participant.lambda$sendRequest$1(Participant.java:697)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.ServiceConfigurationError: org.eclipse.jetty.websocket.core.Extension: Provider org.eclipse.jetty.websocket.core.internal.PerMessageDeflateExtension could not be instantiated
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:582)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:804)
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:722)
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1395)
	at org.eclipse.jetty.util.ServiceLoaderSpliterator.tryAdvance(ServiceLoaderSpliterator.java:39)
	... 18 more
Caused by: java.lang.NoClassDefFoundError: org/eclipse/jetty/util/StaticException
	at org.eclipse.jetty.websocket.core.internal.PerMessageDeflateExtension.<init>(PerMessageDeflateExtension.java:67)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:780)
	... 21 more
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.util.StaticException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 27 more

```

Anyone else have this problem or had lucky running VOSK on current new releases?

**Comment by jaakidup** [comment]
Yes, we are having the same problem, 

We had people using vosk for transcriptions, but when we updated to the latest versions of jitsi, we couldn't get vosk to work properly anymore.
