### ISSUE TITLE
Error on Jicofo startup 

### ISSUE THREAD

**Issue by indigo423** [jitsi/docker-jitsi-meet#1505]
When you start up the stack I've got the following error message:

```
jicofo_1   | Jicofo 2023-03-17 13:22:43.107 SEVERE: [1] Main.lambda$main$0#50: An uncaught exception occurred in thread=Thread[main,5,main]
jicofo_1   | java.lang.ExceptionInInitializerError
jicofo_1   | 	at org.jitsi.jicofo.Main.main(Main.java:53)
jicofo_1   | Caused by: com.typesafe.config.ConfigException$Parse: /config/jicofo.conf: 103: unbalanced close brace '}' with no open brace (if you intended '}' to be part of a key or string value, try enclosing the key or value in double quotes)
jicofo_1   | 	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:201)
jicofo_1   | 	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:197)
jicofo_1   | 	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:434)
jicofo_1   | 	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parse(ConfigDocumentParser.java:648)
jicofo_1   | 	at com.typesafe.config.impl.ConfigDocumentParser.parse(ConfigDocumentParser.java:14)
jicofo_1   | 	at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:262)
jicofo_1   | 	at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:250)
jicofo_1   | 	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:180)
jicofo_1   | 	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
jicofo_1   | 	at com.typesafe.config.impl.Parseable.parse(Parseable.java:301)
jicofo_1   | 	at com.typesafe.config.ConfigFactory.parseFile(ConfigFactory.java:793)
jicofo_1   | 	at com.typesafe.config.ConfigFactory.parseApplicationReplacement(ConfigFactory.java:1166)
jicofo_1   | 	at com.typesafe.config.ConfigFactory.parseApplicationReplacement(ConfigFactory.java:1106)
jicofo_1   | 	at org.jitsi.config.JitsiConfig$Companion.loadNewConfig(JitsiConfig.kt:85)
jicofo_1   | 	at org.jitsi.config.JitsiConfig$Companion.access$loadNewConfig(JitsiConfig.kt:32)
jicofo_1   | 	at org.jitsi.config.JitsiConfig.<clinit>(JitsiConfig.kt:38)
jicofo_1   | 	... 1 more
```

It seems like the END of the IF condition in the Jicofo template is in the wrong place

https://github.com/jitsi/docker-jitsi-meet/blob/e5d421331d4ba7c85ab85520a5c85553e90a236a/jicofo/rootfs/defaults/jicofo.conf#L110

**Comment by aaronkvanmeerten** [comment]
Great catch I'll fix that now.

**Comment by aaronkvanmeerten** [comment]
PR: https://github.com/jitsi/docker-jitsi-meet/pull/1506
