### ISSUE TITLE
Jicofo: SEVERE: XmppProvider.doConnect#179: Failed to connect/login: [...] Connection refused

### ISSUE THREAD

**Issue by krassle** [jitsi/docker-jitsi-meet#1543]
Hi, with the latest **stable-8615** Jicofo logs the following _SEVERE_ message. Still everything appears to work fine...
```java
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-set-timezone: executing... 
[cont-init.d] 01-set-timezone: exited 0.
[cont-init.d] 10-config: executing... 
[cont-init.d] 10-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Jicofo 2023-05-02 17:58:52.095 INFO: [1] Main.main#47: Starting Jicofo.
Jicofo 2023-05-02 17:58:52.509 INFO: [1] JitsiConfig.<clinit>#47: Initialized newConfig: merge of /config/jicofo.conf: 1,system properties,reference.conf @ jar:file:/usr/share/jicofo/lib/jicofo-selector-1.0-1027.jar!/reference.conf: 1
Jicofo 2023-05-02 17:58:52.512 INFO: [1] ReadOnlyConfigurationService.reloadConfiguration#40: net.java.sip.communicator.SC_HOME_DIR_LOCATION not set
Jicofo 2023-05-02 17:58:52.514 INFO: [1] JitsiConfig.<clinit>#68: Initialized legacyConfig: sip communicator props (no description provided)
Jicofo 2023-05-02 17:58:52.533 INFO: [1] JitsiConfig$Companion.reloadNewConfig#94: Reloading the Typesafe config source (previously reloaded 0 times).
Jicofo 2023-05-02 17:58:54.262 INFO: [1] JicofoMetricsContainer.addUpdateTask#48: Scheduling metrics update task with interval PT30S.
Jicofo 2023-05-02 17:58:54.332 INFO: [1] JicofoServices.createAuthenticationAuthority#203: Authentication service disabled.
Jicofo 2023-05-02 17:58:54.528 WARNING: [1] [xmpp_connection=client] XmppProviderKt.createXmppConnection#310: Disabling TLS certificate verification!
Jicofo 2023-05-02 17:58:54.790 INFO: [1] XmppServices.<init>#45: No dedicated Service XMPP connection configured, re-using the client XMPP connection.
Jicofo 2023-05-02 17:58:54.826 SEVERE: [13] [xmpp_connection=client] XmppProvider.doConnect#179: Failed to connect/login: The following addresses failed: 'RFC 6120 A/AAAA Endpoint + [xmpp.meet.jitsi:5222] (xmpp.meet.jitsi/172.18.0.5:5222)' failed because: java.net.ConnectException: Connection refused (Connection refused)
org.jivesoftware.smack.SmackException$EndpointConnectionException: The following addresses failed: 'RFC 6120 A/AAAA Endpoint + [xmpp.meet.jitsi:5222] (xmpp.meet.jitsi/172.18.0.5:5222)' failed because: java.net.ConnectException: Connection refused (Connection refused)
	at org.jivesoftware.smack.SmackException$EndpointConnectionException.from(SmackException.java:334)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:664)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:849)
	at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:526)
	at org.jitsi.jicofo.xmpp.XmppProvider.doConnect(XmppProvider.kt:165)
	at org.jitsi.jicofo.xmpp.XmppProvider.start$lambda-1(XmppProvider.kt:125)
	at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:167)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Jicofo 2023-05-02 17:58:54.829 INFO: [1] XmppServices.<init>#75: No Jigasi detector configured.
Jicofo 2023-05-02 17:58:54.831 INFO: [1] AvModerationHandler.componentsChanged#112: No av_moderation component discovered.
Jicofo 2023-05-02 17:58:54.853 INFO: [1] [connection=client] VisitorsManager.updateAddress#56: VisitorsComponentManager is now disabled with address null
Jicofo 2023-05-02 17:58:54.880 INFO: [1] ConferenceIqHandler.componentsChanged#207: No breakout room component discovered.
Jicofo 2023-05-02 17:58:54.941 INFO: [1] BridgeSelector.<init>#57: Using org.jitsi.jicofo.bridge.SingleBridgeSelectionStrategy
Jicofo 2023-05-02 17:58:54.985 INFO: [1] [type=bridge brewery=jvbbrewery] BaseBrewery.<init>#100: Initialized with JID=jvbbrewery@internal-muc.meet.jitsi
Jicofo 2023-05-02 17:58:54.990 INFO: [1] JicofoServices.<init>#110: No Jibri detector configured.
Jicofo 2023-05-02 17:58:54.992 INFO: [1] JicofoServices.<init>#116: No SIP Jibri detector configured.
Jicofo 2023-05-02 17:58:55.117 INFO: [1] JicofoServices.<init>#143: Starting HTTP server with config: host=null, port=8888, tlsPort=8843, isTls=false, keyStorePath=null, sendServerVersion=true, [TLSv1.2, TLSv1.3]=[TLSv1.2, TLSv1.3], tlsCipherSuites=[TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256, TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256, TLS_DHE_RSA_WITH_AES_256_GCM_SHA384, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256].
Jicofo 2023-05-02 17:58:55.499 INFO: [1] org.eclipse.jetty.server.Server.doStart: jetty-11.0.14; built: 2023-02-22T23:41:48.575Z; git: 4601fe8dd805ce75b69c64466c115a162586641b; jvm 11.0.18+10-post-Debian-1deb11u1
Jicofo 2023-05-02 17:58:56.156 WARNING: [1] org.glassfish.jersey.server.wadl.WadlFeature.configure: JAXBContext implementation could not be found. WADL feature is disabled.
Jicofo 2023-05-02 17:58:56.342 WARNING: [1] org.glassfish.jersey.internal.inject.Providers.checkProviderRuntime: A provider org.jitsi.rest.Version registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider org.jitsi.rest.Version will be ignored. 
Jicofo 2023-05-02 17:58:56.344 WARNING: [1] org.glassfish.jersey.internal.inject.Providers.checkProviderRuntime: A provider org.jitsi.rest.prometheus.Prometheus registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider org.jitsi.rest.prometheus.Prometheus will be ignored. 
Jicofo 2023-05-02 17:58:56.344 WARNING: [1] org.glassfish.jersey.internal.inject.Providers.checkProviderRuntime: A provider org.jitsi.jicofo.rest.ConferenceRequest registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider org.jitsi.jicofo.rest.ConferenceRequest will be ignored. 
Jicofo 2023-05-02 17:58:56.754 INFO: [1] org.eclipse.jetty.server.handler.ContextHandler.doStart: Started o.e.j.s.ServletContextHandler@67fa5045{/,null,AVAILABLE}
Jicofo 2023-05-02 17:58:56.769 INFO: [1] org.eclipse.jetty.server.AbstractConnector.doStart: Started ServerConnector@4393593c{HTTP/1.1, (http/1.1)}{0.0.0.0:8888}
Jicofo 2023-05-02 17:58:56.795 INFO: [1] org.eclipse.jetty.server.Server.doStart: Started Server@4cb0a000{STARTING}[11.0.14,sto=0] @4944ms
Jicofo 2023-05-02 17:58:56.795 INFO: [1] JicofoServices.<init>#162: Registering GlobalMetrics periodic updates.
Jicofo 2023-05-02 17:58:59.949 INFO: [13] [xmpp_connection=client] XmppProvider.doConnect#166: Connected, JID=null
Jicofo 2023-05-02 17:59:00.051 INFO: [13] [xmpp_connection=client] XmppProvider.fireRegistrationStateChanged#216: Set replyTimeout=PT15S
Jicofo 2023-05-02 17:59:00.051 INFO: [13] [xmpp_connection=client] XmppProvider$connectionListener$1.authenticated#97: Registered.
Jicofo 2023-05-02 17:59:00.051 INFO: [13] [xmpp_connection=client] XmppProvider$connectionListener$1.authenticated#99: Will discover components for meet.jitsi
Jicofo 2023-05-02 17:59:00.114 WARNING: [30] [xmpp_connection=client] XmppProvider.setComponents#76: Discovered components: [Component(type=av_moderation, address=avmoderation.meet.jitsi), Component(type=breakout_rooms, address=breakout.meet.jitsi), Component(type=conference_duration, address=conferenceduration.meet.jitsi), Component(type=lobbyrooms, address=lobby.meet.jitsi), Component(type=end_conference, address=endconference.meet.jitsi), Component(type=speakerstats, address=speakerstats.meet.jitsi), Component(type=room_metadata, address=metadata.meet.jitsi)]
Jicofo 2023-05-02 17:59:00.123 INFO: [32] AvModerationHandler.componentsChanged#115: Using av_moderation component at avmoderation.meet.jitsi.
Jicofo 2023-05-02 17:59:00.124 INFO: [38] [connection=client] VisitorsManager.updateAddress#56: VisitorsComponentManager is now disabled with address null
Jicofo 2023-05-02 17:59:00.129 INFO: [39] ConferenceIqHandler.componentsChanged#210: Using breakout room component at breakout.meet.jitsi.
Jicofo 2023-05-02 17:59:00.166 INFO: [31] [type=bridge brewery=jvbbrewery] BaseBrewery.start#176: Joined the room.
Jicofo 2023-05-02 17:59:00.470 INFO: [18] [type=bridge brewery=jvbbrewery] BaseBrewery.addInstance#346: Added brewery instance: jvbbrewery@internal-muc.meet.jitsi/0c89ae3bf3fb
Jicofo 2023-05-02 17:59:00.482 INFO: [18] BridgeSelector.addJvbAddress#96: Added new videobridge: Bridge[jid=jvbbrewery@internal-muc.meet.jitsi/0c89ae3bf3fb, version=2.3.19-gb286dc0c, relayId=null, region=null, stress=0.00]
Jicofo 2023-05-02 17:59:00.485 INFO: [41] JvbDoctor.bridgeAdded#131: Scheduled health-check task for: Bridge[jid=jvbbrewery@internal-muc.meet.jitsi/0c89ae3bf3fb, version=2.3.19-gb286dc0c, relayId=null, region=null, stress=0.00]
```

**Comment by saghul** [comment]
Looks like a container startup thing. Jicofo might have started faster than Prosody and thus it fails when it tries to connect. The software is ready to handle this and will re-connect as you can see towards the bottom of the log.
