### ISSUE TITLE
Internal auth will not connect

### ISSUE THREAD

**Issue by jcalfee** [jitsi/docker-jitsi-meet#1573]
I can not connect enough to get to the login screen.  The 1st thing that comes up:

![image](https://github.com/jitsi/docker-jitsi-meet/assets/204121/c322070a-c639-4993-a9f1-a53eaac915fb)

The only error I see is early on:
```bash
jvb_1      | java.lang.IllegalArgumentException: hostname can't be null
jvb_1      | 	at java.base/java.net.InetSocketAddress.checkHost(InetSocketAddress.java:149)
jvb_1      | 	at java.base/java.net.InetSocketAddress.<init>(InetSocketAddress.java:216)
jvb_1      | 	at org.ice4j.TransportAddress.<init>(TransportAddress.java:61)
jvb_1      | 	at org.ice4j.ice.harvest.AwsCandidateHarvester.obtainEC2Addresses(AwsCandidateHarvester.java:112)
jvb_1      | 	at org.ice4j.ice.harvest.AwsCandidateHarvester.getFace(AwsCandidateHarvester.java:153)
jvb_1      | 	at org.ice4j.ice.harvest.MappingCandidateHarvesters.maybeAdd(MappingCandidateHarvesters.java:189)
jvb_1      | 	at org.ice4j.ice.harvest.MappingCandidateHarvesters.prune(MappingCandidateHarvesters.java:173)
jvb_1      | 	at org.ice4j.ice.harvest.MappingCandidateHarvesters.initialize(MappingCandidateHarvesters.java:149)
jvb_1      | 	at org.jitsi.videobridge.MainKt$startIce4j$1.invoke(Main.kt:211)
jvb_1      | 	at org.jitsi.videobridge.MainKt$startIce4j$1.invoke(Main.kt:210)
jvb_1      | 	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
```
I'm not trying to send anything to Amazon.  

The only config changes are:
```bash
# Enable authentication
ENABLE_AUTH=1

# Enable guest access
ENABLE_GUESTS=1

# Select authentication type: internal, jwt, ldap or matrix
AUTH_TYPE=internal
```
docker-jitsi-meet-stable-8719

Probably not my network, I have another jitsi server using a different image that is working.

**Comment by saghul** [comment]
Are you running on AWS? Any jicofo logs?
