### ISSUE TITLE
Jigasi Incoming call not received

### ISSUE THREAD

**Issue by hiteshsaini33** [jitsi/docker-jitsi-meet#1580]
I have integrated voximplant with jigasi. I am able to do outbound calling from jitsi to any mobile no. but incoming calls are not working. Here are the logs for incoming calls in jigasi:-

2023-07-14 12:28:17.399 INFO: [82] SipGateway$SipCallListener.incomingCallReceived#216: [ctx=16893178973961300318303] Incoming call received...
2023-07-14 12:28:17.407 INFO: [84] SipGatewaySession$WaitForJvbRoomNameThread.run#1587: [ctx=16893178973961300318303] Wait thread cancelled
2023-07-14 12:28:17.413 INFO: [82] JvbConference.start#454: [ctx=16893178973961300318303] Starting JVB conference room: voximplant@conference.vc.test.co.in?cid=1788389
2023-07-14 12:28:17.415 INFO: [82] JvbConference.setXmppProvider#590: [ctx=16893178973961300318303] Using ProtocolProviderServiceJabberImpl(Jabber:6465c393@vc.test.co.in?cid=1788389/6465c393)
2023-07-14 12:28:17.418 SEVERE: [17] net.java.sip.communicator.impl.packetlogging.PacketLoggingServiceImpl$SaverThread.run: Error writing packet to file
java.lang.SecurityException: Insufficient rights to access this file in current user's home directory: /config/log/jitsi0.pcap
        at org.jitsi.impl.fileaccess.FileAccessServiceImpl.getPrivatePersistentFile(FileAccessServiceImpl.java:171)
        at net.java.sip.communicator.impl.packetlogging.PacketLoggingServiceImpl.getFileNames(PacketLoggingServiceImpl.java:194)
        at net.java.sip.communicator.impl.packetlogging.PacketLoggingServiceImpl.savePacket(PacketLoggingServiceImpl.java:579)
        at net.java.sip.communicator.impl.packetlogging.PacketLoggingServiceImpl$SaverThread.run(PacketLoggingServiceImpl.java:833)
2023-07-14 12:28:17.419 SEVERE: [17] net.java.sip.communicator.impl.packetlogging.PacketLoggingServiceImpl$SaverThread.run: Error writing packet to file
java.lang.SecurityException: Insufficient rights to access this file in current user's home directory: /config/log/jitsi0.pcap
        at org.jitsi.impl.fileaccess.FileAccessServiceImpl.getPrivatePersistentFile(FileAccessServiceImpl.java:171)
        at net.java.sip.communicator.impl.packetlogging.PacketLoggingServiceImpl.getFileNames(PacketLoggingServiceImpl.java:194)
        at net.java.sip.communicator.impl.packetlogging.PacketLoggingServiceImpl.savePacket(PacketLoggingServiceImpl.java:579)
        at net.java.sip.communicator.impl.packetlogging.PacketLoggingServiceImpl$SaverThread.run(PacketLoggingServiceImpl.java:833)
2023-07-14 12:28:17.424 SEVERE: [87] net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.connectAndLogin: Failed to connect to XMPP service for:ProtocolProviderServiceJabberImpl(Jabber:6465c393@vc.test.co.in?cid=1788389/6465c393)
org.jivesoftware.smack.XMPPException$StreamErrorException: host-unknown You can read more about the meaning of this stream error at http://xmpp.org/rfcs/rfc6120.html#streams-error-conditions
<stream:error><host-unknown xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text>This server does not serve vc.test.co.in?cid=1788389</text></stream:error>
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:984)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$700(XMPPTCPConnection.java:916)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:939)
        at java.base/java.lang.Thread.run(Thread.java:829)
2023-07-14 12:28:17.427 WARNING: [93] org.jivesoftware.smack.AbstractXMPPConnection.callConnectionClosedOnErrorListener: Connection XMPPTCPConnection[not-authenticated] (1) closed with error
org.jivesoftware.smack.XMPPException$StreamErrorException: host-unknown You can read more about the meaning of this stream error at http://xmpp.org/rfcs/rfc6120.html#streams-error-conditions
<stream:error><host-unknown xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text>This server does not serve vc.test.co.in?cid=1788389</text></stream:error>
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:984)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$700(XMPPTCPConnection.java:916)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:939)
        at java.base/java.lang.Thread.run(Thread.java:829)
2023-07-14 12:28:17.428 SEVERE: [87] JvbConference.registrationStateChanged#656: [ctx=16893178973961300318303] XMPP Connection failed. RegistrationStateChangeEvent[ oldState=Registering; newState=RegistrationState=Connection Failed; userRequest=false; reasonCode=6; reason=host-unknown You can read more about the meaning of this stream error at http://xmpp.org/rfcs/rfc6120.html#streams-error-conditions
<stream:error><host-unknown xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text>This server does not serve vc.test.co.in?cid=1788389</text></stream:error>]
2023-07-14 12:28:19.641 INFO: [96] net.java.sip.communicator.impl.protocol.sip.SipLogger.logInfo: Info from the JAIN-SIP stack: Setting SIPMessage peerPacketSource to: /18.140.111.54:5060
2023-07-14 12:28:32.641 INFO: [97] net.java.sip.communicator.impl.protocol.sip.SipLogger.logInfo: Info from the JAIN-SIP stack: Setting SIPMessage peerPacketSource to: /18.140.111.54:5060
2023-07-14 12:28:32.653 INFO: [97] SipGatewaySession$SipCallStateListener.handleCallState#1460: [ctx=16893178973961300318303] SIP call ended: CallPeerChangeEvent: type=CallPeerStatusChange oldV=net.java.sip.communicator.service.protocol.CallPeerState:Incoming Call newV=net.java.sip.communicator.service.protocol.CallPeerState:Disconnected for peer=919664022987 (+919664022987) <919664022987@jigasi-test.testprivate.n2.voximplant.com>;status=Disconnected reason=null reasonCode=487
2023-07-14 12:28:32.655 INFO: [97] SipGatewaySession.sipCallEnded#698: [ctx=16893178973961300318303] Sip call ended: Call: id=16893178973631940983454 peers=0
2023-07-14 12:28:32.656 INFO: [97] JvbConference.stop#550: [ctx=16893178973961300318303] Removing account Jabber:6465c393@vc.test.co.in?cid=1788389/6465c393
2023-07-14 12:28:32.656 INFO: [97] net.java.sip.communicator.impl.protocol.jabber.OperationSetBasicTelephonyJabberImpl.registrationStateChanged: Jingle : OFF 
2023-07-14 12:28:32.657 SEVERE: [97] AbstractGateway.notifyCallEnded#147: [ctx=16893178973961300318303] Call resource not exists for session.
2023-07-14 12:28:32.657 INFO: [97] SipGatewaySession$CallPeerListener.peerStateChanged#1521: null SIP peer state: Disconnected
2023-07-14 12:28:32.702 INFO: [98] net.java.sip.communicator.impl.protocol.sip.SipLogger.logInfo: Info from the JAIN-SIP stack: Setting SIPMessage peerPacketSource to: /18.140.111.54:5060
2023-07-14 12:28:34.649 INFO: [99] net.java.sip.communicator.impl.protocol.sip.SipLogger.logInfo: Info from the JAIN-SIP stack: Setting SIPMessage peerPacketSource to: /18.140.111.54:5060
2023-07-14 12:28:59.649 INFO: [100] net.java.sip.communicator.impl.protocol.sip.SipLogger.logInfo: Info from the JAIN-SIP stack: Setting SIPMessage peerPacketSource to: /18.140.111.54:5060
2023-07-14 12:29:24.650 INFO: [101] net.java.sip.communicator.impl.protocol.sip.SipLogger.logInfo: Info from the JAIN-SIP stack: Setting SIPMessage peerPacketSource to: /18.140.111.54:5060
2023-07-14 12:29:49.650 INFO: [102] net.java.sip.communicator.impl.protocol.sip.SipLogger.logInfo: Info from the JAIN-SIP stack: Setting SIPMessage peerPacketSource to: /18.140.111.54:5060

Pls help me regarding this.

**Comment by damencho** [comment]
The room jid you are sending in the sip header needs to be like roomname@muc.meet.jitsi

**Comment by hiteshsaini33** [comment]
Still same after changing room jid

2023-07-14 18:53:03.433 INFO: [75] SipGateway$SipCallListener.incomingCallReceived#216: [ctx=16893409834311552568773] Incoming call received...
2023-07-14 18:53:03.445 INFO: [77] SipGatewaySession$WaitForJvbRoomNameThread.run#1587: [ctx=16893409834311552568773] Wait thread cancelled
2023-07-14 18:53:03.451 INFO: [75] JvbConference.start#454: [ctx=16893409834311552568773] Starting JVB conference room: voximplant@muc.vc.test.co.in?cid=32153368
2023-07-14 18:53:03.454 INFO: [75] JvbConference.setXmppProvider#590: [ctx=16893409834311552568773] Using ProtocolProviderServiceJabberImpl(Jabber:659fa8f7@vc.test.co.in?cid=32153368/659fa8f7)
2023-07-14 18:53:03.457 SEVERE: [17] net.java.sip.communicator.impl.packetlogging.PacketLoggingServiceImpl$SaverThread.run: Error writing packet to file
java.lang.SecurityException: Insufficient rights to access this file in current user's home directory: /config/log/jitsi0.pcap
        at org.jitsi.impl.fileaccess.FileAccessServiceImpl.getPrivatePersistentFile(FileAccessServiceImpl.java:171)
        at net.java.sip.communicator.impl.packetlogging.PacketLoggingServiceImpl.getFileNames(PacketLoggingServiceImpl.java:194)
        at net.java.sip.communicator.impl.packetlogging.PacketLoggingServiceImpl.savePacket(PacketLoggingServiceImpl.java:579)
        at net.java.sip.communicator.impl.packetlogging.PacketLoggingServiceImpl$SaverThread.run(PacketLoggingServiceImpl.java:833)
2023-07-14 18:53:03.459 SEVERE: [17] net.java.sip.communicator.impl.packetlogging.PacketLoggingServiceImpl$SaverThread.run: Error writing packet to file
java.lang.SecurityException: Insufficient rights to access this file in current user's home directory: /config/log/jitsi0.pcap
        at org.jitsi.impl.fileaccess.FileAccessServiceImpl.getPrivatePersistentFile(FileAccessServiceImpl.java:171)
        at net.java.sip.communicator.impl.packetlogging.PacketLoggingServiceImpl.getFileNames(PacketLoggingServiceImpl.java:194)
        at net.java.sip.communicator.impl.packetlogging.PacketLoggingServiceImpl.savePacket(PacketLoggingServiceImpl.java:579)
        at net.java.sip.communicator.impl.packetlogging.PacketLoggingServiceImpl$SaverThread.run(PacketLoggingServiceImpl.java:833)
2023-07-14 18:53:03.464 SEVERE: [80] net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.connectAndLogin: Failed to connect to XMPP service for:ProtocolProviderServiceJabberImpl(Jabber:659fa8f7@vc.test.co.in?cid=32153368/659fa8f7)
org.jivesoftware.smack.XMPPException$StreamErrorException: host-unknown You can read more about the meaning of this stream error at http://xmpp.org/rfcs/rfc6120.html#streams-error-conditions
<stream:error><host-unknown xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text>This server does not serve vc.test.co.in?cid=32153368</text></stream:error>
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:984)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$700(XMPPTCPConnection.java:916)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:939)
        at java.base/java.lang.Thread.run(Thread.java:829)
2023-07-14 18:53:03.464 WARNING: [86] org.jivesoftware.smack.AbstractXMPPConnection.callConnectionClosedOnErrorListener: Connection XMPPTCPConnection[not-authenticated] (1) closed with error
org.jivesoftware.smack.XMPPException$StreamErrorException: host-unknown You can read more about the meaning of this stream error at http://xmpp.org/rfcs/rfc6120.html#streams-error-conditions
<stream:error><host-unknown xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text>This server does not serve vc.test.co.in?cid=32153368</text></stream:error>
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:984)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$700(XMPPTCPConnection.java:916)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:939)
        at java.base/java.lang.Thread.run(Thread.java:829)
2023-07-14 18:53:03.466 SEVERE: [80] JvbConference.registrationStateChanged#656: [ctx=16893409834311552568773] XMPP Connection failed. RegistrationStateChangeEvent[ oldState=Registering; newState=RegistrationState=Connection Failed; userRequest=false; reasonCode=6; reason=host-unknown You can read more about the meaning of this stream error at http://xmpp.org/rfcs/rfc6120.html#streams-error-conditions
<stream:error><host-unknown xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text>This server does not serve vc.test.co.in?cid=32153368</text></stream:error>]

**Comment by damencho** [comment]
> room: [voximplant@muc.vc.test.co.in](mailto:voximplant@muc.vc.test.co.in)?

Still bot the right one. What are all the custom the headers you are sending?
