### ISSUE TITLE
Jicofo error when adding room

### ISSUE THREAD

**Issue by yand9807** [jitsi/docker-jitsi-meet#1684]
this is my jicofo log.
It looks like the conference.domain is invalid. The conference.domain here should be an internal address value, right? Where should I configure it?
```
Jicofo 2023-12-28 09:05:08.642 INFO: [85] ConferenceIqHandler.handleConferenceIq#86: Conference request for room suburbanlabsdategrimly@conference.smp.someray.com, from zmcr289vkd5qmmrzqatst03-@smp.someray.com/8DyVpXgea1jv
Jicofo 2023-12-28 09:05:08.643 INFO: [85] [room=suburbanlabsdategrimly@conference.smp.someray.com] JitsiMeetConferenceImpl.<init>#293: Created new conference.
Jicofo 2023-12-28 09:05:08.643 INFO: [85] [room=suburbanlabsdategrimly@conference.smp.someray.com] JitsiMeetConferenceImpl.joinTheRoom#484: Joining suburbanlabsdategrimly@conference.smp.someray.com
Jicofo 2023-12-28 09:05:08.644 INFO: [85] [room=suburbanlabsdategrimly@conference.smp.someray.com] JitsiMeetConferenceImpl.stop#461: Stopped.
Jicofo 2023-12-28 09:05:08.644 WARNING: [85] FocusManager.conferenceRequest#113: Exception while trying to start the conference
org.jivesoftware.smack.XMPPException$XMPPErrorException: XMPP error reply received from conference.smp.someray.com: XMPPError: not-allowed - cancel [Communication with remote domains is not enabled]
	at org.jivesoftware.smack.XMPPException$XMPPErrorException.ifHasErrorThenThrow(XMPPException.java:171)
	at org.jivesoftware.smack.XMPPException$XMPPErrorException.ifHasErrorThenThrow(XMPPException.java:165)
	at org.jivesoftware.smack.StanzaCollector.nextResultOrThrow(StanzaCollector.java:284)
	at org.jivesoftware.smack.StanzaCollector.nextResultOrThrow(StanzaCollector.java:228)
	at org.jivesoftware.smackx.disco.ServiceDiscoveryManager.discoverInfo(ServiceDiscoveryManager.java:606)
	at org.jivesoftware.smackx.disco.ServiceDiscoveryManager.discoverInfo(ServiceDiscoveryManager.java:578)
	at org.jivesoftware.smackx.muc.MultiUserChatManager.getMucServiceDiscoInfo(MultiUserChatManager.java:425)
	at org.jivesoftware.smackx.muc.MultiUserChat.enter(MultiUserChat.java:358)
	at org.jivesoftware.smackx.muc.MultiUserChat.createOrJoin(MultiUserChat.java:546)
	at org.jivesoftware.smackx.muc.MultiUserChat.createOrJoin(MultiUserChat.java:521)
	at org.jitsi.jicofo.xmpp.muc.ChatRoomImpl.joinAs(ChatRoomImpl.kt:255)
	at org.jitsi.jicofo.xmpp.muc.ChatRoomImpl.join(ChatRoomImpl.kt:221)
	at org.jitsi.jicofo.conference.JitsiMeetConferenceImpl.joinTheRoom(JitsiMeetConferenceImpl.java:499)
	at org.jitsi.jicofo.conference.JitsiMeetConferenceImpl.start(JitsiMeetConferenceImpl.java:358)
	at org.jitsi.jicofo.FocusManager.conferenceRequest(FocusManager.kt:110)
	at org.jitsi.jicofo.FocusManager.conferenceRequest$default(FocusManager.kt:91)
	at org.jitsi.jicofo.xmpp.ConferenceIqHandler.handleConferenceIq(ConferenceIqHandler.kt:119)
	at org.jitsi.jicofo.xmpp.ConferenceIqHandler.handleIQRequest$lambda$8(ConferenceIqHandler.kt:192)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Jicofo 2023-12-28 09:05:08.645 SEVERE: [85] Main.lambda$main$0#50: An uncaught exception occurred in thread=Thread[Jicofo Global IO Poolpool-1-thread-48,5,main]
org.jivesoftware.smack.XMPPException$XMPPErrorException: XMPP error reply received from conference.smp.someray.com: XMPPError: not-allowed - cancel [Communication with remote domains is not enabled]
	at org.jivesoftware.smack.XMPPException$XMPPErrorException.ifHasErrorThenThrow(XMPPException.java:171)
	at org.jivesoftware.smack.XMPPException$XMPPErrorException.ifHasErrorThenThrow(XMPPException.java:165)
	at org.jivesoftware.smack.StanzaCollector.nextResultOrThrow(StanzaCollector.java:284)
	at org.jivesoftware.smack.StanzaCollector.nextResultOrThrow(StanzaCollector.java:228)
	at org.jivesoftware.smackx.disco.ServiceDiscoveryManager.discoverInfo(ServiceDiscoveryManager.java:606)
	at org.jivesoftware.smackx.disco.ServiceDiscoveryManager.discoverInfo(ServiceDiscoveryManager.java:578)
	at org.jivesoftware.smackx.muc.MultiUserChatManager.getMucServiceDiscoInfo(MultiUserChatManager.java:425)
	at org.jivesoftware.smackx.muc.MultiUserChat.enter(MultiUserChat.java:358)
	at org.jivesoftware.smackx.muc.MultiUserChat.createOrJoin(MultiUserChat.java:546)
	at org.jivesoftware.smackx.muc.MultiUserChat.createOrJoin(MultiUserChat.java:521)
	at org.jitsi.jicofo.xmpp.muc.ChatRoomImpl.joinAs(ChatRoomImpl.kt:255)
	at org.jitsi.jicofo.xmpp.muc.ChatRoomImpl.join(ChatRoomImpl.kt:221)
	at org.jitsi.jicofo.conference.JitsiMeetConferenceImpl.joinTheRoom(JitsiMeetConferenceImpl.java:499)
	at org.jitsi.jicofo.conference.JitsiMeetConferenceImpl.start(JitsiMeetConferenceImpl.java:358)
	at org.jitsi.jicofo.FocusManager.conferenceRequest(FocusManager.kt:110)
	at org.jitsi.jicofo.FocusManager.conferenceRequest$default(FocusManager.kt:91)
	at org.jitsi.jicofo.xmpp.ConferenceIqHandler.handleConferenceIq(ConferenceIqHandler.kt:119)
	at org.jitsi.jicofo.xmpp.ConferenceIqHandler.handleIQRequest$lambda$8(ConferenceIqHandler.kt:192)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Jicofo 2023-12-28 09:05:23.643 INFO: [13] [room=suburbanlabsdategrimly@conference.smp.someray.com] JitsiMeetConferenceImpl.lambda$new$1#285: Expiring due to initial timeout.

```

**Comment by yand9807** [comment]
I have identified the problem.
In the configuration of Prosody, muc. domain is used, but in the config.js of the web project I downloaded, the default address configuration for muc is conference.domain. I changed the muc address in config.js to muc. domain and everything was fine.
