### ISSUE TITLE
gen-passwords.sh doesn't set JIGASI_SIP_PASSWORD, jigasi container starts with an empty configuration

### ISSUE THREAD

**Issue by carneallabrace** [jitsi/docker-jitsi-meet#1758]
docker-jitsi-meet version: `stable-9258`
command used: `docker compose -f docker-compose.yml -f jigasi.yml up`

```
root@linux:~/docker-jitsi-meet-stable-9258# docker logs -f docker-jitsi-meet-stable-9258-jigasi-1
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-set-timezone: executing... 
[cont-init.d] 01-set-timezone: exited 0.
[cont-init.d] 10-config: executing... 
panic: render template error: template: /defaults/sip-communicator.properties:48:88: executing "/defaults/sip-communicator.properties" at <b64enc>: invalid value; expected string

goroutine 1 [running]:
main.templateExecute(0xc00009e580?, {0x7ffe55620e82, 0x25})
	/Users/runner/work/tpl/tpl/main.go:47 +0x1b5
main.main()
	/Users/runner/work/tpl/tpl/main.go:68 +0x226
[cont-init.d] 10-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

```
root@linux:~/docker-jitsi-meet-stable-9258# docker exec -it docker-jitsi-meet-stable-9258-jigasi-1 nl -ba /defaults/sip-communicator.properties | grep " 48"
    48	net.java.sip.communicator.impl.protocol.sip.acc1.PASSWORD={{ .Env.JIGASI_SIP_PASSWORD | b64enc }}
root@linux:~/docker-jitsi-meet-stable-9258# 
```

```
root@linux:~/docker-jitsi-meet-stable-9258# docker exec -it docker-jitsi-meet-stable-9258-jigasi-1 wc -l /config/sip-communicator.properties 
0 /config/sip-communicator.properties
root@linux:~/docker-jitsi-meet-stable-9258# 
```

**Comment by saghul** [comment]
How are you running Jigasi? Is it for transcribing?

**Comment by saghul** [comment]
The SIP password does not need to be generated. It needs to match the configuration of a SIP server.

Now, if you are using jigasi just for transcribing, I guess we can disable that. Made https://github.com/jitsi/docker-jitsi-meet/pull/1760 as a potential fix.

**Comment by tuider** [comment]
Yes, it is only used for transcribing. Thank you.
