### ISSUE TITLE
Transcriber pcap issues with vosk

### ISSUE THREAD

**Issue by bmagistro** [jitsi/docker-jitsi-meet#1954]
This may be better directed at https://github.com/jitsi/jigasi directly.  Recently configured transcription and while troubleshooting some pebkac, I noticed errors in the log related to pcap but also see in the config that packet logging should be disabled.  Part of this is making sure that we have things configured correctly and will not experience issues down the road.

OS: Alma 9 (selinux enabled)
Docker: 26.1.3
Jitsi: stabe-9779

The compose file is the same as what is provided in the repo, with `WHITEBOARD_ENABELED` added for web.  The Jibri compose file is the same as what is provided in the repo.  The transcriber compose file is based on the repo and had the following lines added for vosk.
```
    vosk:
        image: alphacep/kaldi-en:latest
        restart: ${RESTART_POLICY:-unless-stopped}
        expose:
                - 2700
        networks:
            meet.jitsi:
```

On the env/config side, the following has been added
```
#
# Metrics
#
COLIBRI_REST_ENABLED=true

#
# Recording
#
ENABLE_RECORDING=1
JIBRI_RECORDER_USER=recorder
JIBRI_RECORDING_DIR=/config/recordings
JIBRI_FINALIZE_RECORDING_SCRIPT_PATH=/config/finalize.sh
JIBRI_XMPP_USER=jibri
JIBRI_STRIP_DOMAIN_JID=muc
JIBRI_BREWERY_MUC=jibribrewery
JIBRI_PENDING_TIMEOUT=90
XMPP_RECORDER_DOMAIN=recorder.meet.jitsi
CHROMIUM_FLAGS="--use-fake-ui-for-media-stream,--start-maximized,--ignore-certificate-errors,--no-sandbox,--kiosk,--disable-infobars,--autoplay-policy=no-user-gesture-required"
JIBRI_RECORDING_RESOLUTION=1280x720

#
# Advanced Configuration
#
JVB_DISABLE_STUN=true

XMPP_MUC_MODULES="muc_allowners"

# disable the end for all
ENABLE_END_CONFERENCE=false

# enable cc/transcriptions
ENABLE_TRANSCRIPTIONS=true
JIGASI_TRANSCRIBER_ADVERTISE_URL=true
JIGASI_TRANSCRIBER_CUSTOM_SERVICE=org.jitsi.jigasi.transcription.VoskTranscriptionService
JIGASI_TRANSCRIBER_ENABLE_SAVING=true
JIGASI_TRANSCRIBER_SEND_TXT=false
JIGASI_TRANSCRIBER_VOSK_URL=ws://vosk:2700
```

Error from log
```
2024-10-25 14:57:16.821 SEVERE: [16] net.java.sip.communicator.impl.packetlogging.PacketLoggingServiceImpl$SaverThread.run: Error writing packet to file
java.lang.SecurityException: Insufficient rights to access this file in current user's home directory: /config/log/jitsi0.pcap
	at org.jitsi.impl.fileaccess.FileAccessServiceImpl.getPrivatePersistentFile(FileAccessServiceImpl.java:171)
	at net.java.sip.communicator.impl.packetlogging.PacketLoggingServiceImpl.getFileNames(PacketLoggingServiceImpl.java:194)
	at net.java.sip.communicator.impl.packetlogging.PacketLoggingServiceImpl.savePacket(PacketLoggingServiceImpl.java:579)
	at net.java.sip.communicator.impl.packetlogging.PacketLoggingServiceImpl$SaverThread.run(PacketLoggingServiceImpl.java:833)
2024-10-25 14:57:16.822 SEVERE: [16] net.java.sip.communicator.impl.packetlogging.PacketLoggingServiceImpl$SaverThread.run: Error writing packet to file
java.lang.SecurityException: Insufficient rights to access this file in current user's home directory: /config/log/jitsi0.pcap
	at org.jitsi.impl.fileaccess.FileAccessServiceImpl.getPrivatePersistentFile(FileAccessServiceImpl.java:171)
	at net.java.sip.communicator.impl.packetlogging.PacketLoggingServiceImpl.getFileNames(PacketLoggingServiceImpl.java:194)
	at net.java.sip.communicator.impl.packetlogging.PacketLoggingServiceImpl.savePacket(PacketLoggingServiceImpl.java:579)
	at net.java.sip.communicator.impl.packetlogging.PacketLoggingServiceImpl$SaverThread.run(PacketLoggingServiceImpl.java:833)
```

pcap disbabled?
```
[bmagistro@meet-0004.test ~]$ cat /etc/jitsi/transcriber/sip-communicator.properties | grep -i packet
# Disables packet logging
net.java.sip.communicator.packetlogging.PACKET_LOGGING_ENABLED=false
```

**Comment by damencho** [comment]
Will be fixed after we update jigasi with: https://github.com/jitsi/jitsi/commit/3eeeb0c7ef7693862f47d30bf533f7c52206046c
