### ISSUE TITLE
JIgasi - Could not initialize class org.jitsi.webrtcvadwrapper.WebRTCVad

### ISSUE THREAD

**Issue by Yerachmiel-Wand** [jitsi/docker-jitsi-meet#1970]
I'm using the docker-compose with jigasi for recording. 

Jigasi image: `jitsi/jigasi:stable-9823`

.env:
```
ENABLE_TRANSCRIPTIONS=true
JIGASI_TRANSCRIBER_ENABLE_SAVING=true
JIGASI_TRANSCRIBER_FILTER_SILENCE=true
JIGASI_TRANSCRIBER_RECORD_AUDIO=true
# google confs ...
```

Here are the logs starting when I click the turn on subtitles in the client.

```

2024-11-28 16:27:56.069 INFO: [39] CallControl.handleDialIq#201: [ctx=1732811275723448660979] Got dial request fromnumber -> jitsi_meet_transcribe room: stiffwestsschedulecalmly@muc.meet.jitsi
2024-11-28 16:27:56.199 INFO: [39] TranscriptionGateway.getCustomTranscriptionServiceClass#173: [ctx=1732811275723448660979] Transcriber class retrieved from config: null
2024-11-28 16:27:56.254 INFO: [39] JvbConference.start#589: [ctx=1732811275723448660979] Starting JVB conference room: stiffwestsschedulecalmly@muc.meet.jitsi
2024-11-28 16:27:56.621 INFO: [39] JvbConference.setXmppProvider#734: [ctx=1732811275723448660979] Using ProtocolProviderServiceJabberImpl(Jabber:transcriber@hidden.meet.jitsi/2919511c)
2024-11-28 16:27:57.210 INFO: [102] net.java.sip.communicator.impl.protocol.jabber.OperationSetBasicTelephonyJabberImpl.registrationStateChanged: Jingle : ON
2024-11-28 16:27:57.216 INFO: [65] JvbConference.registrationStateChangedInternal#795: [ctx=1732811275723448660979] Registering XMPP.
2024-11-28 16:27:57.303 INFO: [102] net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl$JabberConnectionListener.authenticated: Authenticated: false
2024-11-28 16:27:57.317 INFO: [65] JvbConference.discoverComponentAddresses#859: [ctx=1732811275723448660979] Disco-info took 13ms.
2024-11-28 16:27:57.319 INFO: [65] JvbConference.joinConferenceRoom#961: [ctx=1732811275723448660979] Joining JVB conference room: stiffwestsschedulecalmly@muc.meet.jitsi
2024-11-28 16:27:57.442 INFO: [112] net.java.sip.communicator.impl.protocol.jabber.ChatRoomJabberImpl$MemberListener.joined: stiffwestsschedulecalmly@muc.meet.jitsi/6fd20d42 has joined the stiffwestsschedulecalmly@muc.meet.jitsi chat room.
2024-11-28 16:27:57.445 INFO: [98] net.java.sip.communicator.impl.protocol.jabber.ChatRoomJabberImpl$MemberListener.joined: stiffwestsschedulecalmly@muc.meet.jitsi/focus has joined the stiffwestsschedulecalmly@muc.meet.jitsi chat room.
2024-11-28 16:27:57.448 INFO: [98] net.java.sip.communicator.impl.protocol.jabber.ChatRoomJabberImpl$MemberListener.joined: stiffwestsschedulecalmly@muc.meet.jitsi/2919511c has joined the stiffwestsschedulecalmly@muc.meet.jitsi chat room.
2024-11-28 16:27:57.499 INFO: [65] JvbConference.joinConferenceRoom#1129: [ctx=1732811275723448660979] Joined room: stiffwestsschedulecalmly@muc.meet.jitsi meetingId:9d1646cb-a088-4211-8c9a-625596379db5
2024-11-28 16:27:57.520 SEVERE: [65] JvbConference.lambda$new$0#209: Error processing xmpp queue item
java.lang.NoClassDefFoundError: Could not initialize class org.jitsi.webrtcvadwrapper.WebRTCVad
	at org.jitsi.webrtcvadwrapper.SpeechDetector.<init>(SpeechDetector.java:118)
	at org.jitsi.jigasi.transcription.SilenceFilter.<init>(SilenceFilter.java:62)
	at org.jitsi.jigasi.transcription.Participant.<init>(Participant.java:183)
	at org.jitsi.jigasi.transcription.Transcriber.lambda$maybeAddParticipant$0(Transcriber.java:316)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
	at org.jitsi.jigasi.transcription.Transcriber.maybeAddParticipant(Transcriber.java:315)
	at org.jitsi.jigasi.transcription.Transcriber.updateParticipant(Transcriber.java:330)
	at org.jitsi.jigasi.TranscriptionGatewaySession.notifyChatRoomMemberJoined(TranscriptionGatewaySession.java:318)
	at org.jitsi.jigasi.JvbConference.memberPresenceChangedInternal(JvbConference.java:1387)
	at org.jitsi.jigasi.JvbConference.lambda$memberPresenceChanged$7(JvbConference.java:1368)
	at org.jitsi.jigasi.JvbConference.lambda$new$0(JvbConference.java:203)
	at org.jitsi.utils.queue.PacketQueue$HandlerAdapter.handleItem(PacketQueue.java:416)
	at org.jitsi.utils.queue.AsyncQueueHandler$1.run(AsyncQueueHandler.java:137)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: no fvad in java.library.path: /usr/share/jigasi/lib [in thread "xmpp-executor-poolpool-7-thread-1"]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2434)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
	at java.base/java.lang.System.loadLibrary(System.java:2006)
	at org.jitsi.utils.JNIUtils.loadNativeInClassloader(JNIUtils.java:148)
	at org.jitsi.utils.JNIUtils.loadLibrary(JNIUtils.java:69)
	at org.jitsi.utils.JNIUtils.loadLibrary(JNIUtils.java:43)
	at org.jitsi.webrtcvadwrapper.WebRTCVad.<clinit>(WebRTCVad.java:42)
	... 18 more
2024-11-28 16:27:57.569 SEVERE: [65] JvbConference.lambda$new$0#209: Error processing xmpp queue item
java.lang.NoClassDefFoundError: Could not initialize class org.jitsi.webrtcvadwrapper.WebRTCVad
	at org.jitsi.webrtcvadwrapper.SpeechDetector.<init>(SpeechDetector.java:118)
	at org.jitsi.jigasi.transcription.SilenceFilter.<init>(SilenceFilter.java:62)
	at org.jitsi.jigasi.transcription.Participant.<init>(Participant.java:183)
	at org.jitsi.jigasi.transcription.Transcriber.lambda$maybeAddParticipant$0(Transcriber.java:316)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
	at org.jitsi.jigasi.transcription.Transcriber.maybeAddParticipant(Transcriber.java:315)
	at org.jitsi.jigasi.transcription.Transcriber.updateParticipant(Transcriber.java:330)
	at org.jitsi.jigasi.TranscriptionGatewaySession.notifyChatRoomMemberUpdated(TranscriptionGatewaySession.java:398)
	at org.jitsi.jigasi.JvbConference.memberPresenceChangedInternal(JvbConference.java:1394)
	at org.jitsi.jigasi.JvbConference.lambda$memberPresenceChanged$7(JvbConference.java:1368)
	at org.jitsi.jigasi.JvbConference.lambda$new$0(JvbConference.java:203)
	at org.jitsi.utils.queue.PacketQueue$HandlerAdapter.handleItem(PacketQueue.java:416)
	at org.jitsi.utils.queue.AsyncQueueHandler$1.run(AsyncQueueHandler.java:137)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: no fvad in java.library.path: /usr/share/jigasi/lib [in thread "xmpp-executor-poolpool-7-thread-1"]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2434)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
	at java.base/java.lang.System.loadLibrary(System.java:2006)
	at org.jitsi.utils.JNIUtils.loadNativeInClassloader(JNIUtils.java:148)
	at org.jitsi.utils.JNIUtils.loadLibrary(JNIUtils.java:69)
	at org.jitsi.utils.JNIUtils.loadLibrary(JNIUtils.java:43)
	at org.jitsi.webrtcvadwrapper.WebRTCVad.<clinit>(WebRTCVad.java:42)
	at org.jitsi.webrtcvadwrapper.SpeechDetector.<init>(SpeechDetector.java:118)
	at org.jitsi.jigasi.transcription.SilenceFilter.<init>(SilenceFilter.java:62)
	at org.jitsi.jigasi.transcription.Participant.<init>(Participant.java:183)
	at org.jitsi.jigasi.transcription.Transcriber.lambda$maybeAddParticipant$0(Transcriber.java:316)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
	at org.jitsi.jigasi.transcription.Transcriber.maybeAddParticipant(Transcriber.java:315)
	at org.jitsi.jigasi.transcription.Transcriber.updateParticipant(Transcriber.java:330)
	at org.jitsi.jigasi.TranscriptionGatewaySession.notifyChatRoomMemberJoined(TranscriptionGatewaySession.java:318)
	at org.jitsi.jigasi.JvbConference.memberPresenceChangedInternal(JvbConference.java:1387)
	... 9 more
2024-11-28 16:27:58.603 INFO: [114] net.java.sip.communicator.impl.protocol.jabber.IceUdpTransportManager.createIceAgent: End gathering harvester within 296 ms
2024-11-28 16:27:59.117 SEVERE: [65] JvbConference.lambda$new$0#209: Error processing xmpp queue item
java.lang.NoClassDefFoundError: Could not initialize class org.jitsi.webrtcvadwrapper.WebRTCVad
	at org.jitsi.webrtcvadwrapper.SpeechDetector.<init>(SpeechDetector.java:118)
	at org.jitsi.jigasi.transcription.SilenceFilter.<init>(SilenceFilter.java:62)
	at org.jitsi.jigasi.transcription.Participant.<init>(Participant.java:183)
	at org.jitsi.jigasi.transcription.Transcriber.lambda$maybeAddParticipant$0(Transcriber.java:316)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
	at org.jitsi.jigasi.transcription.Transcriber.maybeAddParticipant(Transcriber.java:315)
	at org.jitsi.jigasi.transcription.Transcriber.updateParticipant(Transcriber.java:330)
	at org.jitsi.jigasi.TranscriptionGatewaySession.notifyChatRoomMemberUpdated(TranscriptionGatewaySession.java:398)
	at org.jitsi.jigasi.JvbConference.memberPresenceChangedInternal(JvbConference.java:1394)
	at org.jitsi.jigasi.JvbConference.lambda$memberPresenceChanged$7(JvbConference.java:1368)
	at org.jitsi.jigasi.JvbConference.lambda$new$0(JvbConference.java:203)
	at org.jitsi.utils.queue.PacketQueue$HandlerAdapter.handleItem(PacketQueue.java:416)
	at org.jitsi.utils.queue.AsyncQueueHandler$1.run(AsyncQueueHandler.java:137)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: no fvad in java.library.path: /usr/share/jigasi/lib [in thread "xmpp-executor-poolpool-7-thread-1"]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2434)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
	at java.base/java.lang.System.loadLibrary(System.java:2006)
	at org.jitsi.utils.JNIUtils.loadNativeInClassloader(JNIUtils.java:148)
	at org.jitsi.utils.JNIUtils.loadLibrary(JNIUtils.java:69)
	at org.jitsi.utils.JNIUtils.loadLibrary(JNIUtils.java:43)
	at org.jitsi.webrtcvadwrapper.WebRTCVad.<clinit>(WebRTCVad.java:42)
	at org.jitsi.webrtcvadwrapper.SpeechDetector.<init>(SpeechDetector.java:118)
	at org.jitsi.jigasi.transcription.SilenceFilter.<init>(SilenceFilter.java:62)
	at org.jitsi.jigasi.transcription.Participant.<init>(Participant.java:183)
	at org.jitsi.jigasi.transcription.Transcriber.lambda$maybeAddParticipant$0(Transcriber.java:316)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
	at org.jitsi.jigasi.transcription.Transcriber.maybeAddParticipant(Transcriber.java:315)
	at org.jitsi.jigasi.transcription.Transcriber.updateParticipant(Transcriber.java:330)
	at org.jitsi.jigasi.TranscriptionGatewaySession.notifyChatRoomMemberJoined(TranscriptionGatewaySession.java:318)
	at org.jitsi.jigasi.JvbConference.memberPresenceChangedInternal(JvbConference.java:1387)
	... 9 more
2024-11-28 16:27:59.817 INFO: [114] net.java.sip.communicator.impl.protocol.jabber.CallPeerMediaHandlerJabberImpl.harvestCandidates: End candidate harvest within 1209 ms
2024-11-28 16:27:59.825 INFO: [65] JvbConference$JvbCallListener.incomingCallReceivedInternal#1676: [ctx=1732811275723448660979] Got invite from focus
2024-11-28 16:27:59.962 SEVERE: [65] JvbConference.lambda$new$0#209: Error processing xmpp queue item
java.lang.NoClassDefFoundError: Could not initialize class org.jitsi.webrtcvadwrapper.WebRTCVad
	at org.jitsi.webrtcvadwrapper.SpeechDetector.<init>(SpeechDetector.java:118)
	at org.jitsi.jigasi.transcription.SilenceFilter.<init>(SilenceFilter.java:62)
	at org.jitsi.jigasi.transcription.Participant.<init>(Participant.java:183)
	at org.jitsi.jigasi.transcription.Transcriber.lambda$maybeAddParticipant$0(Transcriber.java:316)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
	at org.jitsi.jigasi.transcription.Transcriber.maybeAddParticipant(Transcriber.java:315)
	at org.jitsi.jigasi.transcription.Transcriber.updateParticipant(Transcriber.java:330)
	at org.jitsi.jigasi.TranscriptionGatewaySession.addInitialMembers(TranscriptionGatewaySession.java:610)
	at org.jitsi.jigasi.TranscriptionGatewaySession.onConferenceCallStarted(TranscriptionGatewaySession.java:238)
	at org.jitsi.jigasi.TranscriptionGatewaySession.onConferenceCallInvited(TranscriptionGatewaySession.java:195)
	at org.jitsi.jigasi.JvbConference$JvbCallListener.incomingCallReceivedInternal(JvbConference.java:1754)
	at org.jitsi.jigasi.JvbConference$JvbCallListener.lambda$incomingCallReceived$0(JvbConference.java:1656)
	at org.jitsi.jigasi.JvbConference.lambda$new$0(JvbConference.java:203)
	at org.jitsi.utils.queue.PacketQueue$HandlerAdapter.handleItem(PacketQueue.java:416)
	at org.jitsi.utils.queue.AsyncQueueHandler$1.run(AsyncQueueHandler.java:137)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: no fvad in java.library.path: /usr/share/jigasi/lib [in thread "xmpp-executor-poolpool-7-thread-1"]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2434)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
	at java.base/java.lang.System.loadLibrary(System.java:2006)
	at org.jitsi.utils.JNIUtils.loadNativeInClassloader(JNIUtils.java:148)
	at org.jitsi.utils.JNIUtils.loadLibrary(JNIUtils.java:69)
	at org.jitsi.utils.JNIUtils.loadLibrary(JNIUtils.java:43)
	at org.jitsi.webrtcvadwrapper.WebRTCVad.<clinit>(WebRTCVad.java:42)
	at org.jitsi.webrtcvadwrapper.SpeechDetector.<init>(SpeechDetector.java:118)
	at org.jitsi.jigasi.transcription.SilenceFilter.<init>(SilenceFilter.java:62)
	at org.jitsi.jigasi.transcription.Participant.<init>(Participant.java:183)
	at org.jitsi.jigasi.transcription.Transcriber.lambda$maybeAddParticipant$0(Transcriber.java:316)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
	at org.jitsi.jigasi.transcription.Transcriber.maybeAddParticipant(Transcriber.java:315)
	at org.jitsi.jigasi.transcription.Transcriber.updateParticipant(Transcriber.java:330)
	at org.jitsi.jigasi.TranscriptionGatewaySession.notifyChatRoomMemberJoined(TranscriptionGatewaySession.java:318)
	at org.jitsi.jigasi.JvbConference.memberPresenceChangedInternal(JvbConference.java:1387)
	at org.jitsi.jigasi.JvbConference.lambda$memberPresenceChanged$7(JvbConference.java:1368)
	... 8 more
2024-11-28 16:28:05.275 WARNING: [65] net.java.sip.communicator.impl.protocol.jabber.ChatRoomJabberImpl.leave: Force sending presence unavailable to stiffwestsschedulecalmly@muc.meet.jitsi for 2919511c
2024-11-28 16:28:05.287 WARNING: [71] net.java.sip.communicator.impl.protocol.jabber.ChatRoomJabberImpl$ChatRoomPresenceListener.processStanza: Unable to handle packet: Presence Stanza [to=transcriber@hidden.meet.jitsi/2919511c,from=stiffwestsschedulecalmly@muc.meet.jitsi/2919511c,id=8JZ3Z-58,type=error,]
2024-11-28 16:28:05.306 WARNING: [92] net.java.sip.communicator.impl.protocol.jabber.ChatRoomJabberImpl$ChatRoomPresenceListener.processStanza: Unable to handle packet: Presence Stanza [to=transcriber@hidden.meet.jitsi/2919511c,from=stiffwestsschedulecalmly@muc.meet.jitsi/2919511c,id=83YFT-4,type=error,]
2024-11-28 16:28:05.455 INFO: [65] AbstractGateway.notifyCallEnded#155: [ctx=1732811275723448660979] Removed session for call. Sessions:0
2024-11-28 16:28:05.460 INFO: [65] JvbConference.memberPresenceChangedInternal#1404: [ctx=1732811275723448660979] Member left : OWNER 6fd20d42-b45e-4e19-b4bd-a58bd5fdedc3@meet.jitsi/rGJc-4-fALVq
2024-11-28 16:28:05.460 INFO: [65] JvbConference.memberPresenceChangedInternal#1404: [ctx=1732811275723448660979] Member left : OWNER focus@auth.meet.jitsi/focus
2024-11-28 16:28:05.460 INFO: [65] JvbConference.memberPresenceChangedInternal#1404: [ctx=1732811275723448660979] Member left : MEMBER transcriber@hidden.meet.jitsi
2024-11-28 16:28:05.461 SEVERE: [65] JvbConference$JvbCallChangeListener.callStateChangedInternal#1777: [ctx=1732811275723448660979] Call change event for different call ? Call: id=1732811278280808797668 peers=0 : null
2024-11-28 16:28:05.464 INFO: [86] net.java.sip.communicator.impl.protocol.jabber.OperationSetBasicTelephonyJabberImpl.registrationStateChanged: Jingle : OFF
2024-11-28 16:28:05.465 INFO: [86] CallManager$HangupCallThread.run#660: [ctx=1732811275723448660979] Removing account Jabber:transcriber@hidden.meet.jitsi/2919511c
2024-11-28 16:28:05.467 INFO: [86] net.java.sip.communicator.impl.protocol.jabber.OperationSetBasicTelephonyJabberImpl.registrationStateChanged: Jingle : OFF
2024-11-28 16:28:08.460 WARNING: [127] Transcriber.participantLeft#472: stiffwestsschedulecalmly@muc.meet.jitsi: participant with identifier 6fd20d42 left while it did not exist
```

**Comment by damencho** [comment]
> 



> JIGASI_TRANSCRIBER_FILTER_SILENCE=true

Disable it, I don't think that works. It has been broken for a long time.

**Comment by Yerachmiel-Wand** [comment]
thanks. I'll try this too.

meanwhile, I found another solution: change the image platform to `platform: linux/x86_64
`
Probably because I'm on mac silicon it defaulted to arm and then failed.

**Comment by saghul** [comment]
> > 
> 
> 
> 
> 
> 
> 
> 
> > JIGASI_TRANSCRIBER_FILTER_SILENCE=true
> 
> 
> 
> Disable it, I don't think that works. It has been broken for a long time.
> 
> 

Should we remove the option altogether?

**Comment by damencho** [comment]
There is such option and code. But it needs taken care of some dependency ... We may fix it some day ... So I don't know, we may remove it for the time being
