### ISSUE TITLE
Cannot connect to Vosk container

### ISSUE THREAD

**Issue by Yerachmiel-Wand** [jitsi/docker-jitsi-meet#1972]
Hi, I'm running Vosk container:
```
docker run -d -p 2700:2700 alphacep/kaldi-en:latest
```
I can test it directly using a test script and it's working. Vosk's logs:
```
INFO:root:Connection from ('192.168.65.1', 35637)
INFO:root:Config {'sample_rate': 8000}
```

However, when enabling subtitles Jigasi fails with:

```
2024-12-02 21:07:04.415 WARNING: [56] net.java.sip.communicator.impl.protocol.jabber.ChatRoomJabberImpl.leave: Force sending presence unavailable to residentoperasenrolincredibly@muc.meet.jitsi for 64886adb
2024-12-02 21:07:04.471 SEVERE: [115] RTPConnectorOutputStream.send#483: Failed to send a packet to target /172.22.0.3:10000:java.net.SocketException: Socket is closed
2024-12-02 21:07:04.497 SEVERE: [114] RTPConnectorOutputStream.send#483: Failed to send a packet to target /172.22.0.3:10000:java.io.IOException: No active socket.
2024-12-02 21:07:04.498 SEVERE: [112] RTPConnectorOutputStream.send#483: Failed to send a packet to target /172.22.0.3:10000:java.io.IOException: No active socket.
```

.env is as follows:

```
ENABLE_TRANSCRIPTIONS=true
# DISABLE_START_FOR_ALL=true
# AUTO_CAPTION_ON_RECORD=false
JIGASI_TRANSCRIBER_ENABLE_SAVING=true
JIGASI_TRANSCRIBER_FILTER_SILENCE=false # 'true' won't work: https://github.com/jitsi/docker-jitsi-meet/issues/1970
JIGASI_TRANSCRIBER_RECORD_AUDIO=true
JIGASI_TRANSCRIBER_CUSTOM_SERVICE=org.jitsi.jigasi.transcription.VoskTranscriptionService
JIGASI_TRANSCRIBER_VOSK_URL=ws://localhost:2700
# VOSK_SAMPLE_RATE=1600
```

From completeness's sake, here are all the logs from the moment captions are turned on:
```

2024-12-02 21:06:54.468 INFO: [39] CallControl.handleDialIq#201: [ctx=17331736144351893543982] Got dial request fromnumber -> jitsi_meet_transcribe room: residentoperasenrolincredibly@muc.meet.jitsi
2024-12-02 21:06:54.470 INFO: [39] TranscriptionGateway.getCustomTranscriptionServiceClass#173: [ctx=17331736144351893543982] Transcriber class retrieved from config: org.jitsi.jigasi.transcription.VoskTranscriptionService
2024-12-02 21:06:54.661 INFO: [39] JvbConference.start#589: [ctx=17331736144351893543982] Starting JVB conference room: residentoperasenrolincredibly@muc.meet.jitsi
2024-12-02 21:06:54.676 INFO: [39] JvbConference.setXmppProvider#734: [ctx=17331736144351893543982] Using ProtocolProviderServiceJabberImpl(Jabber:transcriber@hidden.meet.jitsi/64886adb)
2024-12-02 21:06:54.760 INFO: [53] net.java.sip.communicator.impl.protocol.jabber.OperationSetBasicTelephonyJabberImpl.registrationStateChanged: Jingle : ON
2024-12-02 21:06:54.767 INFO: [56] JvbConference.registrationStateChangedInternal#795: [ctx=17331736144351893543982] Registering XMPP.
2024-12-02 21:06:54.846 INFO: [53] net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl$JabberConnectionListener.authenticated: Authenticated: false
2024-12-02 21:06:54.867 INFO: [56] JvbConference.discoverComponentAddresses#859: [ctx=17331736144351893543982] Disco-info took 24ms.
2024-12-02 21:06:54.870 INFO: [56] JvbConference.joinConferenceRoom#961: [ctx=17331736144351893543982] Joining JVB conference room: residentoperasenrolincredibly@muc.meet.jitsi
2024-12-02 21:06:54.933 INFO: [47] net.java.sip.communicator.impl.protocol.jabber.ChatRoomJabberImpl$MemberListener.joined: residentoperasenrolincredibly@muc.meet.jitsi/26833d2a has joined the residentoperasenrolincredibly@muc.meet.jitsi chat room.
2024-12-02 21:06:54.940 INFO: [45] net.java.sip.communicator.impl.protocol.jabber.ChatRoomJabberImpl$MemberListener.joined: residentoperasenrolincredibly@muc.meet.jitsi/focus has joined the residentoperasenrolincredibly@muc.meet.jitsi chat room.
2024-12-02 21:06:54.942 INFO: [36] net.java.sip.communicator.impl.protocol.jabber.ChatRoomJabberImpl$MemberListener.joined: residentoperasenrolincredibly@muc.meet.jitsi/64886adb has joined the residentoperasenrolincredibly@muc.meet.jitsi chat room.
2024-12-02 21:06:54.993 INFO: [56] JvbConference.joinConferenceRoom#1129: [ctx=17331736144351893543982] Joined room: residentoperasenrolincredibly@muc.meet.jitsi meetingId:a608f00e-1209-4cbc-aabd-a3119b3230e1
2024-12-02 21:06:56.457 INFO: [77] net.java.sip.communicator.impl.protocol.jabber.IceUdpTransportManager.createIceAgent: End gathering harvester within 791 ms
2024-12-02 21:06:58.178 INFO: [77] net.java.sip.communicator.impl.protocol.jabber.CallPeerMediaHandlerJabberImpl.harvestCandidates: End candidate harvest within 1238 ms
2024-12-02 21:06:58.195 INFO: [56] JvbConference$JvbCallListener.incomingCallReceivedInternal#1676: [ctx=17331736144351893543982] Got invite from focus
2024-12-02 21:06:58.294 INFO: [112] TranscriptionGatewaySession$1.getDefaultDevice#185: Transcriber: Media Device Audio
2024-12-02 21:06:58.340 INFO: [112] net.java.sip.communicator.service.protocol.media.MediaHandler.registerDynamicPTsWithStream: Dynamic PT map: 126=rtpmap:-1 telephone-event/8000; 111=rtpmap:-1 opus/48000/2 fmtp:useinbandfec=1;minptime=10;
2024-12-02 21:06:58.340 INFO: [112] net.java.sip.communicator.service.protocol.media.MediaHandler.registerDynamicPTsWithStream: PT overrides []
2024-12-02 21:06:58.358 INFO: [112] net.java.sip.communicator.service.protocol.media.CallPeerMediaHandler.start: Starting
2024-12-02 21:06:58.614 INFO: [56] JvbConference$JvbCallChangeListener.callStateChangedInternal#1785: [ctx=17331736144351893543982] JVB conference call IN_PROGRESS.
2024-12-02 21:06:58.749 INFO: [118] JitsiOpenSslProvider.<clinit>#52: jitsisrtp successfully loaded for OpenSSL 3
2024-12-02 21:06:59.135 INFO: [118] Aes.benchmark#367: AES benchmark (of execution times expressed in nanoseconds): OpenSSL 741, SunJCE 458, BouncyCastle 9587 for AES/CTR/NoPadding
2024-12-02 21:06:59.136 INFO: [118] Aes.createCipher#433: Will employ AES implemented by SunJCE for AES/CTR/NoPadding.
2024-12-02 21:07:04.415 WARNING: [56] net.java.sip.communicator.impl.protocol.jabber.ChatRoomJabberImpl.leave: Force sending presence unavailable to residentoperasenrolincredibly@muc.meet.jitsi for 64886adb
2024-12-02 21:07:04.471 SEVERE: [115] RTPConnectorOutputStream.send#483: Failed to send a packet to target /172.22.0.3:10000:java.net.SocketException: Socket is closed
2024-12-02 21:07:04.497 SEVERE: [114] RTPConnectorOutputStream.send#483: Failed to send a packet to target /172.22.0.3:10000:java.io.IOException: No active socket.
2024-12-02 21:07:04.498 SEVERE: [112] RTPConnectorOutputStream.send#483: Failed to send a packet to target /172.22.0.3:10000:java.io.IOException: No active socket.
2024-12-02 21:07:04.510 INFO: [112] net.java.sip.communicator.impl.protocol.jabber.OperationSetBasicTelephonyJabberImpl.registrationStateChanged: Jingle : OFF
2024-12-02 21:07:04.511 INFO: [112] CallManager$HangupCallThread.run#660: [ctx=17331736144351893543982] Removing account Jabber:transcriber@hidden.meet.jitsi/64886adb
2024-12-02 21:07:04.511 INFO: [112] net.java.sip.communicator.impl.protocol.jabber.OperationSetBasicTelephonyJabberImpl.registrationStateChanged: Jingle : OFF
2024-12-02 21:07:04.983 INFO: [56] AbstractTranscriptPublisher.saveTranscriptStringToFile#210: Wrote final transcript to /tmp/transcripts/2024-12-02T21:06:58.212859378Z_1fb35966-981e-4d5b-acf3-ca0a2dc679cf/transcript_2024-12-02T21:06:58.213657628Z_fed042b1-e273-45b3-bb7b-513a0aa58f86.txt
2024-12-02 21:07:04.986 INFO: [56] AbstractGateway.notifyCallEnded#155: [ctx=17331736144351893543982] Removed session for call. Sessions:0
2024-12-02 21:07:04.987 INFO: [56] JvbConference.memberPresenceChangedInternal#1404: [ctx=17331736144351893543982] Member left : OWNER focus@auth.meet.jitsi/focus
2024-12-02 21:07:04.988 INFO: [56] JvbConference.memberPresenceChangedInternal#1404: [ctx=17331736144351893543982] Member left : MEMBER transcriber@hidden.meet.jitsi
2024-12-02 21:07:04.993 INFO: [56] JvbConference.memberPresenceChangedInternal#1404: [ctx=17331736144351893543982] Member left : OWNER 26833d2a-7cde-40a8-bf79-5d918a46de8d@meet.jitsi/pbv1ehq57km8
2024-12-02 21:07:04.993 SEVERE: [56] JvbConference$JvbCallChangeListener.callStateChangedInternal#1777: [ctx=17331736144351893543982] Call change event for different call ? Call: id=17331736156312098132851 peers=0 : null
2024-12-02 21:07:07.996 SEVERE: [251] VoskTranscriptionService$VoskWebsocketStreamingSession.end#359: Error to finalize websocket connection for participant residentoperasenrolincredibly/26833d2a
java.lang.NullPointerException: Cannot invoke "org.eclipse.jetty.websocket.api.Session.getRemote()" because "this.session" is null
	at org.jitsi.jigasi.transcription.VoskTranscriptionService$VoskWebsocketStreamingSession.end(VoskTranscriptionService.java:355)
	at org.jitsi.jigasi.transcription.Participant.left(Participant.java:543)
	at org.jitsi.jigasi.transcription.Transcriber.participantLeft(Transcriber.java:459)
	at org.jitsi.jigasi.TranscriptionGatewaySession.lambda$notifyChatRoomMemberLeft$0(TranscriptionGatewaySession.java:345)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

We can be sure Vosk is not being called by checking Vosk's container logs:
```
# WHEN I TESTED MANUALLY
INFO:root:Connection from ('192.168.65.1', 35637)
INFO:root:Config {'sample_rate': 8000}
# WHEN TRYING Jigasi, we see nothing from here
```

Thank you!

**Comment by HighwayStar** [comment]
>ws://localhost:2700

you have to specify ip address or name resolvable by trancriber container.  When you set it to localhost it means it ties to find it inside transcriber container, while it is another container.

Easy way is to create vosk.yml like
```
version: '3.5'

services:
    vosk:
        image: alphacep/kaldi-ru:latest
        restart: ${RESTART_POLICY:-unless-stopped}
        ports:
            - '2700:2700'
        networks:
            meet.jitsi:

```

and set JIGASI_TRANSCRIBER_VOSK_URL=ws://vosk:2700  in .env

You also have to aded vosk.yml to your docker-compose up string like 

```
sudo docker-compose -f docker-compose.yml -f jibri.yml -f transcriber.yml -f jigasi.yml -f vosk.yml up -d
```
