### ISSUE TITLE
Camera Access not Requested

### ISSUE THREAD

**Issue by Treverr** [jitsi/docker-jitsi-meet#247]
I am able to get into a room but the browser is never asked for video access, but it is asked for microphone access when checking the logs in jvb I can see some error:

This happens using HTTPS on both Safari and Chrome.

```
jvb_1      | JVB 2020-03-20 14:32:09.673 SEVERE: [183] org.jitsi.impl.neomedia.transform.dtls.DtlsPacketTransformer.log() Failed to accept a connection from a DTLS client!
jvb_1      | java.io.IOException: org.jitsi.impl.neomedia.transform.dtls.DatagramTransportImpl is closed!
jvb_1      | 	at org.jitsi.impl.neomedia.transform.dtls.DatagramTransportImpl.assertNotClosed(DatagramTransportImpl.java:124)
jvb_1      | 	at org.jitsi.impl.neomedia.transform.dtls.DatagramTransportImpl.send(DatagramTransportImpl.java:477)
jvb_1      | 	at org.bouncycastle.crypto.tls.DTLSRecordLayer.sendRecord(Unknown Source)
jvb_1      | 	at org.bouncycastle.crypto.tls.DTLSRecordLayer.send(Unknown Source)
jvb_1      | 	at org.bouncycastle.crypto.tls.DTLSReliableHandshake$RecordLayerBuffer.sendToRecordLayer(Unknown Source)
jvb_1      | 	at org.bouncycastle.crypto.tls.DTLSReliableHandshake.writeHandshakeFragment(Unknown Source)
jvb_1      | 	at org.bouncycastle.crypto.tls.DTLSReliableHandshake.writeMessage(Unknown Source)
jvb_1      | 	at org.bouncycastle.crypto.tls.DTLSReliableHandshake.resendOutboundFlight(Unknown Source)
jvb_1      | 	at org.bouncycastle.crypto.tls.DTLSReliableHandshake.receiveMessage(Unknown Source)
jvb_1      | 	at org.bouncycastle.crypto.tls.DTLSServerProtocol.serverHandshake(Unknown Source)
jvb_1      | 	at org.bouncycastle.crypto.tls.DTLSServerProtocol.accept(Unknown Source)
jvb_1      | 	at org.jitsi.impl.neomedia.transform.dtls.DtlsPacketTransformer.runInConnectThread(DtlsPacketTransformer.java:1043)
jvb_1      | 	at org.jitsi.impl.neomedia.transform.dtls.DtlsPacketTransformer.access$000(DtlsPacketTransformer.java:40)
jvb_1      | 	at org.jitsi.impl.neomedia.transform.dtls.DtlsPacketTransformer$1.run(DtlsPacketTransformer.java:1272)
```

Full logs:
[logs.log](https://github.com/jitsi/docker-jitsi-meet/files/4361926/logs.log)

**Comment by Treverr** [comment]
Client Logs:

```
[Error] [modules/RTC/BridgeChannel.js] – "<i>: " – "Bridge Channel send: no opened channel."
	error
	i (lib-jitsi-meet.min.js:6:251432)
	i
	value (lib-jitsi-meet.min.js:40:33066)
	value (lib-jitsi-meet.min.js:40:30561)
	value (lib-jitsi-meet.min.js:6:115376)
	(anonymous function) (lib-jitsi-meet.min.js:6:299867)
	(anonymous function) (lib-jitsi-meet.min.js:6:299948)
	value (lib-jitsi-meet.min.js:40:83766)
	value (lib-jitsi-meet.min.js:40:84414)
	value
	(anonymous function) (lib-jitsi-meet.min.js:6:144572)
	(anonymous function) (lib-jitsi-meet.min.js:25:47967)
	(anonymous function) (lib-jitsi-meet.min.js:25:52010)
	(anonymous function) (lib-jitsi-meet.min.js:25:42146)
	promiseReactionJob
[Error] [JitsiMeetJS.js] – "<i>: " – "UnhandledError: null" – "Script: null" – "Line: null" – "Column: null" – "StackTrace: " – NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission. — AbstractAudio.js:84
NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission. — AbstractAudio.js:84
	error
	i (lib-jitsi-meet.min.js:6:251432)
	i
	getGlobalOnErrorHandler (lib-jitsi-meet.min.js:40:138225)
	(anonymous function) (app.bundle.min.js:1:58695)
[Error] Unhandled Promise Rejection: NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
	(anonymous function)
	rejectPromise
	play
	play (app.bundle.min.js:211:106764)
	(anonymous function) (app.bundle.min.js:232:275610)
	(anonymous function) (app.bundle.min.js:232:275719)
	(anonymous function) (app.bundle.min.js:24:79592)
	(anonymous function) (app.bundle.min.js:232:271398)
	W (app.bundle.min.js:1:131804)
	(anonymous function) (app.bundle.min.js:1:134184)
	l (app.bundle.min.js:35:119351)
	(anonymous function) (app.bundle.min.js:250:150036)
	(anonymous function) (lib-jitsi-meet.min.js:6:144572)
	(anonymous function) (lib-jitsi-meet.min.js:6:290064)
	(anonymous function)
	(anonymous function) (lib-jitsi-meet.min.js:6:144572)
	value (lib-jitsi-meet.min.js:25:69715)
	value (lib-jitsi-meet.min.js:25:70897)
	value (lib-jitsi-meet.min.js:25:59150)
	value
	run (lib-jitsi-meet.min.js:6:21526)
	(anonymous function) (lib-jitsi-meet.min.js:6:29839)
	forEachChild (lib-jitsi-meet.min.js:6:13290)
	_dataRecv (lib-jitsi-meet.min.js:6:29681)
	_dataRecv
	_onRequestStateChange (lib-jitsi-meet.min.js:6:49336)
	_onRequestStateChange
	bound _onRequestStateChange
[Error] [conference.js] – "<i>: " – "CONFERENCE FAILED:" – "conference.offerAnswerFailed" – SyntaxError: Multiple Simulcast attributes specified. — word.js:37
SyntaxError: Multiple Simulcast attributes specified. — word.js:37
	error
	i (app.bundle.min.js:60:69774)
	i
	_onConferenceFailed (app.bundle.min.js:250:136311)
	_onConferenceFailed
	(anonymous function) (lib-jitsi-meet.min.js:6:144363)
	(anonymous function) (lib-jitsi-meet.min.js:6:329036)
	(anonymous function) (lib-jitsi-meet.min.js:6:144363)
	(anonymous function) (lib-jitsi-meet.min.js:40:55304)
	promiseReactionJob
[Error] [modules/xmpp/JingleSessionPC.js] – "<i>: " – "removeRemoteStream failed:" – SyntaxError: Multiple Simulcast attributes specified. — word.js:37
SyntaxError: Multiple Simulcast attributes specified. — word.js:37
	error
	i (lib-jitsi-meet.min.js:6:251432)
	i
	(anonymous function) (lib-jitsi-meet.min.js:6:205145)
	promiseReactionJob
[Error] [JitsiMeetJS.js] – "<i>: " – "UnhandledError: null" – "Script: null" – "Line: null" – "Column: null" – "StackTrace: " – NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission. — AbstractAudio.js:84
NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission. — AbstractAudio.js:84
	error
	i (lib-jitsi-meet.min.js:6:251432)
	i
	getGlobalOnErrorHandler (lib-jitsi-meet.min.js:40:138225)
	(anonymous function) (app.bundle.min.js:1:58695)
[Error] Unhandled Promise Rejection: NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
	(anonymous function)
	rejectPromise
	play
	play (app.bundle.min.js:211:106764)
	(anonymous function) (app.bundle.min.js:232:275610)
	(anonymous function) (app.bundle.min.js:232:275719)
	(anonymous function) (app.bundle.min.js:24:79592)
	(anonymous function) (app.bundle.min.js:232:271398)
	W (app.bundle.min.js:1:131804)
	(anonymous function) (app.bundle.min.js:1:134184)
	(anonymous function) (app.bundle.min.js:1:134378)
	_listener (app.bundle.min.js:84:69398)
	_listener
	b (app.bundle.min.js:35:124598)
	(anonymous function) (app.bundle.min.js:60:93821)
	(anonymous function) (app.bundle.min.js:35:9293)
	(anonymous function) (app.bundle.min.js:35:7278)
	(anonymous function) (app.bundle.min.js:35:5347)
	(anonymous function) (app.bundle.min.js:211:105499)
	(anonymous function) (app.bundle.min.js:35:3620)
	(anonymous function) (app.bundle.min.js:16:96734)
	(anonymous function) (app.bundle.min.js:60:66042)
	(anonymous function) (app.bundle.min.js:65:48884)
	(anonymous function) (app.bundle.min.js:243:29262)
	(anonymous function) (app.bundle.min.js:60:225100)
	(anonymous function) (app.bundle.min.js:243:25704)
	(anonymous function) (app.bundle.min.js:232:286104)
	(anonymous function) (app.bundle.min.js:60:96886)
	(anonymous function) (app.bundle.min.js:1:49284)
	(anonymous function) (app.bundle.min.js:24:79592)
	(anonymous function) (app.bundle.min.js:232:271398)
	_onConferenceFailed (app.bundle.min.js:250:136280)
	_onConferenceFailed
	(anonymous function) (lib-jitsi-meet.min.js:6:144363)
	(anonymous function) (lib-jitsi-meet.min.js:6:329036)
	(anonymous function) (lib-jitsi-meet.min.js:6:144363)
	(anonymous function) (lib-jitsi-meet.min.js:40:55304)
	promiseReactionJob
[Error] [JitsiMeetJS.js] – "<i>: " – "UnhandledError: null" – "Script: null" – "Line: null" – "Column: null" – "StackTrace: " – NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission. — AbstractAudio.js:84
NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission. — AbstractAudio.js:84
	error
	i (lib-jitsi-meet.min.js:6:251432)
	i
	getGlobalOnErrorHandler (lib-jitsi-meet.min.js:40:138225)
	(anonymous function) (app.bundle.min.js:1:58695)
[Error] Unhandled Promise Rejection: NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
	(anonymous function)
	rejectPromise
	play
	play (app.bundle.min.js:211:106764)
	(anonymous function) (app.bundle.min.js:232:275610)
	(anonymous function) (app.bundle.min.js:232:275719)
	(anonymous function) (app.bundle.min.js:24:79592)
	(anonymous function) (app.bundle.min.js:232:271398)
	W (app.bundle.min.js:1:131804)
	(anonymous function) (app.bundle.min.js:1:134184)
	(anonymous function) (app.bundle.min.js:1:134378)
	_listener (app.bundle.min.js:84:69398)
	_listener
	b (app.bundle.min.js:35:124598)
	(anonymous function) (app.bundle.min.js:60:93821)
	(anonymous function) (app.bundle.min.js:35:9293)
	(anonymous function) (app.bundle.min.js:35:7278)
	(anonymous function) (app.bundle.min.js:35:5347)
	(anonymous function) (app.bundle.min.js:211:105499)
	(anonymous function) (app.bundle.min.js:35:3620)
	(anonymous function) (app.bundle.min.js:16:96734)
	(anonymous function) (app.bundle.min.js:60:66042)
	(anonymous function) (app.bundle.min.js:65:48884)
	(anonymous function) (app.bundle.min.js:243:29262)
	(anonymous function) (app.bundle.min.js:60:225100)
	(anonymous function) (app.bundle.min.js:243:25704)
	(anonymous function) (app.bundle.min.js:232:286104)
	(anonymous function) (app.bundle.min.js:60:96886)
	(anonymous function) (app.bundle.min.js:1:49284)
	(anonymous function) (app.bundle.min.js:24:79592)
	(anonymous function) (app.bundle.min.js:232:271398)
	_onConferenceFailed (app.bundle.min.js:250:136280)
	_onConferenceFailed
	(anonymous function) (lib-jitsi-meet.min.js:6:144363)
	(anonymous function) (lib-jitsi-meet.min.js:6:329036)
	(anonymous function) (lib-jitsi-meet.min.js:6:144363)
	(anonymous function) (lib-jitsi-meet.min.js:40:55304)
	promiseReactionJob
[Error] [JitsiMeetJS.js] – "<i>: " – "UnhandledError: null" – "Script: null" – "Line: null" – "Column: null" – "StackTrace: " – NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission. — AbstractAudio.js:84
NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission. — AbstractAudio.js:84
	error
	i (lib-jitsi-meet.min.js:6:251432)
	i
	getGlobalOnErrorHandler (lib-jitsi-meet.min.js:40:138225)
	(anonymous function) (app.bundle.min.js:1:58695)
[Error] Unhandled Promise Rejection: NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
	(anonymous function)
	rejectPromise
	play
	play (app.bundle.min.js:211:106764)
	(anonymous function) (app.bundle.min.js:232:275610)
	(anonymous function) (app.bundle.min.js:232:275719)
	(anonymous function) (app.bundle.min.js:24:79592)
	(anonymous function) (app.bundle.min.js:232:271398)
	W (app.bundle.min.js:1:131804)
	(anonymous function) (app.bundle.min.js:1:134184)
	l (app.bundle.min.js:35:119351)
	(anonymous function) (app.bundle.min.js:250:150036)
	(anonymous function) (lib-jitsi-meet.min.js:6:144572)
	(anonymous function) (lib-jitsi-meet.min.js:6:290064)
	(anonymous function)
	(anonymous function) (lib-jitsi-meet.min.js:6:144572)
	value (lib-jitsi-meet.min.js:25:69715)
	(anonymous function) (lib-jitsi-meet.min.js:25:70751)
	forEach
	value (lib-jitsi-meet.min.js:25:70680)
	value (lib-jitsi-meet.min.js:25:59150)
	value
	run (lib-jitsi-meet.min.js:6:21526)
	(anonymous function) (lib-jitsi-meet.min.js:6:29839)
	forEachChild (lib-jitsi-meet.min.js:6:13290)
	_dataRecv (lib-jitsi-meet.min.js:6:29681)
	_dataRecv
	_onRequestStateChange (lib-jitsi-meet.min.js:6:49336)
	_onRequestStateChange
	bound _onRequestStateChange
[Error] [JitsiMeetJS.js] – "<i>: " – "UnhandledError: null" – "Script: null" – "Line: null" – "Column: null" – "StackTrace: " – NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission. — AbstractAudio.js:84
NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission. — AbstractAudio.js:84
	error
	i (lib-jitsi-meet.min.js:6:251432)
	i
	getGlobalOnErrorHandler (lib-jitsi-meet.min.js:40:138225)
	(anonymous function) (app.bundle.min.js:1:58695)
[Error] Unhandled Promise Rejection: NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
	(anonymous function)
	rejectPromise
	play
	play (app.bundle.min.js:211:106764)
	(anonymous function) (app.bundle.min.js:232:275610)
	(anonymous function) (app.bundle.min.js:232:275719)
	(anonymous function) (app.bundle.min.js:24:79592)
	(anonymous function) (app.bundle.min.js:232:271398)
	W (app.bundle.min.js:1:131804)
	(anonymous function) (app.bundle.min.js:1:134184)
	l (app.bundle.min.js:35:119351)
	(anonymous function) (app.bundle.min.js:250:150036)
	(anonymous function) (lib-jitsi-meet.min.js:6:144572)
	(anonymous function) (lib-jitsi-meet.min.js:6:290064)
	(anonymous function)
	(anonymous function) (lib-jitsi-meet.min.js:6:144572)
	value (lib-jitsi-meet.min.js:25:69715)
	(anonymous function) (lib-jitsi-meet.min.js:25:70751)
	forEach
	value (lib-jitsi-meet.min.js:25:70680)
	value (lib-jitsi-meet.min.js:25:59150)
	value
	run (lib-jitsi-meet.min.js:6:21526)
	(anonymous function) (lib-jitsi-meet.min.js:6:29839)
	forEachChild (lib-jitsi-meet.min.js:6:13290)
	_dataRecv (lib-jitsi-meet.min.js:6:29681)
	_dataRecv
	_onRequestStateChange (lib-jitsi-meet.min.js:6:49336)
	_onRequestStateChange
	bound _onRequestStateChange
[Error] [modules/UI/videolayout/SmallVideo.js] – "<i>: " – "Unable to init avatar - no id"
g

$container: E [<span id="localVideoContainer">] (1)

VideoLayout: {init: function, registerListeners: function, reset: function, initLargeVideo: function, setAudioLevel: function, …}

_connectionStatus: null

_isModerator: false

_onContainerClick: function()

_onPopoverHover: function()

_popoverIsHovered: false

_showConnectionIndicator: false

_showDominantSpeaker: false

_showRaisedHand: false

audioStream: null

container: <span id="localVideoContainer">

displayMode: 1

emitter: n {_events: Object, _maxListeners: undefined, setMaxListeners: function, emit: function, addListener: function, …}

hasAvatar: true

id: 

isAudioMuted: false

isLocal: true

isVideoMuted: true

localVideoId: null

statsPopoverLocation: "left top"

streamEndedCallback: function()

updateView: function()

videoIsHovered: false

videoSpanId: "localVideoContainer"

videoStream: null

videoType: "camera"

g Prototype
	error
	i (app.bundle.min.js:60:69774)
	i
	(anonymous function) (app.bundle.min.js:35:62806)
	(anonymous function)
	(anonymous function) (app.bundle.min.js:24:86960)
	promiseReactionJob
```

**Comment by sapkra** [comment]
@Treverr I think this is related to #263.

**Comment by saghul** [comment]
> [Error] [conference.js] – "<i>: " – "CONFERENCE FAILED:" – "conference.offerAnswerFailed" – SyntaxError: Multiple Simulcast attributes specified.

@jallamsetty1 have you seen this before?

**Comment by jallamsetty1** [comment]
@saghul the only case where we seem to be setting the Simulcast attributes is on Firefox. This happens when we call sRD on the browser with simulcast attributes.
@Treverr, do you have `enableFirefoxSimulcast` set to true in your config.js by any chance ?

**Comment by prasadkadiyala** [comment]
@saghul, getting the same issue when using Safari 13.1 with macOS Catalina 10.15.4.  Is this issue related to WebRTC Unified Plan feature?
