### ISSUE TITLE
client disconnected, "health check failed"

### ISSUE THREAD

**Issue by craftyguy** [jitsi/docker-jitsi-meet#329]
I'm running `stable-4101`, but this also occurs on the latest in the master branch too. Clients are disconnected every ~30 seconds or so with the following error below.

I'm running jitsi-meet on a system on my LAN right now, with no https (I intend to run it behind a reverse proxy once it is working properly).

Error in log:
```
jicofo_1   | Jicofo 2020-03-29 11:57:31.681 WARNING: [17] org.jitsi.jicofo.bridge.JvbDoctor.log() Health check failed on: jvbbrewery@internal-muc.meet.jitsi/0773d6d58033 error: <error type='cancel'><internal-server-error xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/><text xmlns='urn:ietf:params:xml:ns:xmpp-stanzas' xml:lang='en'>No health checks performed recently, the last result was 1585508251680ms ago.</text></error>
jicofo_1   | Jicofo 2020-03-29 11:57:31.683 INFO: [43] org.jitsi.jicofo.bridge.BridgeSelector.log() Removing JVB: jvbbrewery@internal-muc.meet.jitsi/0773d6d58033
jicofo_1   | Jicofo 2020-03-29 11:57:31.683 INFO: [43] org.jitsi.jicofo.bridge.JvbDoctor.log() Stopping health-check task for: jvbbrewery@internal-muc.meet.jitsi/0773d6d58033
jicofo_1   | Jicofo 2020-03-29 11:57:32.639 INFO: [31] org.jitsi.jicofo.ComponentsDiscovery.log() New component discovered: focus.meet.jitsi, null
jvb_1      | JVB 2020-03-29 11:57:36.672 INFO: [15] org.jitsi.xmpp.mucclient.MucClientManager.log() Setting a presence extension: org.jitsi.xmpp.extensions.colibri.ColibriStatsExtension@2fb2d3b4
jicofo_1   | Jicofo 2020-03-29 11:57:36.679 INFO: [28] org.jitsi.jicofo.bridge.BridgeSelector.log() Added videobridge: jvbbrewery@internal-muc.meet.jitsi/0773d6d58033 v: null
jicofo_1   | Jicofo 2020-03-29 11:57:36.679 WARNING: [28] org.jitsi.jicofo.bridge.BridgeSelector.log() No pub-sub node mapped for jvbbrewery@internal-muc.meet.jitsi/0773d6d58033
jicofo_1   | Jicofo 2020-03-29 11:57:36.680 INFO: [43] org.jitsi.jicofo.bridge.JvbDoctor.log() Scheduled health-check task for: jvbbrewery@internal-muc.meet.jitsi/0773d6d58033
jvb_1      | JVB 2020-03-29 11:57:41.675 INFO: [15] org.jitsi.xmpp.mucclient.MucClientManager.log() Setting a presence extension: org.jitsi.xmpp.extensions.colibri.ColibriStatsExtension@31f25d8d
jvb_1      | JVB 2020-03-29 11:57:46.678 INFO: [15] org.jitsi.xmpp.mucclient.MucClientManager.log() Setting a presence extension: org.jitsi.xmpp.extensions.colibri.ColibriStatsExtension@69c835a9
jvb_1      | java.lang.Exception: No health checks performed recently, the last result was 1585508266690ms ago.
jvb_1      |    at org.jitsi.videobridge.health.Health.check(Health.java:552)
jvb_1      |    at org.jitsi.videobridge.Videobridge.healthCheck(Videobridge.java:1253)
jvb_1      |    at org.jitsi.videobridge.Videobridge.handleHealthCheckIQ(Videobridge.java:1221)
jvb_1      |    at org.jitsi.videobridge.xmpp.XmppCommon.handleIQRequest(XmppCommon.java:197)
jvb_1      |    at org.jitsi.videobridge.xmpp.XmppCommon.handleIQInternal(XmppCommon.java:151)
jvb_1      |    at org.jitsi.videobridge.xmpp.XmppCommon.handleIQ(XmppCommon.java:122)
jvb_1      |    at org.jitsi.videobridge.xmpp.ClientConnectionImpl.handleIq(ClientConnectionImpl.java:122)
jvb_1      |    at org.jitsi.xmpp.mucclient.IQListener.handleIq(IQListener.java:50)
jvb_1      |    at org.jitsi.xmpp.mucclient.MucClient.handleIq(MucClient.java:446)
jvb_1      |    at org.jitsi.xmpp.mucclient.MucClient.access$500(MucClient.java:47)
jvb_1      |    at org.jitsi.xmpp.mucclient.MucClient$2.handleIQRequest(MucClient.java:412)
jvb_1      |    at org.jivesoftware.smack.AbstractXMPPConnection$4.run(AbstractXMPPConnection.java:1188)
jvb_1      |    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
jvb_1      |    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
jvb_1      |    at java.lang.Thread.run(Thread.java:748)

```

Here are the differences between the env.example and my env:

```
--- env.example 2020-03-28 18:50:01.023444982 -0700
+++ .env        2020-03-29 12:05:25.553832242 -0700
@@ -12,14 +12,14 @@
 HTTPS_PORT=8443

 # System time zone.
-TZ=Europe/Amsterdam
+TZ=US/Pacific-New

 # Public URL for the web service.
 #PUBLIC_URL="https://meet.example.com"

 # IP address of the Docker host. See the "Running on a LAN environment" section
 # in the README.
-#DOCKER_HOST_ADDRESS=192.168.1.1
+DOCKER_HOST_ADDRESS=192.168.1.13


 #
@@ -27,7 +27,7 @@
 #

 # Enable Let's Encrypt certificate generation.
-#ENABLE_LETSENCRYPT=1
+ENABLE_LETSENCRYPT=0

 # Domain for which to generate the certificate.
 #LETSENCRYPT_DOMAIN=meet.example.com
```

**Comment by saghul** [comment]
Can you disable `https://github.com/jitsi/docker-jitsi-meet/blob/master/env.example#L185` ? Make sure you wipe the CONFIG volume so the configuration is regenerated.

**Comment by craftyguy** [comment]
@saghul Thanks, that seems to resolve the issue with being disconnected. The errors still exist in the log, but maybe they are related to something else.
