### ISSUE TITLE
Jigasi SIP connection fails with "protocol family unavailable"

### ISSUE THREAD

**Issue by albe** [jitsi/docker-jitsi-meet#333]
After having docker-jitsi-meet running generally, I want to enable SIP call support via jigasi. I set the SIP variables and start jigasi successfully with `sudo docker-compose -f docker-compose.yml -f jigasi.yml up -d`
However, the connection to the SIP server fails:
```
jigasi_1   | Jigasi 2020-03-30 12:53:29.828 SEVERE: [35] impl.protocol.sip.SipRegistrarConnection.register().342 Could not send out the register request!
jigasi_1   | javax.sip.SipException: Protocol family unavailable
jigasi_1   |    at gov.nist.javax.sip.stack.SIPClientTransactionImpl.sendRequest(SIPClientTransactionImpl.java:1069)
jigasi_1   |    at net.java.sip.communicator.impl.protocol.sip.SipRegistrarConnection.register(SipRegistrarConnection.java:330)
jigasi_1   |    at net.java.sip.communicator.impl.protocol.sip.ProtocolProviderServiceSipImpl.registerUsingNextAddress(ProtocolProviderServiceSipImpl.java:2737)
jigasi_1   |    at net.java.sip.communicator.impl.protocol.sip.SipRegistrarConnection.register(SipRegistrarConnection.java:338)
jigasi_1   |    at net.java.sip.communicator.impl.protocol.sip.ProtocolProviderServiceSipImpl.registerUsingNextAddress(ProtocolProviderServiceSipImpl.java:2737)
jigasi_1   |    at net.java.sip.communicator.impl.protocol.sip.SipRegistrarConnection.register(SipRegistrarConnection.java:338)
jigasi_1   |    at net.java.sip.communicator.impl.protocol.sip.ProtocolProviderServiceSipImpl.registerUsingNextAddress(ProtocolProviderServiceSipImpl.java:2737)
jigasi_1   |    at net.java.sip.communicator.impl.protocol.sip.SipRegistrarConnection.register(SipRegistrarConnection.java:338)
jigasi_1   |    at net.java.sip.communicator.impl.protocol.sip.ProtocolProviderServiceSipImpl.registerUsingNextAddress(ProtocolProviderServiceSipImpl.java:2737)
jigasi_1   |    at net.java.sip.communicator.impl.protocol.sip.SipRegistrarConnection.processTimeout(SipRegistrarConnection.java:1108)
jigasi_1   |    at net.java.sip.communicator.impl.protocol.sip.ProtocolProviderServiceSipImpl.processTimeout(ProtocolProviderServiceSipImpl.java:904)
jigasi_1   |    at net.java.sip.communicator.impl.protocol.sip.SipStackSharing.processTimeout(SipStackSharing.java:839)
jigasi_1   |    at gov.nist.javax.sip.EventScanner.deliverTimeoutEvent(EventScanner.java:401)
jigasi_1   |    at gov.nist.javax.sip.EventScanner.deliverEvent(EventScanner.java:150)
jigasi_1   |    at gov.nist.javax.sip.SipProviderImpl.handleEvent(SipProviderImpl.java:185)
jigasi_1   |    at gov.nist.javax.sip.SipProviderImpl.transactionErrorEvent(SipProviderImpl.java:968)
jigasi_1   |    at gov.nist.javax.sip.stack.SIPTransactionImpl.raiseErrorEvent(SIPTransactionImpl.java:960)
jigasi_1   |    at gov.nist.javax.sip.stack.SIPClientTransactionImpl.fireTimeoutTimer(SIPClientTransactionImpl.java:1177)
jigasi_1   |    at gov.nist.javax.sip.stack.SIPTransactionImpl.fireTimer(SIPTransactionImpl.java:661)
jigasi_1   |    at gov.nist.javax.sip.stack.SIPClientTransactionImpl$TransactionTimer.runTask(SIPClientTransactionImpl.java:259)
jigasi_1   |    at gov.nist.javax.sip.stack.timers.DefaultSipTimer$DefaultTimerTask.run(DefaultSipTimer.java:67)
jigasi_1   |    at java.util.TimerThread.mainLoop(Timer.java:555)
jigasi_1   |    at java.util.TimerThread.run(Timer.java:505)
jigasi_1   | Caused by: java.net.SocketException: Protocol family unavailable
jigasi_1   |    at java.net.PlainDatagramSocketImpl.send(Native Method)
jigasi_1   |    at java.net.DatagramSocket.send(DatagramSocket.java:693)
jigasi_1   |    at gov.nist.javax.sip.stack.UDPMessageChannel.sendMessage(UDPMessageChannel.java:843)
jigasi_1   |    at gov.nist.javax.sip.stack.MessageChannel.sendMessage(MessageChannel.java:281)
jigasi_1   |    at gov.nist.javax.sip.stack.SIPTransactionImpl.sendMessage(SIPTransactionImpl.java:892)
jigasi_1   |    at gov.nist.javax.sip.stack.SIPClientTransactionImpl.sendMessage(SIPClientTransactionImpl.java:475)
jigasi_1   |    at gov.nist.javax.sip.stack.SIPClientTransactionImpl.sendRequest(SIPClientTransactionImpl.java:1062)
jigasi_1   |    ... 22 more
jigasi_1   | Jigasi 2020-03-30 12:53:29.830 INFO: [35] org.jitsi.jigasi.SipGateway.registrationStateChanged().105 REG STATE CHANGE ProtocolProviderServiceSipImpl(SIP:2413972e1@sipgate.de) -> RegistrationStateChangeEvent[ oldState=Registering; newState=RegistrationState=Connection Failed; reasonCode=6; reason=Protocol family unavailable]
```

After some research I found that this could be due to java choosing to use IPv6 and this should be worked around via two java options:
`-Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true`
See e.g. https://www.sipmann.com/socketException-protocol-family-unavailable-java-docker-wildfly.html#.XoHQ3ogzZPY

Setting this inside `jigasi/rootfs/etc/services.d/jigasi/run` `JAVA_SYS_PROPS=` solves the issue indeed. If it does work, I can see the registration of jigasi on the SIP server (but with the wrong IP of the docker container instead of the configured `DOCKER_HOST_ADDRESS` - different issue).

**Comment by albe** [comment]
Apparently, it still fails with above error sometimes, so there must be another factor. I'll try to narrow things done more.

**Comment by albe** [comment]
New finding: It seems to fail every other time, which is... odd? Probably concidence and just a timing issue?

**Comment by lingen** [comment]
@albe how you sovle sovle this problem? 

I still have this problem when using the Onsip sip server in Jitsi Meet in docker mode
