### ISSUE TITLE
Recording and Streaming option is not available

### ISSUE THREAD

**Issue by dikkatdeli** [jitsi/docker-jitsi-meet#348]
Hi,

I did:  JItsi BRoadcasting Infrastructure configuration and ENABLE_RECORDING=1 too

still dont have Recording and Streaming option.

```
root@meet:~/docker-jitsi-meet# docker-compose logs | grep jibri
jicofo_1   | Jicofo 2020-03-31 19:57:20.008 INFO: [10] org.jitsi.jicofo.JitsiMeetServices.log() Using a Jibri detector with MUC: jibribrewery@internal-muc.meet.jitsi
jicofo_1   | Jicofo 2020-03-31 19:57:25.846 INFO: [16] org.jitsi.jicofo.xmpp.BaseBrewery.start().186 Joined brewery room: jibribrewery@internal-muc.meet.jitsi
jicofo_1   | Jicofo 2020-03-31 19:57:30.814 INFO: [1] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() org.jitsi.jicofo.jibri.PENDING_TIMEOUT=90
jicofo_1   | Jicofo 2020-03-31 19:57:30.815 INFO: [1] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() org.jitsi.jicofo.jibri.BREWERY=jibribrewery@internal-muc.meet.jitsi
jicofo_1   | Jicofo 2020-03-31 19:57:35.109 INFO: [27] org.jitsi.jicofo.xmpp.BaseBrewery.processInstanceStatusChanged().318 Added brewery instance: jibribrewery@internal-muc.meet.jitsi/jibri-instanse-687780510
jicofo_1   | Jicofo 2020-03-31 19:57:35.110 INFO: [27] org.jitsi.jicofo.recording.jibri.JibriDetector.onInstanceStatusChanged().136 Received Jibri jibribrewery@internal-muc.meet.jitsi/jibri-instanse-687780510 status <jibri-status xmlns='http://jitsi.org/protocol/jibri'><busy-status xmlns='http://jitsi.org/protocol/jibri' status='idle'/><health-status xmlns='http://jitsi.org/protocol/health' status='healthy'/></jibri-status>
jicofo_1   | Jicofo 2020-03-31 19:57:35.123 INFO: [27] org.jitsi.jicofo.recording.jibri.JibriDetector.notifyJibriStatus().174 Jibri: jibribrewery@internal-muc.meet.jitsi/jibri-instanse-687780510 available: true
prosody_1  | c2s556c13b60620                           info     Authenticated as jibri@auth.meet.jitsi

```

What should i do to enable it?

**Comment by dikkatdeli** [comment]
Logs:

```
2020-03-31 19:57:25.842 INFO: [1] org.jitsi.jibri.Main.main() Jibri run with args [--config, /etc/jitsi/jibri/config.json]
2020-03-31 19:57:25.917 INFO: [1] org.jitsi.jibri.Main.main() Using config file /etc/jitsi/jibri/config.json
2020-03-31 19:57:25.966 INFO: [1] org.jitsi.jibri.Main.main() Using port 3333 for internal HTTP API
2020-03-31 19:57:25.969 INFO: [1] org.jitsi.jibri.Main.main() Using port 2222 for the HTTP API
2020-03-31 19:57:32.044 INFO: [1] org.jitsi.jibri.Main.loadConfig() Parsed config:
JibriConfig(recordingDirectory=/config/recordings, singleUseMode=false, enabledStatsD=true, finalizeRecordingScriptPath=/config/finalize.sh, xmppEnvironments=[XmppEnvironmentConfig(name=prod environment, xmppServerHosts=[xmpp.meet.jitsi], xmppDomain=meet.jitsi, controlLogin=XmppCredentials(domain=auth.meet.jitsi, username=jibri, password=passw0rd), controlMuc=XmppMuc(domain=internal-muc.meet.jitsi, roomName=jibribrewery, nickname=jibri-instanse-687780510), sipControlMuc=null, callLogin=XmppCredentials(domain=recorder.meet.jitsi, username=recorder, password=passw0rd), stripFromRoomDomain=muc., usageTimeoutMins=0, trustAllXmppCerts=true)])
2020-03-31 19:57:33.447 WARNING: [1] org.glassfish.jersey.internal.inject.Providers.checkProviderRuntime() A provider org.jitsi.jibri.api.http.internal.InternalHttpApi registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider org.jitsi.jibri.api.http.internal.InternalHttpApi will be ignored. 
2020-03-31 19:57:34.117 INFO: [1] org.jitsi.jibri.api.xmpp.XmppApi.updatePresence() Jibri reports its status is now JibriStatus(busyStatus=IDLE, health=OverallHealth(healthStatus=HEALTHY, details={})), publishing presence to connections
2020-03-31 19:57:34.126 INFO: [1] org.jitsi.xmpp.mucclient.MucClientManager.log() Setting a presence extension: org.jitsi.xmpp.extensions.jibri.JibriStatusPacketExt@771158fb
2020-03-31 19:57:34.137 INFO: [1] org.jitsi.jibri.api.xmpp.XmppApi.start() Connecting to xmpp environment on xmpp.meet.jitsi with config XmppEnvironmentConfig(name=prod environment, xmppServerHosts=[xmpp.meet.jitsi], xmppDomain=meet.jitsi, controlLogin=XmppCredentials(domain=auth.meet.jitsi, username=jibri, password=passw0rd), controlMuc=XmppMuc(domain=internal-muc.meet.jitsi, roomName=jibribrewery, nickname=jibri-instanse-687780510), sipControlMuc=null, callLogin=XmppCredentials(domain=recorder.meet.jitsi, username=recorder, password=passw0rd), stripFromRoomDomain=muc., usageTimeoutMins=0, trustAllXmppCerts=true)
2020-03-31 19:57:34.143 INFO: [1] org.jitsi.jibri.api.xmpp.XmppApi.start() The trustAllXmppCerts config is enabled for this domain, all XMPP server provided certificates will be accepted
2020-03-31 19:57:34.175 FINE: [19] org.jitsi.xmpp.mucclient.MucClient.log() Initializing a new MucClient for [ org.jitsi.xmpp.mucclient.MucClientConfiguration id=xmpp.meet.jitsi domain=auth.meet.jitsi hostname=xmpp.meet.jitsi username=jibri mucs=[jibribrewery@internal-muc.meet.jitsi] mucNickname=jibri-instanse-687780510 disableCertificateVerification=true]
2020-03-31 19:57:34.234 WARNING: [19] org.jitsi.xmpp.mucclient.MucClient.log() Disabling certificate verification!
2020-03-31 19:57:34.315 WARNING: [1] org.glassfish.jersey.internal.inject.Providers.checkProviderRuntime() A provider org.jitsi.jibri.api.http.HttpApi registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider org.jitsi.jibri.api.http.HttpApi will be ignored. 
2020-03-31 19:57:34.331 FINE: [19] org.jitsi.xmpp.mucclient.MucClient.log() [MucClient id=xmpp.meet.jitsi hostname=xmpp.meet.jitsi] about to connect and login.
2020-03-31 19:57:34.929 INFO: [19] org.jitsi.xmpp.mucclient.MucClient.log() [MucClient id=xmpp.meet.jitsi hostname=xmpp.meet.jitsi] connected
2020-03-31 19:57:35.059 FINE: [19] org.jitsi.xmpp.mucclient.MucClient.log() [MucClient id=xmpp.meet.jitsi hostname=xmpp.meet.jitsi] authenticated, b=false
2020-03-31 19:57:35.065 FINE: [19] org.jitsi.xmpp.mucclient.MucClient.log() [MucClient id=xmpp.meet.jitsi hostname=xmpp.meet.jitsi] about to join MUCs.
2020-03-31 19:57:35.103 INFO: [19] org.jitsi.xmpp.mucclient.MucClient.log() Joined MUC: jibribrewery@internal-muc.meet.jitsi
2020-03-31 19:57:35.115 FINE: [30] org.jitsi.xmpp.extensions.DefaultPacketExtensionProvider.parse() Could not add a provider for element busy-status from namespace http://jitsi.org/protocol/jibri
2020-03-31 19:57:35.130 FINE: [30] org.jitsi.xmpp.extensions.DefaultPacketExtensionProvider.parse() Could not add a provider for element health-status from namespace http://jitsi.org/protocol/health

```


Log 2 

```

2020-03-31 19:52:02.981 INFO: [1] org.jitsi.jibri.Main.main() Jibri run with args [--config, /etc/jitsi/jibri/config.json]
2020-03-31 19:52:03.074 INFO: [1] org.jitsi.jibri.Main.main() Using config file /etc/jitsi/jibri/config.json
2020-03-31 19:52:03.093 INFO: [1] org.jitsi.jibri.Main.main() Using port 3333 for internal HTTP API
2020-03-31 19:52:03.093 INFO: [1] org.jitsi.jibri.Main.main() Using port 2222 for the HTTP API
2020-03-31 19:52:11.014 INFO: [1] org.jitsi.jibri.Main.loadConfig() Parsed config:
JibriConfig(recordingDirectory=/config/recordings, singleUseMode=false, enabledStatsD=true, finalizeRecordingScriptPath=/config/finalize.sh, xmppEnvironments=[XmppEnvironmentConfig(name=prod environment, xmppServerHosts=[xmpp.meet.jitsi], xmppDomain=meet.jitsi, controlLogin=XmppCredentials(domain=auth.meet.jitsi, username=jibri, password=passw0rd), controlMuc=XmppMuc(domain=internal-muc.meet.jitsi, roomName=jibribrewery, nickname=jibri-instanse-499574081), sipControlMuc=null, callLogin=XmppCredentials(domain=recorder.meet.jitsi, username=recorder, password=passw0rd), stripFromRoomDomain=muc., usageTimeoutMins=0, trustAllXmppCerts=true)])
2020-03-31 19:52:12.706 WARNING: [1] org.glassfish.jersey.internal.inject.Providers.checkProviderRuntime() A provider org.jitsi.jibri.api.http.internal.InternalHttpApi registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider org.jitsi.jibri.api.http.internal.InternalHttpApi will be ignored. 
2020-03-31 19:52:13.314 INFO: [1] org.jitsi.jibri.api.xmpp.XmppApi.updatePresence() Jibri reports its status is now JibriStatus(busyStatus=IDLE, health=OverallHealth(healthStatus=HEALTHY, details={})), publishing presence to connections
2020-03-31 19:52:13.317 INFO: [1] org.jitsi.xmpp.mucclient.MucClientManager.log() Setting a presence extension: org.jitsi.xmpp.extensions.jibri.JibriStatusPacketExt@771158fb
2020-03-31 19:52:13.329 INFO: [1] org.jitsi.jibri.api.xmpp.XmppApi.start() Connecting to xmpp environment on xmpp.meet.jitsi with config XmppEnvironmentConfig(name=prod environment, xmppServerHosts=[xmpp.meet.jitsi], xmppDomain=meet.jitsi, controlLogin=XmppCredentials(domain=auth.meet.jitsi, username=jibri, password=passw0rd), controlMuc=XmppMuc(domain=internal-muc.meet.jitsi, roomName=jibribrewery, nickname=jibri-instanse-499574081), sipControlMuc=null, callLogin=XmppCredentials(domain=recorder.meet.jitsi, username=recorder, password=passw0rd), stripFromRoomDomain=muc., usageTimeoutMins=0, trustAllXmppCerts=true)
2020-03-31 19:52:13.335 INFO: [1] org.jitsi.jibri.api.xmpp.XmppApi.start() The trustAllXmppCerts config is enabled for this domain, all XMPP server provided certificates will be accepted
2020-03-31 19:52:13.371 FINE: [19] org.jitsi.xmpp.mucclient.MucClient.log() Initializing a new MucClient for [ org.jitsi.xmpp.mucclient.MucClientConfiguration id=xmpp.meet.jitsi domain=auth.meet.jitsi hostname=xmpp.meet.jitsi username=jibri mucs=[jibribrewery@internal-muc.meet.jitsi] mucNickname=jibri-instanse-499574081 disableCertificateVerification=true]
2020-03-31 19:52:13.421 WARNING: [19] org.jitsi.xmpp.mucclient.MucClient.log() Disabling certificate verification!
2020-03-31 19:52:13.523 FINE: [19] org.jitsi.xmpp.mucclient.MucClient.log() [MucClient id=xmpp.meet.jitsi hostname=xmpp.meet.jitsi] about to connect and login.
2020-03-31 19:52:13.538 WARNING: [1] org.glassfish.jersey.internal.inject.Providers.checkProviderRuntime() A provider org.jitsi.jibri.api.http.HttpApi registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider org.jitsi.jibri.api.http.HttpApi will be ignored. 
2020-03-31 19:52:14.020 INFO: [19] org.jitsi.xmpp.mucclient.MucClient.log() [MucClient id=xmpp.meet.jitsi hostname=xmpp.meet.jitsi] connected
2020-03-31 19:52:14.173 FINE: [19] org.jitsi.xmpp.mucclient.MucClient.log() [MucClient id=xmpp.meet.jitsi hostname=xmpp.meet.jitsi] authenticated, b=false
2020-03-31 19:52:14.186 FINE: [19] org.jitsi.xmpp.mucclient.MucClient.log() [MucClient id=xmpp.meet.jitsi hostname=xmpp.meet.jitsi] about to join MUCs.
2020-03-31 19:52:14.221 INFO: [19] org.jitsi.xmpp.mucclient.MucClient.log() Joined MUC: jibribrewery@internal-muc.meet.jitsi
2020-03-31 19:52:14.230 FINE: [30] org.jitsi.xmpp.extensions.DefaultPacketExtensionProvider.parse() Could not add a provider for element busy-status from namespace http://jitsi.org/protocol/jibri
2020-03-31 19:52:14.237 FINE: [30] org.jitsi.xmpp.extensions.DefaultPacketExtensionProvider.parse() Could not add a provider for element health-status from namespace http://jitsi.org/protocol/health
2020-03-31 19:56:57.190 WARNING: [30] org.jivesoftware.smack.AbstractXMPPConnection.callConnectionClosedOnErrorListener() Connection XMPPTCPConnection[jibri@auth.meet.jitsi/yS8kA7u3] (0) closed with error
org.jivesoftware.smack.XMPPException$StreamErrorException: system-shutdown You can read more about the meaning of this stream error at http://xmpp.org/rfcs/rfc6120.html#streams-error-conditions
<stream:error><system-shutdown xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text>Received SIGTERM</text></stream:error>
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1064)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:1000)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1016)
	at java.lang.Thread.run(Thread.java:748)
2020-03-31 19:56:57.195 INFO: [30] org.jitsi.xmpp.mucclient.MucClient.log() [MucClient id=xmpp.meet.jitsi hostname=xmpp.meet.jitsi] closed on error:
org.jivesoftware.smack.XMPPException$StreamErrorException: system-shutdown You can read more about the meaning of this stream error at http://xmpp.org/rfcs/rfc6120.html#streams-error-conditions
<stream:error><system-shutdown xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text>Received SIGTERM</text></stream:error>
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1064)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:1000)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1016)
	at java.lang.Thread.run(Thread.java:748)
2020-03-31 19:56:58.200 FINE: [43] org.jitsi.xmpp.mucclient.MucClient.log() [MucClient id=xmpp.meet.jitsi hostname=xmpp.meet.jitsi] reconnecting in 8
2020-03-31 19:56:59.201 FINE: [43] org.jitsi.xmpp.mucclient.MucClient.log() [MucClient id=xmpp.meet.jitsi hostname=xmpp.meet.jitsi] reconnecting in 7
2020-03-31 19:57:00.203 FINE: [43] org.jitsi.xmpp.mucclient.MucClient.log() [MucClient id=xmpp.meet.jitsi hostname=xmpp.meet.jitsi] reconnecting in 6
2020-03-31 19:57:01.210 FINE: [43] org.jitsi.xmpp.mucclient.MucClient.log() [MucClient id=xmpp.meet.jitsi hostname=xmpp.meet.jitsi] reconnecting in 5
2020-03-31 19:57:02.213 FINE: [43] org.jitsi.xmpp.mucclient.MucClient.log() [MucClient id=xmpp.meet.jitsi hostname=xmpp.meet.jitsi] reconnecting in 4
2020-03-31 19:57:03.216 FINE: [43] org.jitsi.xmpp.mucclient.MucClient.log() [MucClient id=xmpp.meet.jitsi hostname=xmpp.meet.jitsi] reconnecting in 3
2020-03-31 19:57:04.217 FINE: [43] org.jitsi.xmpp.mucclient.MucClient.log() [MucClient id=xmpp.meet.jitsi hostname=xmpp.meet.jitsi] reconnecting in 2
2020-03-31 19:57:05.219 FINE: [43] org.jitsi.xmpp.mucclient.MucClient.log() [MucClient id=xmpp.meet.jitsi hostname=xmpp.meet.jitsi] reconnecting in 1
2020-03-31 19:57:06.220 FINE: [43] org.jitsi.xmpp.mucclient.MucClient.log() [MucClient id=xmpp.meet.jitsi hostname=xmpp.meet.jitsi] reconnecting in 0
2020-03-31 19:57:06.221 FINE: [43] org.jitsi.xmpp.mucclient.MucClient.log() [MucClient id=xmpp.meet.jitsi hostname=xmpp.meet.jitsi] reconnecting in 0
2020-03-31 19:57:06.238 INFO: [43] org.jitsi.xmpp.mucclient.MucClient.log() [MucClient id=xmpp.meet.jitsi hostname=xmpp.meet.jitsi] reconnection failed

```

**Comment by morphles** [comment]
Did you start jibri container?
you need to do 
`docker-compose -f docker-compose.yml -f jibri.yml up`
That is you need to explicitly list compose files as jibri container is defined in separate file.

**Comment by hmharshit** [comment]
Have you enabled the options in the interface_config.js file?

**Comment by soletan** [comment]
Basically running into similar issue, at least my log file of Jibri container looks very similar to the one posted first in second comment. And yes, this one is caused by Jibri container, for I was listing jibri.yml when starting the composition.

FWIW: I'm usiing Jigasi as well and there is authentication enabled.

@hmharshit Is this file some internal file? For I can't remember it has been listed as part of setup guide for using Jibri.

**Comment by hmharshit** [comment]
@soletan Does the recording and streaming option not available in the web UI to you?

**Comment by soletan** [comment]
precisely. The Jibri is running and its claiming to have authenticated, but I can't find any control for starting recording in GUI ... I assume there should be some new option in menu available from icon in bottom-right corner ...

**Comment by hmharshit** [comment]
I think the option is the same as in [meet.jit.si](https://meet.jit.si/). 
Please check the following places on whether the option is activated or not?

1. ENABLE_RECORDING  should be equal to **1** in _.env_ file.
2. Find the web config file and check whether *liveStreamingEnabled* is set to true or not, if not, please uncomment it and set it to true.

For quick reference, you can check your config file through yourdomain.com/config.js .

**Comment by soletan** [comment]
The ENABLE_RECORDING has been set before, but I was using the setup before that already, thus I had to adjust the config.js of web manually. Now there is a button for live-streaming, but that's different from recording sessions. If I would have to stream to YouTube for that I wouldn't need to work with Jitsi instead of Teams/Skype/WebEx/zoom in the first place ...

**Comment by soletan** [comment]
But it looks like the right config.js file to play with ...

**Comment by hmharshit** [comment]
Yeah you are correct, I just wanted to check whether the recording and live stream are enabled or not because both are connected with jibri.

Just modify the config.js file for recording, rebuild the docker images and it should be working I guess then.

**Comment by soletan** [comment]
Hm, I don't know what you mean with "rebuilding docker images" for this would require some dev setup for this project, wouldn't it? And I assume this isn't required for users having issues related to this.

However, I was able to reproduce this case up to the point that this issue is mostly due to enabling recording late after having used Jitsi setup without recording enabled first. Due to configuration files not being replaced on restart of docker composition, this change of ENABLE_RECORDER hasn't been applied to the setup.

Following your hint I was able to adjust the config file **~/.jitsi-meet-cfg/web/config.js** and enable 

```
fileRecordingsEnabled: true
```

instead of the option you were referring to. Restarting conference in Chrome browser was sufficient to now reach state of what is discussed in #240.

**Comment by hmharshit** [comment]
Ahh, It's a typo, it should have been _restart _ instead of rebuild. For me, it was not working just restarting the conference in the Chrome browser. It worked after I restarted the docker containers. That's why I mentioned to restart it.
