### ISSUE TITLE
Jigasi: "Did not received session invite"

### ISSUE THREAD

**Issue by real-or-random** [jitsi/docker-jitsi-meet#367]
Trying to setup incoming SIP calls... Jigasi gets the call but then is stuck with "Did not received session invite".
```
Jigasi 2020-04-03 00:54:13.976 INFO: [433] org.jitsi.jigasi.SipGateway.incomingCallReceived().188 Incoming call received...
Jigasi 2020-04-03 00:54:13.977 INFO: [434] org.jitsi.jigasi.SipGatewaySession.run().1281 [ctx=15858680539761320436894] Wait thread cancelled
Jigasi 2020-04-03 00:54:13.978 INFO: [433] org.jitsi.jigasi.JvbConference.setXmppProvider().539 [ctx=15858680539761320436894] Using ProtocolProviderServiceJabberImpl(Jabber:6a14e534@meet.jitsi/6a14e534)
Jigasi 2020-04-03 00:54:13.981 SEVERE: [20] impl.packetlogging.PacketLoggingServiceImpl.run().845 Error writing packet to file
java.lang.SecurityException: Insufficient rights to access this file in current user's home directory: /config/log/jitsi0.pcap
	at org.jitsi.impl.fileaccess.FileAccessServiceImpl.getPrivatePersistentFile(FileAccessServiceImpl.java:171)
	at net.java.sip.communicator.impl.packetlogging.PacketLoggingServiceImpl.getFileNames(PacketLoggingServiceImpl.java:197)
	at net.java.sip.communicator.impl.packetlogging.PacketLoggingServiceImpl.savePacket(PacketLoggingServiceImpl.java:582)
	at net.java.sip.communicator.impl.packetlogging.PacketLoggingServiceImpl.access$100(PacketLoggingServiceImpl.java:35)
	at net.java.sip.communicator.impl.packetlogging.PacketLoggingServiceImpl$SaverThread.run(PacketLoggingServiceImpl.java:834)
Jigasi 2020-04-03 00:54:13.981 SEVERE: [20] impl.packetlogging.PacketLoggingServiceImpl.run().845 Error writing packet to file
java.lang.SecurityException: Insufficient rights to access this file in current user's home directory: /config/log/jitsi0.pcap
	at org.jitsi.impl.fileaccess.FileAccessServiceImpl.getPrivatePersistentFile(FileAccessServiceImpl.java:171)
	at net.java.sip.communicator.impl.packetlogging.PacketLoggingServiceImpl.getFileNames(PacketLoggingServiceImpl.java:197)
	at net.java.sip.communicator.impl.packetlogging.PacketLoggingServiceImpl.savePacket(PacketLoggingServiceImpl.java:582)
	at net.java.sip.communicator.impl.packetlogging.PacketLoggingServiceImpl.access$100(PacketLoggingServiceImpl.java:35)
	at net.java.sip.communicator.impl.packetlogging.PacketLoggingServiceImpl$SaverThread.run(PacketLoggingServiceImpl.java:834)
Jigasi 2020-04-03 00:54:14.010 INFO: [435] impl.protocol.jabber.OperationSetBasicTelephonyJabberImpl.registrationStateChanged().125 Jingle : ON 
Jigasi 2020-04-03 00:54:14.011 INFO: [435] org.jitsi.jigasi.JvbConference.registrationStateChanged().577 [ctx=15858680539761320436894] Registering XMPP.
Jigasi 2020-04-03 00:54:14.015 INFO: [435] impl.protocol.jabber.ProtocolProviderServiceJabberImpl.authenticated().2535 Authenticated: false
Jigasi 2020-04-03 00:54:14.017 INFO: [435] org.jitsi.jigasi.JvbConference.joinConferenceRoom().648 [ctx=15858680539761320436894] Joining JVB conference room: test
Jigasi 2020-04-03 00:54:14.040 INFO: [441] impl.protocol.jabber.ChatRoomJabberImpl.joined().1256 test@internal-muc.meet.jitsi/focus has joined the test@internal-muc.meet.jitsi chat room.
Jigasi 2020-04-03 00:54:30.493 INFO: [451] impl.protocol.sip.SipLogger.logInfo().196 Info from the JAIN-SIP stack: Setting SIPMessage peerPacketSource to: /3.123.246.217:5060
Jigasi 2020-04-03 00:54:44.044 SEVERE: [448] org.jitsi.jigasi.JvbConference.run().1471 [ctx=15858680539761320436894] Did not received session invite (30000 ms)
Jigasi 2020-04-03 00:54:44.045 INFO: [448] org.jitsi.jigasi.JvbConference.stop().500 [ctx=15858680539761320436894] Removing account Jabber:6a14e534@meet.jitsi/6a14e534
Jigasi 2020-04-03 00:54:44.048 INFO: [448] impl.protocol.jabber.OperationSetBasicTelephonyJabberImpl.registrationStateChanged().132 Jingle : OFF 
Jigasi 2020-04-03 00:54:44.050 INFO: [162] org.jitsi.jigasi.SipGatewaySession.handleCallState().1138 [ctx=15858680539761320436894] SIP call ended: CallPeerChangeEvent: type=CallPeerStatusChange oldV=net.java.sip.communicator.service.protocol.CallPeerState:Incoming Call newV=net.java.sip.communicator.service.protocol.CallPeerState:Failed for peer=491727012691 <anonymous@bla.voximplant.com>;status=Failed
Jigasi 2020-04-03 00:54:44.050 INFO: [162] org.jitsi.jigasi.SipGatewaySession.sipCallEnded().629 [ctx=15858680539761320436894] Sip call ended: Call: id=15858680539751145843694 peers=0
Jigasi 2020-04-03 00:54:44.051 INFO: [162] org.jitsi.jigasi.AbstractGateway.notifyCallEnded().128 [ctx=15858680539761320436894] Removed session for call. Sessions:0
Jigasi 2020-04-03 00:54:44.051 INFO: [162] org.jitsi.jigasi.SipGatewaySession.peerStateChanged().1204 null SIP peer state: Failed
```

According to the jicofo logs, the SIP caller ends up in test@internal-muc.jitsi but we (connected via web) were in test@muc.jitsi. We then (just for testing) tried to set XMPP_INTERNAL_MUC_DOMAIN and XMPP_MUC_DOMAIN to the same value. I know this is wrong -- but also I don't understand that the purpose of the two MUCs is. Then the SIP caller ended up the same room but there were other issues (call aborted after a few seconds), not sure if they were related or not.

cc @kappc

**Comment by real-or-random** [comment]
Fwiw, this was fixed by sending `X-Room-Name: test@muc.meet.jitsi` instead of just `X-Room-Name: test`.
