### ISSUE TITLE
Jibri - Failed to initialize and start a MucClient - SASLError using SCRAM-SHA-1: not-authorized

### ISSUE THREAD

**Issue by pini-gh** [jitsi/docker-jitsi-meet#396]
Hi,
I've successfully set up a basic docker-jitsi-meet configuration, and now I'd like to give a try at using the jibri service. But this one fails with:
```
2020-04-07 13:52:06.258 INFO: [20] org.jitsi.xmpp.mucclient.MucClient.log() [MucClient id=xmpp.meet.jitsi hostname=xmpp.meet.jitsi] connected
2020-04-07 13:52:06.606 SEVERE: [20] org.jitsi.xmpp.mucclient.MucClientManager.log() Failed to initialize and start a MucClient: 
org.jivesoftware.smack.sasl.SASLErrorException: SASLError using SCRAM-SHA-1: not-authorized
        at org.jivesoftware.smack.SASLAuthentication.authenticationFailed(SASLAuthentication.java:292)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1100)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:1000)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1016)
        at java.lang.Thread.run(Thread.java:748)
2020-04-07 13:52:34.734 WARNING: [29] org.jivesoftware.smackx.ping.PingManager.pingServerIfNecessary() XMPPConnection was not authenticated
2020-04-07 13:57:04.977 WARNING: [31] org.jivesoftware.smack.AbstractXMPPConnection.callConnectionClosedOnErrorListener() Connection XMPPTCPConnection[not-authenticated] (0) closed with error
org.jivesoftware.smack.XMPPException$StreamErrorException: connection-timeout You can read more about the meaning of this stream error at http://xmpp.org/rfcs/rfc6120.html#streams-error-conditions
<stream:error><connection-timeout xmlns='urn:ietf:params:xml:ns:xmpp-streams'/></stream:error>
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1064)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:1000)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1016)
        at java.lang.Thread.run(Thread.java:748)
2020-04-07 13:57:04.983 INFO: [31] org.jitsi.xmpp.mucclient.MucClient.log() [MucClient id=xmpp.meet.jitsi hostname=xmpp.meet.jitsi] closed on error:
org.jivesoftware.smack.XMPPException$StreamErrorException: connection-timeout You can read more about the meaning of this stream error at http://xmpp.org/rfcs/rfc6120.html#streams-error-conditions
<stream:error><connection-timeout xmlns='urn:ietf:params:xml:ns:xmpp-streams'/></stream:error>
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1064)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:1000)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1016)
        at java.lang.Thread.run(Thread.java:748)
2020-04-07 13:57:05.989 FINE: [33] org.jitsi.xmpp.mucclient.MucClient.log() [MucClient id=xmpp.meet.jitsi hostname=xmpp.meet.jitsi] reconnecting in 3
2020-04-07 13:57:06.992 FINE: [33] org.jitsi.xmpp.mucclient.MucClient.log() [MucClient id=xmpp.meet.jitsi hostname=xmpp.meet.jitsi] reconnecting in 2
2020-04-07 13:57:07.996 FINE: [33] org.jitsi.xmpp.mucclient.MucClient.log() [MucClient id=xmpp.meet.jitsi hostname=xmpp.meet.jitsi] reconnecting in 1
2020-04-07 13:57:08.999 FINE: [33] org.jitsi.xmpp.mucclient.MucClient.log() [MucClient id=xmpp.meet.jitsi hostname=xmpp.meet.jitsi] reconnecting in 0
2020-04-07 13:57:09.003 FINE: [33] org.jitsi.xmpp.mucclient.MucClient.log() [MucClient id=xmpp.meet.jitsi hostname=xmpp.meet.jitsi] reconnecting in 0
2020-04-07 13:57:09.276 INFO: [33] org.jitsi.xmpp.mucclient.MucClient.log() [MucClient id=xmpp.meet.jitsi hostname=xmpp.meet.jitsi] connected
2020-04-07 13:57:09.452 INFO: [33] org.jitsi.xmpp.mucclient.MucClient.log() [MucClient id=xmpp.meet.jitsi hostname=xmpp.meet.jitsi] reconnection failed
```
Any help appreciated.
Thanks.

**Comment by saghul** [comment]
Have you changed your .env file *after* crearting the containers for the first time?

**Comment by pini-gh** [comment]
Oh, you're right indeed. The error is gone after dropping the persistent data.
BTW, I've read this on a Docker forum:
> Persisting data across runs is really the only reason to use volumes. If
> you don't want persisted data why are you putting it in a volume?

Then, with using volumes in docker-jitsi-meet if we have to drop all persistent data after any configuration change?
Thanks.

**Comment by GuillaumeOuint** [comment]
I'm using Jitsi meet statelessly on k8s and I have this problem too, containers are created with the pod with ENV var attached, I don't have /config volume for stateless state and its seems that jicofo doesn't generate /config/config with ENV parameters and use the default /etc/jitsi/jicofo/config that doesn't contains custom config (passwords, username, domain).

**Comment by GuillaumeOuint** [comment]
On my side, this is not an error with Jibri but with Jicofo (jvb cannot auth, p2p works, but 3 users and no video/audio)
This is my error:

> 2020-04-07T13:01:25.98864656Z Jicofo 2020-04-07 15:01:25.987 SEVERE: [67] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.doConnect().309 Failed to connect/login: SASLError using SCRAM-SHA-1: not-authorized
2020-04-07T13:01:25.988710491Z org.jivesoftware.smack.sasl.SASLErrorException: SASLError using SCRAM-SHA-1: not-authorized
2020-04-07T13:01:25.988728837Z 	at org.jivesoftware.smack.SASLAuthentication.authenticationFailed(SASLAuthentication.java:292)
2020-04-07T13:01:25.98874585Z 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1100)
2020-04-07T13:01:25.988762482Z 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:1000)
2020-04-07T13:01:25.988779224Z 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1016)
2020-04-07T13:01:25.988795776Z 	at java.lang.Thread.run(Thread.java:748)

**Comment by pini-gh** [comment]
I'm now running stateless too (keeping only one volume for transcripts), and I don't see this problem.
Maybe force a new container creation with:
```
$ docker-compose stop
$ docker-compose rm
$ docker-compose up -d
```

**Comment by saghul** [comment]
Tentatively closing.
