### ISSUE TITLE
vanilla install (ton of errors in docker logs)

### ISSUE THREAD

**Issue by chovy** [jitsi/docker-jitsi-meet#439]
I don't know if this is normal or if I have to open up any ports on my firewall or what.

I changed what seemed to be the defaults for a few things in .env

nothing else.

```
rosody_1_468b6fc145cd | c2s55fd60ced0b0             info       Client connected
prosody_1_468b6fc145cd | c2s55fd60ced0b0             info       Stream encrypted (TLSv1.2 with ECDHE-RSA-AES256-GCM-SHA384)
jicofo_1_c2be4020d5fa | Jicofo 2020-04-12 10:47:32.917 SEVERE: [43] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.doConnect().315 Failed to connect/login: SASLError using SCRAM-SHA-1: not-authorized
jicofo_1_c2be4020d5fa | org.jivesoftware.smack.sasl.SASLErrorException: SASLError using SCRAM-SHA-1: not-authorized
jicofo_1_c2be4020d5fa |         at org.jivesoftware.smack.SASLAuthentication.authenticationFailed(SASLAuthentication.java:292)
jicofo_1_c2be4020d5fa |         at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1100)
jicofo_1_c2be4020d5fa |         at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:1000)
jicofo_1_c2be4020d5fa |         at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1016)
jicofo_1_c2be4020d5fa |         at java.lang.Thread.run(Thread.java:748)
prosody_1_468b6fc145cd | c2s55fd60ced0b0             info       Client disconnected: connection closed
web_1_c53cdcd3382e | nginx: [emerg] PEM_read_bio_DHparams("/config/nginx/dhparams.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: DH PARAMETERS)
prosody_1_468b6fc145cd | c2s55fd602923d0             info       Client disconnected: connection closed
jvb_1_182be9920bf8 | Apr 12, 2020 10:47:33 AM org.jivesoftware.smack.AbstractXMPPConnection callConnectionClosedOnErrorListener
jvb_1_182be9920bf8 | WARNING: Connection XMPPTCPConnection[not-authenticated] (0) closed with error
jvb_1_182be9920bf8 | org.jivesoftware.smack.XMPPException$StreamErrorException: connection-timeout You can read more about the meaning of this stream error at http://xmpp.org/rfcs/rfc6120.html#streams-error-conditions
jvb_1_182be9920bf8 | <stream:error><connection-timeout xmlns='urn:ietf:params:xml:ns:xmpp-streams'/></stream:error>
jvb_1_182be9920bf8 |    at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1064)
jvb_1_182be9920bf8 |    at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:1000)
jvb_1_182be9920bf8 |    at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1016)
jvb_1_182be9920bf8 |    at java.lang.Thread.run(Thread.java:748)
jvb_1_182be9920bf8 | 
jvb_1_182be9920bf8 | Apr 12, 2020 10:47:33 AM org.jitsi.utils.logging2.LoggerImpl log
jvb_1_182be9920bf8 | WARNING: Closed on error:
jvb_1_182be9920bf8 | org.jivesoftware.smack.XMPPException$StreamErrorException: connection-timeout You can read more about the meaning of this stream error at http://xmpp.org/rfcs/rfc6120.html#streams-error-conditions
jvb_1_182be9920bf8 | <stream:error><connection-timeout xmlns='urn:ietf:params:xml:ns:xmpp-streams'/></stream:error>
jvb_1_182be9920bf8 |    at org.jivesoftware.smack.tcp.XMPPTCPConnection$Packe
```

**Comment by saghul** [comment]
What image versions are you running? can you please share your .env file?

**Comment by chovy** [comment]
https://gist.github.com/chovy/b07f35a80345bec5529e7f37655b6b13

I'm using your docker compose file here.

**Comment by saghul** [comment]
Did you pull the latest images?

**Comment by albeethekid** [comment]
Seeing at least a few of those errors as well.  I followed the steps here: 
https://github.com/jitsi/docker-jitsi-meet/blob/master/README.md#quick-start

What needs doin?!

**Comment by kivi** [comment]
Similar here. On Docker installed on Windows as well as on Linux. Followed the steps according quick-start.

```Java
SEVERE: org.jivesoftware.smack.sasl.SASLErrorException: SASLError using SCRAM-SHA-1: not-authorized
org.jivesoftware.smack.sasl.SASLErrorException: SASLError using SCRAM-SHA-1: not-authorized
        at org.jivesoftware.smack.SASLAuthentication.authenticationFailed(SASLAuthentication.java:292)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1100)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:1000)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1016)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by MalteBiermann** [comment]
+1

**Comment by saghul** [comment]
Have you updated the images with docker-compose pull?

**Comment by MalteBiermann** [comment]
Yes, I did do a docker-compose pull. Also fresh git clone today.
Followed the Quick Start steps.
my .env: https://pastebin.com/iQkDPzqA
docker-compose out: https://pastebin.com/G8uV3HXa
Any ideas?

**Comment by nischay-dhiman** [comment]
Facing same issue after normal docker-compose up:

`jcp55bc21e31670             info	Incoming Jabber component connection
prosody_1  | focus.meet.jitsi:component  info	Component authentication failed for focus.meet.jitsi
jicofo_1   | Jicofo 2020-04-23 19:46:12.425 SEVERE: [34] org.jitsi.meet.ComponentMain.log() not-authorized, host:xmpp.meet.jitsi, port:5347
jicofo_1   | org.xmpp.component.ComponentException: not-authorized
jicofo_1   | 	at org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:243)
jicofo_1   | 	at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:242)
jicofo_1   | 	at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:222)
jicofo_1   | 	at org.jitsi.meet.ComponentMain.lambda$getConnectCallable$0(ComponentMain.java:285)
jicofo_1   | 	at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
jicofo_1   | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
jicofo_1   | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
jicofo_1   | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
jicofo_1   | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
jicofo_1   | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
jicofo_1   | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
jicofo_1   | 	at java.lang.Thread.run(Thread.java:748)
prosody_1  | mod_component               info	Disconnecting component, <stream:error> is: <stream:error><not-authorized xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text xmlns='urn:ietf:params:xml:ns:xmpp-streams'>Given token does not match calculated token</text></stream:error>
prosody_1  | jcp55bc21e31670             info	component disconnected: focus.meet.jitsi (stream error)
jvb_1      | Apr 23, 2020 7:46:13 PM org.jitsi.utils.logging2.LoggerImpl log
jvb_1      | INFO: create_conf, id=dbba52cf0dafcb26 gid=null logging=false
jvb_1      | Apr 23, 2020 7:46:14 PM org.jitsi.utils.logging2.LoggerImpl log
jvb_1      | INFO: Performed a successful health check in 13ms. Sticky failure: false
prosody_1  | c2s55bc21e49ad0             info	Client connected
prosody_1  | c2s55bc21e49ad0             info	Stream encrypted (TLSv1.2 with ECDHE-RSA-AES256-GCM-SHA384)
jicofo_1   | Jicofo 2020-04-23 19:46:15.668 SEVERE: [64] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.doConnect().315 Failed to connect/login: SASLError using SCRAM-SHA-1: not-authorized
jicofo_1   | org.jivesoftware.smack.sasl.SASLErrorException: SASLError using SCRAM-SHA-1: not-authorized
jicofo_1   | 	at org.jivesoftware.smack.SASLAuthentication.authenticationFailed(SASLAuthentication.java:292)
jicofo_1   | 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1100)
jicofo_1   | 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:1000)
jicofo_1   | 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1016)
jicofo_1   | 	at java.lang.Thread.run(Thread.java:748)
prosody_1  | c2s55bc21e49ad0             info	Client disconnected: connection closed
jvb_1      | Apr 23, 2020 7:46:16 PM org.jitsi.utils.logging2.LoggerImpl log
jvb_1      | INFO: Logging in.
jvb_1      | Apr 23, 2020 7:46:16 PM org.jitsi.utils.logging.LoggerImpl log
jvb_1      | SEVERE: org.jivesoftware.smack.sasl.SASLErrorException: SASLError using SCRAM-SHA-1: not-authorized
jvb_1      | org.jivesoftware.smack.sasl.SASLErrorException: SASLError using SCRAM-SHA-1: not-authorized
jvb_1      | 	at org.jivesoftware.smack.SASLAuthentication.authenticationFailed(SASLAuthentication.java:292)
jvb_1      | 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1100)
jvb_1      | 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:1000)
jvb_1      | 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1016)
jvb_1      | 	at java.lang.Thread.run(Thread.java:748)
jvb_1      |`

**Comment by jhammons** [comment]
Someone has discovered what is wrong and very helpfully explained it here: https://community.jitsi.org/t/help-regarding-failing-docker-based-setup/33658/5

**Comment by MalteBiermann** [comment]
Deleting ~/.jitsi-meet-cfg solved my issue.
