### ISSUE TITLE
jigasi + ldap auth not working out of the box

### ISSUE THREAD

**Issue by creativeguitar** [jitsi/docker-jitsi-meet#500]
Jigasi works when auth is turned off.
If I turn on ldap auth, then I get the following error

```
jigasi_1   | Jigasi 2020-04-21 13:50:36.475 INFO: [75] org.jitsi.jigasi.SipGateway.incomingCallReceived().188 Incoming call received...
jigasi_1   | Jigasi 2020-04-21 13:50:37.480 INFO: [76] org.jitsi.jigasi.SipGatewaySession.run().1295 [ctx=1587495036476430832605]Using default JVB room name property siptest
jigasi_1   | Jigasi 2020-04-21 13:50:37.486 INFO: [76] org.jitsi.jigasi.JvbConference.setXmppProvider().539 [ctx=1587495036476430832605] Using ProtocolProviderServiceJabberImpl(Jabber:3979586d@meet.jitsi/3979586d)
jigasi_1   | Jigasi 2020-04-21 13:50:37.558 INFO: [78] impl.protocol.jabber.OperationSetBasicTelephonyJabberImpl.registrationStateChanged().125 Jingle : ON
jigasi_1   | Jigasi 2020-04-21 13:50:37.558 INFO: [78] org.jitsi.jigasi.JvbConference.registrationStateChanged().577 [ctx=1587495036476430832605] Registering XMPP.
jigasi_1   | Jigasi 2020-04-21 13:50:37.577 INFO: [78] impl.protocol.jabber.ProtocolProviderServiceJabberImpl.authenticated().2535 Authenticated: false
jigasi_1   | Jigasi 2020-04-21 13:50:37.579 INFO: [78] org.jitsi.jigasi.JvbConference.joinConferenceRoom().648 [ctx=1587495036476430832605] Joining JVB conference room: siptest
jigasi_1   | Jigasi 2020-04-21 13:50:37.584 SEVERE: [78] org.jitsi.jigasi.JvbConference.joinConferenceRoom().760 [ctx=1587495036476430832605]java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
jigasi_1   | java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
jigasi_1   |    at java.util.ArrayList.rangeCheck(ArrayList.java:657)
jigasi_1   |    at java.util.ArrayList.get(ArrayList.java:433)
jigasi_1   |    at net.java.sip.communicator.impl.protocol.jabber.OperationSetMultiUserChatJabberImpl.getCanonicalRoomName(OperationSetMultiUserChatJabberImpl.java:658)
jigasi_1   |    at net.java.sip.communicator.impl.protocol.jabber.OperationSetMultiUserChatJabberImpl.findRoom(OperationSetMultiUserChatJabberImpl.java:316)
jigasi_1   |    at org.jitsi.jigasi.JvbConference.joinConferenceRoom(JvbConference.java:650)
jigasi_1   |    at org.jitsi.jigasi.JvbConference.registrationStateChanged(JvbConference.java:569)
jigasi_1   |    at net.java.sip.communicator.service.protocol.AbstractProtocolProviderService.fireRegistrationStateChanged(AbstractProtocolProviderService.java:187)
jigasi_1   |    at net.java.sip.communicator.service.protocol.AbstractProtocolProviderService.fireRegistrationStateChanged(AbstractProtocolProviderService.java:141)
jigasi_1   |    at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.connectAndLogin(ProtocolProviderServiceJabberImpl.java:1389)
jigasi_1   |    at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.connectAndLogin(ProtocolProviderServiceJabberImpl.java:970)
jigasi_1   |    at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.initializeConnectAndLogin(ProtocolProviderServiceJabberImpl.java:795)
jigasi_1   |    at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.register(ProtocolProviderServiceJabberImpl.java:500)
jigasi_1   |    at org.jitsi.jigasi.util.RegisterThread.run(RegisterThread.java:59)
jigasi_1   | Jigasi 2020-04-21 13:50:37.587 INFO: [78] org.jitsi.jigasi.JvbConference.stop().500 [ctx=1587495036476430832605] Removing account Jabber:3979586d@meet.jitsi/3979586d
jigasi_1   | Jigasi 2020-04-21 13:50:37.595 WARNING: [84] org.jivesoftware.smack.AbstractXMPPConnection.run() Exception while sending response to IQ request
jigasi_1   | org.jivesoftware.smack.SmackException$NotConnectedException: The connection XMPPTCPConnection[jigasi@auth.meet.jitsi/3979586d] (1) is no longer connected. done=true smResumptionPossible=false
jigasi_1   |    at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketWriter.throwNotConnectedExceptionIfDoneAndResumptionNotPossible(XMPPTCPConnection.java:1327)
jigasi_1   |    at org.jivesoftware.smack.tcp.XMPPTCPConnection.throwNotConnectedExceptionIfAppropriate(XMPPTCPConnection.java:358)
jigasi_1   |    at org.jivesoftware.smack.AbstractXMPPConnection.sendStanza(AbstractXMPPConnection.java:670)
jigasi_1   |    at org.jivesoftware.smack.AbstractXMPPConnection$4.run(AbstractXMPPConnection.java:1198)
jigasi_1   |    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
jigasi_1   |    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
jigasi_1   |    at java.lang.Thread.run(Thread.java:748)
jigasi_1   | Jigasi 2020-04-21 13:50:37.613 INFO: [78] impl.protocol.jabber.OperationSetBasicTelephonyJabberImpl.registrationStateChanged().132 Jingle : OFF
jigasi_1   | Jigasi 2020-04-21 13:50:37.622 INFO: [90] org.jitsi.jigasi.SipGatewaySession.handleCallState().1138 [ctx=1587495036476430832605] SIP call ended: CallPeerChangeEvent: type=CallPeerStatusChange oldV=net.java.sip.communicator.service.protocol.CallPeerState:Incoming Call newV=net.java.sip.communicator.service.protocol.CallPeerState:Failed for peer=9729956001 <9729956001@10.180.69.241>;status=Failed
jigasi_1   | Jigasi 2020-04-21 13:50:37.622 INFO: [90] org.jitsi.jigasi.SipGatewaySession.sipCallEnded().629 [ctx=1587495036476430832605] Sip call ended: Call: id=1587495036435168372966 peers=0
jigasi_1   | Jigasi 2020-04-21 13:50:37.623 SEVERE: [90] org.jitsi.jigasi.AbstractGateway.notifyCallEnded().120 [ctx=1587495036476430832605] Call resource not exists for session.
jigasi_1   | Jigasi 2020-04-21 13:50:37.624 INFO: [90] org.jitsi.jigasi.SipGatewaySession.peerStateChanged().1204 null SIP peer state: Failed
```

**Comment by creativeguitar** [comment]
here is the log without ldap

```
jigasi_1   | Jigasi 2020-04-21 14:02:59.758 INFO: [80] org.jitsi.jigasi.JvbConference.joinConferenceRoom().648 [ctx=1587495778669388824477] Joining JVB conference room: siptest
jigasi_1   | Jigasi 2020-04-21 14:02:59.799 INFO: [85] impl.protocol.jabber.ChatRoomJabberImpl.joined().1256 siptest@internal-muc.meet.jitsi/focus has joined the siptest@internal-muc.meet.jitsi chat room.
```

it looks like index goes out of bounce with the following line when ldap auth is on. 
**siptest@internal-muc.meet.jits**

**Comment by creativeguitar** [comment]
Adding this line to jigasi sip-communicator.properties fixed my issue

org.jitsi.jigasi.MUC_SERVICE_ADDRESS=muc.meet.jitsi
