### ISSUE TITLE
[JIGASI] HELP :)

### ISSUE THREAD

**Issue by nyok92** [jitsi/docker-jitsi-meet#536]
Hi, 
I think i managed to get jigasi working with my sip provider.
Now i try to make inbound and outbound calls to another sip account: try to connect from an sip softphone to my webconference but it doesn't work.

I'v read a lot on forums but can't find really my answers:
Is ther a button on a conference where i can call/add a sip client to the current meeting ? Like the + button ( which i think is reserved to call real numbers through our sip provider: the one connected to jigasi)

When this setup is finally working, I want to make the transcriber working with google speech to text API.
When I click on the CC button (Transcriber get in my conference) but i've got an error with the google credentials.

Here are the log from JIGASI: 
Thanks for any help/advise !

'''
Jigasi 2020-04-29 20:18:13.272 WARNING: [169] org.jitsi.jigasi.transcription.GoogleCloudTranscriptionService.log() Google Credentials are not properly set,
java.io.IOException: Error reading credential file from environment variable GOOGLE_APPLICATION_CREDENTIALS, value '/config/key.json': Invalid PKCS#8 data.,
	at com.google.auth.oauth2.DefaultCredentialsProvider.getDefaultCredentialsUnsynchronized(DefaultCredentialsProvider.java:162),
	at com.google.auth.oauth2.GoogleCredentials.getApplicationDefault(GoogleCredentials.java:113),
	at com.google.auth.oauth2.DefaultCredentialsProvider.getDefaultCredentials(DefaultCredentialsProvider.java:126),
	at com.google.auth.oauth2.GoogleCredentials.getApplicationDefault(GoogleCredentials.java:85),
	at org.jitsi.jigasi.transcription.GoogleCloudTranscriptionService.isConfiguredProperly(GoogleCloudTranscriptionService.java:302),
	at org.jitsi.jigasi.TranscriptionGatewaySession.onConferenceCallStarted(TranscriptionGatewaySession.java:181),
	at org.jitsi.jigasi.TranscriptionGatewaySession.onConferenceCallInvited(TranscriptionGatewaySession.java:163),
	at org.jitsi.jigasi.JvbConference$JvbCallListener.incomingCallReceived(JvbConference.java:1134),
	at net.java.sip.communicator.service.protocol.media.AbstractOperationSetBasicTelephony.fireCallEvent(AbstractOperationSetBasicTelephony.java:208),
	at net.java.sip.communicator.service.protocol.media.AbstractOperationSetBasicTelephony.fireCallEvent(AbstractOperationSetBasicTelephony.java:167),
	at net.java.sip.communicator.impl.protocol.jabber.CallJabberImpl.processSessionInitiate(CallJabberImpl.java:1135),
	at net.java.sip.communicator.impl.protocol.jabber.OperationSetBasicTelephonyJabberImpl$2.run(OperationSetBasicTelephonyJabberImpl.java:1136),
Caused by: java.io.IOException: Invalid PKCS#8 data.,
	at com.google.auth.oauth2.ServiceAccountCredentials.privateKeyFromPkcs8(ServiceAccountCredentials.java:323),
	at com.google.auth.oauth2.ServiceAccountCredentials.fromPkcs8(ServiceAccountCredentials.java:305),
	at com.google.auth.oauth2.ServiceAccountCredentials.fromJson(ServiceAccountCredentials.java:183),
	at com.google.auth.oauth2.GoogleCredentials.fromStream(GoogleCredentials.java:160),
	at com.google.auth.oauth2.DefaultCredentialsProvider.getDefaultCredentialsUnsynchronized(DefaultCredentialsProvider.java:156),
	... 11 more,
Jigasi 2020-04-29 20:18:13.273 WARNING: [169] org.jitsi.jigasi.TranscriptionGatewaySession.log() TranscriptionService is not properly configured
'''

**Comment by Echolon** [comment]
@nyok92 can you provide a decent title please?

Anyway, thanks for reporting!
