### ISSUE TITLE
Message "Unfortunately" after authorizing the use webcam and microphone

### ISSUE THREAD

**Issue by profe-jacm** [jitsi/docker-jitsi-meet#543]
Hi, I just installed jitsi, but can't get it to work. Open the page to create a new room and when you enter the room just after authorizing the use of the webcam and the microphone, the error "Unfortunately,  ....."

I need help..

**Comment by saghul** [comment]
Please provide logs for all containers and the JS browser console.

**Comment by anoskar** [comment]
Dear,
I have the same problem. Please from enclose logs :
 
### **jitsi/jicofo:latest**

`Jicofo 2020-05-07 22:17:07.005 SEVERE: [39] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.doConnect().315 Failed to connect/login: SASLError using SCRAM-SHA-1: not-authorized
org.jivesoftware.smack.sasl.SASLErrorException: SASLError using SCRAM-SHA-1: not-authorized
        at org.jivesoftware.smack.SASLAuthentication.authenticationFailed(SASLAuthentication.java:292)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1100)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:1000)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1016)
        at java.lang.Thread.run(Thread.java:748)
Jicofo 2020-05-07 22:17:10.945 SEVERE: [33] org.jitsi.meet.ComponentMain.log() not-authorized, host:xmpp.meet.jitsi, port:5347
org.xmpp.component.ComponentException: not-authorized
        at org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:243)
        at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:242)
        at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:222)
        at org.jitsi.meet.ComponentMain.lambda$getConnectCallable$0(ComponentMain.java:285)
        at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Jicofo 2020-05-07 22:17:12.075 SEVERE: [39] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.doConnect().315 Failed to connect/login: SASLError using SCRAM-SHA-1: not-authorized
org.jivesoftware.smack.sasl.SASLErrorException: SASLError using SCRAM-SHA-1: not-authorized
        at org.jivesoftware.smack.SASLAuthentication.authenticationFailed(SASLAuthentication.java:292)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1100)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:1000)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1016)
        at java.lang.Thread.run(Thread.java:748)
`


### **jitsi/jvb:latest**


`May 07, 2020 10:18:36 PM org.jitsi.utils.logging2.LoggerImpl log
INFO: create_conf, id=54aab319e240c3ca gid=null logging=false
May 07, 2020 10:18:36 PM org.jitsi.utils.logging2.LoggerImpl log
INFO: Performed a successful health check in 9ms. Sticky failure: false
May 07, 2020 10:18:40 PM org.jitsi.utils.logging2.LoggerImpl log
INFO: Logging in.
May 07, 2020 10:18:40 PM org.jitsi.utils.logging.LoggerImpl log
SEVERE: org.jivesoftware.smack.sasl.SASLErrorException: SASLError using SCRAM-SHA-1: not-authorized
org.jivesoftware.smack.sasl.SASLErrorException: SASLError using SCRAM-SHA-1: not-authorized
        at org.jivesoftware.smack.SASLAuthentication.authenticationFailed(SASLAuthentication.java:292)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1100)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:1000)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1016)
        at java.lang.Thread.run(Thread.java:748)

May 07, 2020 10:18:45 PM org.jitsi.utils.logging2.LoggerImpl log
INFO: Logging in.
May 07, 2020 10:18:45 PM org.jitsi.utils.logging.LoggerImpl log
SEVERE: org.jivesoftware.smack.sasl.SASLErrorException: SASLError using SCRAM-SHA-1: not-authorized
org.jivesoftware.smack.sasl.SASLErrorException: SASLError using SCRAM-SHA-1: not-authorized
        at org.jivesoftware.smack.SASLAuthentication.authenticationFailed(SASLAuthentication.java:292)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1100)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:1000)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1016)
        at java.lang.Thread.run(Thread.java:748)

May 07, 2020 10:18:46 PM org.jitsi.utils.logging2.LoggerImpl log
INFO: create_conf, id=5af8503a7e45397 gid=null logging=false
May 07, 2020 10:18:46 PM org.jitsi.utils.logging2.LoggerImpl log
INFO: Performed a successful health check in 10ms. Sticky failure: false
May 07, 2020 10:18:50 PM org.jitsi.utils.logging2.LoggerImpl log
INFO: Logging in.
May 07, 2020 10:18:50 PM org.jitsi.utils.logging.LoggerImpl log
SEVERE: org.jivesoftware.smack.sasl.SASLErrorException: SASLError using SCRAM-SHA-1: not-authorized
org.jivesoftware.smack.sasl.SASLErrorException: SASLError using SCRAM-SHA-1: not-authorized
        at org.jivesoftware.smack.SASLAuthentication.authenticationFailed(SASLAuthentication.java:292)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1100)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:1000)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1016)
        at java.lang.Thread.run(Thread.java:748)
`


### **jitsi/prosody:latest** 

`lculated token</text></stream:error>
jcp5618efbaf170             info        component disconnected: focus.meet.jitsi (stream error)
c2s5618efbc74e0             info        Client connected
c2s5618efbc74e0             info        Stream encrypted (TLSv1.2 with ECDHE-RSA-AES256-GCM-SHA384)
c2s5618efbc74e0             info        Client disconnected: connection closed
jcp5618efbcb320             info        Incoming Jabber component connection
focus.meet.jitsi:component  info        Component authentication failed for focus.meet.jitsi
mod_component               info        Disconnecting component, <stream:error> is: <stream:error><not-authorized xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text xmlns='urn:ietf:params:xml:ns:xmpp-streams'>Given token does not match calculated token</text></stream:error>
jcp5618efbcb320             info        component disconnected: focus.meet.jitsi (stream error)
c2s5618efbe36e0             info        Client connected
c2s5618efbe36e0             info        Stream encrypted (TLSv1.2 with ECDHE-RSA-AES256-GCM-SHA384)
c2s5618efbe36e0             info        Client disconnected: connection closed
jcp5618efbe6cd0             info        Incoming Jabber component connection
focus.meet.jitsi:component  info        Component authentication failed for focus.meet.jitsi
mod_component               info        Disconnecting component, <stream:error> is: <stream:error><not-authorized xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text xmlns='urn:ietf:params:xml:ns:xmpp-streams'>Given token does not match calculated token</text></stream:error>
jcp5618efbe6cd0             info        component disconnected: focus.meet.jitsi (stream error)
c2s5618efbff140             info        Client connected
c2s5618efbff140             info        Stream encrypted (TLSv1.2 with ECDHE-RSA-AES256-GCM-SHA384)
c2s5618efbff140             info        Client disconnected: connection closed
`

### **jitsi/web:latest**


`80.150.192.199 - - [07/May/2020:22:14:48 +0200] "GET /sounds/liveStreamingOff.mp3 HTTP/2.0" 206 29475 "https://visio.hello.yata:8443/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
80.150.192.199 - - [07/May/2020:22:14:48 +0200] "GET /sounds/liveStreamingOn.mp3 HTTP/2.0" 206 26115 "https://visio.hello.yata:8443/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
80.150.192.199 - - [07/May/2020:22:14:48 +0200] "GET /sounds/recordingOff.mp3 HTTP/2.0" 206 21572 "https://visio.hello.yata:8443/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
80.150.192.199 - - [07/May/2020:22:14:48 +0200] "GET /sounds/recordingOn.mp3 HTTP/2.0" 206 21855 "https://visio.hello.yata:8443/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
80.150.192.199 - - [07/May/2020:22:14:48 +0200] "GET /sounds/rejected.wav HTTP/2.0" 206 69393 "https://visio.hello.yata:8443/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
`

Best regards

**Comment by saghul** [comment]
@anoskar Have you wiped the entire config directory before updating?

**Comment by profe-jacm** [comment]
Hi,

I m resolv now it`s problem.

From a previous install there was conflict with nginx, my solution, running “apt-get autoremove”.

And follow the steps in strict order, they are forgetting the “gen-passwords.sh” and always deleting the “.jitsi-meet-cfg” when I make changes in the “.env”.

Now it runs well. At the beginning I had a conflict with the Android app, some devices did not recognize my server, upon review I found that this only happened with Android version 7, on those devices I do not use the Jitsi Meet app, I use Mozilla Fire Fox.

**Comment by anoskar** [comment]
@saghul I follow exactly the standard step : 
### 
*** Download and extract the [latest release]
  * Alternatively, to test the latest changes clone the repository: `git clone https://github.com/jitsi/docker-jitsi-meet && cd docker-jitsi-meet`**

Done 


### 
### *** Create a ``.env`` file by copying and adjusting ``env.example``
  * `cp env.example .env`**


Done and i edit .env file. I add only my timezone and my domain name like " https://mydomaine.yata "

###   * Set strong passwords in the security section options: `./gen-passwords.sh`
Done and i check if the passwd has been add 

### *** Create required `CONFIG` directories
  * `mkdir -p ~/.jitsi-meet-cfg/{web/letsencrypt,transcripts,prosody,jicofo,jvb,jigasi,jibri}`**

Done but i do notthing else in this step . 

### *** Run ``docker-compose up -d``**

All docker boot 

### *** Access the web UI at [``https://localhost:8443``](https://localhost:8443) (or a different port, in case you edited the compose file).**

I access the jitsi portail via  : 

### **"https://mydomaine.yata:8000"** 

The portail is up, i made my room and ..... "unfortunately " ..... without requesting access to my camera and microphone

### **"https://mydomaine.yata:8443"** 

The portail is up, i made my room and  after accept camera and micro : ..... "unfortunately " .....

I don't use let's encrypt, it will be the next step.
I miss an operation ?

**Comment by anoskar** [comment]
Nobody have an idea please?

**Comment by normen** [comment]
I *think* WebRTC doesn't work without a proper https connection, do you use a self-signed certificate at least? And did you tell your browser that it's safe? Without letsencrypt or a self-signed cert you won't be able to connect imo.

**Comment by anoskar** [comment]
@normen Hi, i install with success jitsi without docker. I havent work with encryption and still work. 
I have no idead

**Comment by saghul** [comment]
@anoskar Delete your `.jitsi-meet-cfg` directory before starting. With the steps.

**Comment by anoskar** [comment]
@saghul Thx for your help, i follow your vice and it's work ! BUT, After this, i need the config file. 
I searched and found a solution that works

First step : 
# git clone https://github.com/jitsi/docker-jitsi-meet && cd docker-jitsi-meet
# cp env.example .env
# vim .env 
Replace the line " **CONFIG= ~/.jitsi-meet-cfg by CONFIG= .jitsi-meet-cfg** . The folders and cfg files when created in your working directory. 

mkdir -p .jitsi-meet-cfg/{web/letsencrypt,transcripts,prosody/config,prosody/prosody-plugins-custom,jicofo,jvb,jigasi,jibri}

In this step, i don't created like the documentation :  /.jitsi-meet-cfg/{web/letsencrypt,transcripts,prosody/config,prosody/prosody-plugins-custom,jicofo,jvb,jigasi,jibri} but in my working directory :  .jitsi-meet-cfg/{ ...... 
# docker-compose up -d

Thx, it work for me !

**Comment by jchipocov** [comment]
> Hi,
> 
> I m resolv now it`s problem.
> 
> From a previous install there was conflict with nginx, my solution, running “apt-get autoremove”.
> 
> And follow the steps in strict order, they are forgetting the “gen-passwords.sh” and always deleting the “.jitsi-meet-cfg” when I make changes in the “.env”.
> 
> Now it runs well. At the beginning I had a conflict with the Android app, some devices did not recognize my server, upon review I found that this only happened with Android version 7, on those devices I do not use the Jitsi Meet app, I use Mozilla Fire Fox.

"And follow the steps in strict order, they are forgetting the “gen-passwords.sh” and always deleting the “.jitsi-meet-cfg” when I make changes in the “.env”."       That does the trick
