### ISSUE TITLE
Not asking for authentication

### ISSUE THREAD

**Issue by phlegx** [jitsi/docker-jitsi-meet#564]
I'm using latest Jitsi (stable-4548-1) I would like to use LDAP as my authentication method, however when I try to enable it, in the browser it is never asked for any authentication at all. Is this a bug?

These are my settings for enabling it:

```
# Enable authentication
ENABLE_AUTH=1

# Enable guest access
#ENABLE_GUESTS=1

# Select authentication type: internal, jwt or ldap
AUTH_TYPE=ldap
```

But as said it seems these changes are never applied.

I tried to comment out also the `CONFIG=` parameter as suggested here: https://community.jitsi.org/t/jitsi-does-not-ask-for-authentication/15971/11

But this results in errors like:

```
prosody_1  | **************************
prosody_1  | A problem occurred while reading the config file /config/prosody.cfg.lua
prosody_1  | 
prosody_1  | Error: Component "<no value>" clashes with previously defined Host "<no value>", for services use a sub-domain like conference.<no value>
prosody_1  | 
prosody_1  | More help on configuring Prosody can be found at https://prosody.im/doc/configure
prosody_1  | Good luck!
prosody_1  | **************************
prosody_1  | 
jicofo_1   | Jicofo 2020-05-08 10:12:22.539 SEVERE: [17] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.doConnect().303 Failed to connect/login: The following addresses failed: 'xmpp.meet.jitsi:5222' failed because: xmpp.meet.jitsi/192.168.96.3 exception: java.net.ConnectException: Connection refused (Connection refused)
jicofo_1   | org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: 'xmpp.meet.jitsi:5222' failed because: xmpp.meet.jitsi/192.168.96.3 exception: java.net.ConnectException: Connection refused (Connection refused)
jicofo_1   | 	at org.jivesoftware.smack.SmackException$ConnectionException.from(SmackException.java:278)
jicofo_1   | 	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:619)
jicofo_1   | 	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:902)
jicofo_1   | 	at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:383)
jicofo_1   | 	at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.doConnect(XmppProtocolProvider.java:267)
jicofo_1   | 	at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
jicofo_1   | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
jicofo_1   | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
jicofo_1   | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
jicofo_1   | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
jicofo_1   | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
jicofo_1   | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
jicofo_1   | 	at java.lang.Thread.run(Thread.java:748)
jvb_1      | May 08, 2020 10:12:22 AM org.jitsi.utils.logging2.LoggerImpl log
jvb_1      | WARNING: [MucClient id=shard hostname=xmpp.meet.jitsi] error connecting
jvb_1      | org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: 'xmpp.meet.jitsi:5222' failed because: xmpp.meet.jitsi/192.168.96.3 exception: java.net.ConnectException: Connection refused (Connection refused)
jvb_1      | 	at org.jivesoftware.smack.SmackException$ConnectionException.from(SmackException.java:278)
jvb_1      | 	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:619)
jvb_1      | 	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:902)
jvb_1      | 	at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:383)
jvb_1      | 	at org.jitsi.xmpp.mucclient.MucClient.lambda$getConnectAndLoginCallable$7(MucClient.java:638)
jvb_1      | 	at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
jvb_1      | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
jvb_1      | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
jvb_1      | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
jvb_1      | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
jvb_1      | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
jvb_1      | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
jvb_1      | 	at java.lang.Thread.run(Thread.java:748)
jvb_1      | 

```

**Comment by hugokoopmans** [comment]
I had the same issue, I needed to throw away the config directories and recreate the containers to make an updated .env file working...
