### ISSUE TITLE
videobridge throwing health check exceptions even when health checks disabled?

### ISSUE THREAD

**Issue by linuxmagic-mp** [jitsi/docker-jitsi-meet#611]
This MIGHT be a red herring, and actually a problem with the sctp connector.. but. 

2020-05-23 16:38:59.900 INFO: [17] Videobridge.createConference#320: create_conf, id=518e0358f2c95a5e gid=null logging=false
2020-05-23 16:38:59.927 SEVERE: [17] RecurringRunnableExecutor.run#230: The invocation of the method org.jitsi.videobridge.health.Health.run() threw an exception.
java.lang.NoClassDefFoundError: Could not initialize class org.jitsi.videobridge.sctp.SctpManager
	at org.jitsi.videobridge.Endpoint.createSctpConnection(Endpoint.java:868)
	at org.jitsi.videobridge.health.Health.check(Health.java:77)
	at org.jitsi.videobridge.health.Health.performCheck(Health.java:211)
	at org.jitsi.health.AbstractHealthCheckService.run(AbstractHealthCheckService.kt:144)
	at org.jitsi.utils.concurrent.RecurringRunnableExecutor.run(RecurringRunnableExecutor.java:216)
	at org.jitsi.utils.concurrent.RecurringRunnableExecutor.runInThread(RecurringRunnableExecutor.java:292)
	at org.jitsi.utils.concurrent.RecurringRunnableExecutor.access$000(RecurringRunnableExecutor.java:36)
	at org.jitsi.utils.concurrent.RecurringRunnableExecutor$1.run(RecurringRunnableExecutor.java:328)

I have it turned off in /etc/jitsi/jicofo/sip-communicator.properties
org.jitsi.jicofo.HEALTH_CHECK_INTERVAL=-1

Is there another location to turn health checks off that I can't find in the documentation?
Or is this health check always run, and the root problem is something else?

Scouring the community comments, could not find anything related to this.. 
But I think the problem is related to the underlying issue with the sctp connector, but trying to turn off the health checks to confirm what is happening.  But since I am creating the issue, if you could point out the config places where the sctp connector is configured, it might help too.

**Comment by linuxmagic-mp** [comment]
For the record, that is using JVB_OPTS="--apis=xmpp" only, when I add the rest back in, I get further errors which might be related.. 
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.dom4j.io.SAXContentHandler (file:/usr/share/jitsi-videobridge/lib/dom4j-1.6.1.jar) to method com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser$LocatorProxy.getEncoding()
WARNING: Please consider reporting this to the maintainers of org.dom4j.io.SAXContentHandler
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
SCTP JNI load: Linux OS detected
OpenJDK Server VM warning: You have loaded library /tmp/nativeutils185857507199151/libjnisctp.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
2020-05-23 17:06:36.785 SEVERE: [25] RecurringRunnableExecutor.run#230: The invocation of the method org.jitsi.videobridge.health.Health.run() threw an exception.
java.lang.UnsatisfiedLinkError: /tmp/nativeutils185857507199151/libjnisctp.so: /tmp/nativeutils185857507199151/libjnisctp.so: wrong ELF class: ELFCLASS64 (Possible cause: architecture word width mismatch)
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1834)
	at cz.adamh.utils.NativeUtils.loadLibraryFromJar(NativeUtils.java:109)
	at org.jitsi_modified.sctp4j.SctpJni.<clinit>(SctpJni.java:31)
	at org.jitsi_modified.sctp4j.Sctp4j.init(Sctp4j.java:40)
	at org.jitsi.videobridge.sctp.SctpManager.<clinit>(SctpManager.java:54)
	at org.jitsi.videobridge.Endpoint.createSctpConnection(Endpoint.java:868)
	at org.jitsi.videobridge.health.Health.check(Health.java:77)
	at org.jitsi.videobridge.health.Health.performCheck(Health.java:211)
	at org.jitsi.health.AbstractHealthCheckService.run(AbstractHealthCheckService.kt:144)
	at org.jitsi.utils.concurrent.RecurringRunnableExecutor.run(RecurringRunnableExecutor.java:216)
	at org.jitsi.utils.concurrent.RecurringRunnableExecutor.runInThread(RecurringRunnableExecutor.java:292)
	at org.jitsi.utils.concurrent.RecurringRunnableExecutor.access$000(RecurringRunnableExecutor.java:36)
	at org.jitsi.utils.concurrent.RecurringRunnableExecutor$1.run(RecurringRunnableExecutor.java:328)

Running on ARM Linux

**Comment by saghul** [comment]
ARM is not officially supported. Can you reproduce this with the official images in DockerHub?

**Comment by linuxmagic-mp** [comment]
Well, a couple of points.. since it is an ALL debian package, it would be resume to be supported, otherwise you should only provide the .deb's for the support platforms.  However.. 

* Could you explain why the health checks are still loaded, when config has them disabled?
* Can we disable SCTP (libjnisctp.so) and still function? If so how?

**Comment by saghul** [comment]
> Well, a couple of points.. since it is an ALL debian package, it would be resume to be supported, otherwise you should only provide the .deb's for the support platforms.

We live in an imperfect world.

>     * Could you explain why the health checks are still loaded, when config has them disabled?

IIRC there was some health-check related problem not o long ago (can't remember the details, sorry) butt the latest stable build should be fine.

>     * Can we disable SCTP (libjnisctp.so) and still function? If so how?

Technically yes, and use WebSocket based bridge channels, but the Docker setup does not yet support them.

**Comment by linuxmagic-mp** [comment]
Could you explain the 'technically yes', eg how would you do this "manually", so we can continue moving forward on our research/testing...

**Comment by saghul** [comment]
https://github.com/jitsi/jitsi-videobridge/blob/master/doc/web-sockets.md

**Comment by linuxmagic-mp** [comment]
For the record, for ARM users on Raspberry PI, follow the instructions here, to fix the SCTP (libjnisctp.so), works for me.. https://community.jitsi.org/t/running-jitsi-meet-on-arm-devices-amazon-ampere-odroid-marvell-thunderx-raspberry-pi-4-tinkerboard-running-raspbian-armbian-debian-or-ubuntu/47842/2
