### ISSUE TITLE
Failed stoping recording

### ISSUE THREAD

**Issue by Oper18** [jitsi/docker-jitsi-meet#615]
Recording start well, but when I will stop it, there are message recording failed to start and chromedriver in container not killed:

```
UID                 PID                 PPID                C                   STIME               TTY                 TIME                CMD
root                18146               18111               0                   18:32               ?                   00:00:00            s6-svscan -t0 /var/run/s6/services
root                18795               18146               0                   18:32               ?                   00:00:00            s6-supervise s6-fdholderd
root                19182               18146               0                   18:32               ?                   00:00:00            s6-supervise 10-xorg
root                19183               18146               0                   18:32               ?                   00:00:00            s6-supervise 20-icewm
root                19184               18146               0                   18:32               ?                   00:00:00            s6-supervise 30-jibri
jvb                 19186               19184               2                   18:32               ?                   00:00:08            java -Djava.util.logging.config.file=/etc/jitsi/jibri/logging.properties -jar /opt/jitsi/jibri/jibri.jar --config /etc/jitsi/jibri/config.json
jvb                 19188               19183               0                   18:32               ?                   00:00:00            /usr/bin/icewm-session
jvb                 19190               19182               2                   18:32               ?                   00:00:07            /usr/lib/xorg/Xorg -nocursor -noreset +extension RANDR +extension RENDER -logfile /tmp/xorg.log -config /etc/jitsi/jibri/xorg-video-dummy.conf :0
jvb                 19229               19188               0                   18:32               ?                   00:00:00            icewmbg
jvb                 19230               19188               0                   18:32               ?                   00:00:00            icewm --notify
jvb                 19637               19188               0                   18:32               ?                   00:00:00            icewmtray --notify
jvb                 19791               19186               0                   18:33               ?                   00:00:00            /usr/bin/chromedriver --port=24680 --log-path=/tmp/chromedriver.log
```

and in log:

```
2020-05-27 18:34:15.508 FINE: [53] org.jitsi.jibri.statsd.JibriStatsDClient.incrementCounter() Incrementing statsd counter: stop:recording
2020-05-27 18:34:15.510 INFO: [53] org.jitsi.jibri.JibriManager.stopService() Stopping the current service
2020-05-27 18:34:15.510 INFO: [53] org.jitsi.jibri.service.impl.FileRecordingJibriService.stop() Stopping capturer
2020-05-27 18:34:15.510 INFO: [53] org.jitsi.jibri.util.JibriSubprocess.ffmpeg.stop() Stopping ffmpeg process
2020-05-27 18:34:16.087 SEVERE: [47] org.jitsi.jibri.selenium.JibriSelenium.invoke() Error while running call status checks: org.openqa.selenium.WebDriverException: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome=78.0.3904.97)
  (Driver info: chromedriver=78.0.3904.105 (60e2d8774a8151efa6a00b1f358371b1e0e07ee2-refs/branch-heads/3904@{#877}),platform=Linux 4.4.0-170-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: '8537ae3a59ad', ip: '18.69.0.7', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-170-generic', java.version: '1.8.0_252'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 78.0.3904.105 (60e2d8774a81..., userDataDir: /tmp/.com.google.Chrome.VXmIJw}, cssSelectorsEnabled: true, databaseEnabled: false, goog:chromeOptions: {debuggerAddress: localhost:41017}, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), rotatable: false, setWindowRect: true, strictFileInteractability: false, takesHeapSnapshot: true, takesScreenshot: true, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unexpectedAlertBehaviour: ignore, unhandledPromptBehavior: ignore, version: 78.0.3904.97, webStorageEnabled: true}
Session ID: 3870cfc695df849e227cadcb7e29ba4a with stack:
un.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
java.lang.reflect.Constructor.newInstance(Constructor.java:423)
org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:480)
org.jitsi.jibri.selenium.pageobjects.CallPage.getNumParticipants(CallPage.kt:71)
org.jitsi.jibri.selenium.status_checks.EmptyCallStatusCheck.isCallEmpty(EmptyCallStatusCheck.kt:44)
org.jitsi.jibri.selenium.status_checks.EmptyCallStatusCheck.run(EmptyCallStatusCheck.kt:29)
org.jitsi.jibri.selenium.JibriSelenium$startRecurringCallStatusChecks$1$event$1.invoke(JibriSelenium.kt:201)
org.jitsi.jibri.selenium.JibriSelenium$startRecurringCallStatusChecks$1$event$1.invoke(JibriSelenium.kt:112)
kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:172)
org.jitsi.jibri.selenium.JibriSelenium$startRecurringCallStatusChecks$1.invoke(JibriSelenium.kt:301)
org.jitsi.jibri.selenium.JibriSelenium$startRecurringCallStatusChecks$1.invoke(JibriSelenium.kt:112)
org.jitsi.jibri.util.extensions.SchedulerExecutorServiceExtsKt$sam$java_lang_Runnable$0.run(SchedulerExecutorServiceExts.kt)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

2020-05-27 18:34:16.095 INFO: [55] org.jitsi.jibri.selenium.JibriSelenium.onSeleniumStateChange() Transitioning from state Running to Error: SESSION Chrome hung
2020-05-27 18:34:16.096 INFO: [55] org.jitsi.jibri.service.impl.FileRecordingJibriService.onServiceStateChange() File recording service transitioning from state Running to Error: SESSION Chrome hung
2020-05-27 18:34:16.098 INFO: [55] org.jitsi.jibri.api.xmpp.XmppApi.invoke() Current service had an error, sending error iq <iq to='jibribrewery@internal-muc.meet.jitsi/focus' id='kkVtF-30' type='set'><jibri xmlns='http://jitsi.org/protocol/jibri' status='off' failure_reason='error'/></iq>
2020-05-27 18:34:16.167 INFO: [50] org.jitsi.jibri.capture.ffmpeg.FfmpegCapturer.onFfmpegStateMachineStateChange() Ffmpeg capturer transitioning from state Running to Finished
2020-05-27 18:34:16.170 INFO: [53] org.jitsi.jibri.util.JibriSubprocess.ffmpeg.stop() ffmpeg exited with value 255
2020-05-27 18:34:16.171 INFO: [53] org.jitsi.jibri.service.impl.FileRecordingJibriService.stop() Quitting selenium
2020-05-27 18:34:16.178 INFO: [53] org.jitsi.jibri.service.impl.FileRecordingJibriService.stop() Participants in this recording: []
2020-05-27 18:34:16.309 FINE: [55] org.jitsi.jibri.statsd.JibriStatsDClient.incrementCounter() Incrementing statsd counter: stop:recording
2020-05-27 18:34:16.310 INFO: [55] org.jitsi.jibri.JibriManager.stopService() Stopping the current service
2020-05-27 18:34:16.310 INFO: [55] org.jitsi.jibri.service.impl.FileRecordingJibriService.stop() Stopping capturer
2020-05-27 18:34:16.311 INFO: [55] org.jitsi.jibri.util.JibriSubprocess.ffmpeg.stop() Stopping ffmpeg process
Exception in thread "Smack Cached Executor" java.lang.ClassCastException: com.google.common.collect.Maps$TransformedEntriesMap cannot be cast to java.util.List
        at org.openqa.selenium.remote.RemoteLogs.getAvailableLogTypes(RemoteLogs.java:108)
        at org.jitsi.jibri.selenium.JibriSelenium.leaveCallAndQuitBrowser(JibriSelenium.kt:280)
        at org.jitsi.jibri.service.impl.FileRecordingJibriService.stop(FileRecordingJibriService.kt:188)
        at org.jitsi.jibri.JibriManager.stopService(JibriManager.kt:254)
        at org.jitsi.jibri.api.xmpp.XmppApi.handleStopJibriIq(XmppApi.kt:256)
        at org.jitsi.jibri.api.xmpp.XmppApi.handleJibriIq(XmppApi.kt:163)
        at org.jitsi.jibri.api.xmpp.XmppApi.handleIq(XmppApi.kt:147)
        at org.jitsi.xmpp.mucclient.MucClient.handleIq(MucClient.java:446)
        at org.jitsi.xmpp.mucclient.MucClient.access$500(MucClient.java:47)
        at org.jitsi.xmpp.mucclient.MucClient$2.handleIQRequest(MucClient.java:412)
        at org.jivesoftware.smack.AbstractXMPPConnection$4.run(AbstractXMPPConnection.java:1188)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-05-27 18:34:16.317 INFO: [55] org.jitsi.jibri.util.JibriSubprocess.ffmpeg.stop() ffmpeg exited with value 255
2020-05-27 18:34:16.317 INFO: [55] org.jitsi.jibri.service.impl.FileRecordingJibriService.stop() Quitting selenium
2020-05-27 18:34:16.325 INFO: [55] org.jitsi.jibri.service.impl.FileRecordingJibriService.stop() Participants in this recording: []
```

if I want to start recording again:
`All recorders are currently busy`

**Comment by ccs1428** [comment]
Facing same issue , are you able to solve the issue.

Recording stops after some time, Sharing my log details.

Please help me.
[log.1.txt](https://github.com/jitsi/docker-jitsi-meet/files/5052897/log.1.txt)

**Comment by ccs1428** [comment]
@Oper18  Please help.

**Comment by aninditasadhukhan** [comment]
I have also faced the same issue. Did you guys get any solution for this?

**Comment by ccs1428** [comment]
@aninditasadhukhan  Please check log file details. Are you using same instance for Jibri and Jitsi server.

**Comment by aninditasadhukhan** [comment]
I have install a jitsi in that same server where jibri is installed in docker, but not using that jitsi server. My original jitsi server is installed in another VM,

**Comment by ccs1428** [comment]
Please check log details.

**Comment by aninditasadhukhan** [comment]
@ccs1428 below is the log0.txt

2020-09-08 07:23:45.036 FINE: [3392] org.jitsi.jibri.statsd.JibriStatsDClient.incrementCounter() Incrementing statsd counter: stop:recording
2020-09-08 07:23:45.036 FINE: [118] org.jitsi.jibri.util.ProcessStatePublisher.ffmpeg.invoke() Process ffmpeg hasn't written in 2 seconds, publishing periodic update
2020-09-08 07:23:45.036 INFO: [3392] org.jitsi.jibri.JibriManager.stopService() Stopping the current service
2020-09-08 07:23:45.036 INFO: [3392] org.jitsi.jibri.service.impl.FileRecordingJibriService.stop() Stopping capturer
2020-09-08 07:23:45.037 INFO: [3390] org.jitsi.jibri.api.xmpp.XmppApi.handleJibriIq() Received JibriIq <iq to='jibri@auth.xmppdemo.tcgdigital.com/AGAzFxGs' from='jibribrewery@internal.auth.xmppdemo.tcgdigital.com/focus' id='amlicmlAYXV0aC54bXBwZGVtby50Y2dkaWdpdGFsLmNvbS9BR0F6RnhHcwB0TUdoMC02MzY5NACeTUyHiENXWWq3F0Sqd/QX' type='set'><jibri xmlns='http://jitsi.org/protocol/jibri' action='stop'/></iq> from environment [MucClient id=xmppdemo.tcgdigital.com hostname=xmppdemo.tcgdigital.com]
2020-09-08 07:23:45.037 INFO: [3392] org.jitsi.jibri.util.JibriSubprocess.ffmpeg.stop() Stopping ffmpeg process
2020-09-08 07:23:45.037 FINE: [118] org.jitsi.jibri.util.ProcessStatePublisher.ffmpeg.invoke() Process ffmpeg hasn't written in 2 seconds, publishing periodic update
2020-09-08 07:28:53.001 SEVERE: [3392] org.jitsi.jibri.util.JibriSubprocess.ffmpeg.stop() Error trying to gracefully stop ffmpeg, destroying forcibly
2020-09-08 07:28:53.049 INFO: [3392] org.jitsi.jibri.util.JibriSubprocess.ffmpeg.stop() ffmpeg exited with value 137
2020-09-08 07:28:53.049 INFO: [3392] org.jitsi.jibri.service.impl.FileRecordingJibriService.stop() Quitting selenium
2020-09-08 07:29:06.827 SEVERE: [118] org.jitsi.jibri.selenium.JibriSelenium.invoke() Error while running call status checks: org.openqa.selenium.WebDriverException: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome=78.0.3904.97)
  (Driver info: chromedriver=78.0.3904.105 (60e2d8774a8151efa6a00b1f358371b1e0e07ee2-refs/branch-heads/3904@{#877}),platform=Linux 4.15.0-115-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: '0769ceb7461b', ip: '172.27.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-115-generic', java.version: '1.8.0_252'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 78.0.3904.105 (60e2d8774a81..., userDataDir: /tmp/.com.google.Chrome.B5FAXT}, cssSelectorsEnabled: true, databaseEnabled: false, goog:chromeOptions: {debuggerAddress: localhost:36205}, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), rotatable: false, setWindowRect: true, strictFileInteractability: false, takesHeapSnapshot: true, takesScreenshot: true, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unexpectedAlertBehaviour: ignore, unhandledPromptBehavior: ignore, version: 78.0.3904.97, webStorageEnabled: true}
Session ID: bd1561b9e4a55da83a0766088843158d with stack: 
sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
java.lang.reflect.Constructor.newInstance(Constructor.java:423)
org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:480)
org.jitsi.jibri.selenium.pageobjects.CallPage.getNumParticipants(CallPage.kt:74)
org.jitsi.jibri.selenium.status_checks.EmptyCallStatusCheck.isCallEmpty(EmptyCallStatusCheck.kt:44)
org.jitsi.jibri.selenium.status_checks.EmptyCallStatusCheck.run(EmptyCallStatusCheck.kt:29)
org.jitsi.jibri.selenium.JibriSelenium$startRecurringCallStatusChecks$1$event$1.invoke(JibriSelenium.kt:204)
org.jitsi.jibri.selenium.JibriSelenium$startRecurringCallStatusChecks$1$event$1.invoke(JibriSelenium.kt:116)
kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:172)
org.jitsi.jibri.selenium.JibriSelenium$startRecurringCallStatusChecks$1.invoke(JibriSelenium.kt:310)
org.jitsi.jibri.selenium.JibriSelenium$startRecurringCallStatusChecks$1.invoke(JibriSelenium.kt:116)
org.jitsi.jibri.util.extensions.SchedulerExecutorServiceExtsKt$sam$java_lang_Runnable$0.run(SchedulerExecutorServiceExts.kt)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

2020-09-08 07:29:06.831 INFO: [3385] org.jitsi.jibri.selenium.JibriSelenium.onSeleniumStateChange() Transitioning from state Running to Error: ChromeHung SESSION Chrome hung
2020-09-08 07:29:06.831 INFO: [3385] org.jitsi.jibri.service.impl.FileRecordingJibriService.onServiceStateChange() File recording service transitioning from state Running to Error: ChromeHung SESSION Chrome hung
2020-09-08 07:29:06.832 INFO: [3385] org.jitsi.jibri.api.xmpp.XmppApi.invoke() Current service had an error Error: ChromeHung SESSION Chrome hung, sending error iq <iq to='jibribrewery@internal.auth.xmppdemo.tcgdigital.com/focus' id='iBLxY-6688' type='set'><jibri xmlns='http://jitsi.org/protocol/jibri' status='off' failure_reason='error' should_retry='true'/></iq>
2020-09-08 07:29:07.023 INFO: [3392] org.jitsi.jibri.service.impl.FileRecordingJibriService.stop() Participants in this recording: []
2020-09-08 07:29:07.178 SEVERE: [118] org.jitsi.jibri.selenium.pageobjects.CallPage.numRemoteParticipantsMuted() error running numRemoteParticipantsMuted script: {error=invalid session id, message=invalid session id, stacktrace=#0 0x55a88f9df859 <unknown>
} class com.google.common.collect.Maps$TransformedEntriesMap
2020-09-08 07:29:07.183 INFO: [118] org.jitsi.jibri.selenium.JibriSelenium.run() Jibri client receive bitrates: {}, all clients muted? true
2020-09-08 07:29:07.190 SEVERE: [118] org.jitsi.jibri.selenium.pageobjects.CallPage.numRemoteParticipantsMuted() error running numRemoteParticipantsMuted script: {error=invalid session id, message=invalid session id, stacktrace=#0 0x55a88f9df859 <unknown>
} class com.google.common.collect.Maps$TransformedEntriesMap
2020-09-08 07:29:07.194 INFO: [118] org.jitsi.jibri.selenium.JibriSelenium.run() Jibri client receive bitrates: {}, all clients muted? true
2020-09-08 07:29:07.209 SEVERE: [118] org.jitsi.jibri.selenium.pageobjects.CallPage.numRemoteParticipantsMuted() error running numRemoteParticipantsMuted script: {error=invalid session id, message=invalid session id, stacktrace=#0 0x55a88f9df859 <unknown>
} class com.google.common.collect.Maps$TransformedEntriesMap
2020-09-08 07:29:07.213 INFO: [118] org.jitsi.jibri.selenium.JibriSelenium.run() Jibri client receive bitrates: {}, all clients muted? true
2020-09-08 07:29:07.221 SEVERE: [118] org.jitsi.jibri.selenium.pageobjects.CallPage.numRemoteParticipantsMuted() error running numRemoteParticipantsMuted script: {error=invalid session id, message=invalid session id, stacktrace=#0 0x55a88f9df859 <unknown>
} class com.google.common.collect.Maps$TransformedEntriesMap
2020-09-08 07:29:07.223 INFO: [118] org.jitsi.jibri.selenium.JibriSelenium.run() Jibri client receive bitrates: {}, all clients muted? true
2020-09-08 07:29:07.231 SEVERE: [118] org.jitsi.jibri.selenium.pageobjects.CallPage.numRemoteParticipantsMuted() error running numRemoteParticipantsMuted script: {error=invalid session id, message=invalid session id, stacktrace=#0 0x55a88f9df859 <unknown>
} class com.google.common.collect.Maps$TransformedEntriesMap
2020-09-08 07:29:07.234 INFO: [118] org.jitsi.jibri.selenium.JibriSelenium.run() Jibri client receive bitrates: {}, all clients muted? true
2020-09-08 07:29:07.247 SEVERE: [118] org.jitsi.jibri.selenium.pageobjects.CallPage.numRemoteParticipantsMuted() error running numRemoteParticipantsMuted script: {error=invalid session id, message=invalid session id, stacktrace=#0 0x55a88f9df859 <unknown>
} class com.google.common.collect.Maps$TransformedEntriesMap
2020-09-08 07:29:07.250 INFO: [118] org.jitsi.jibri.selenium.JibriSelenium.run() Jibri client receive bitrates: {}, all clients muted? true
2020-09-08 07:29:07.326 SEVERE: [118] org.jitsi.jibri.selenium.pageobjects.CallPage.numRemoteParticipantsMuted() error running numRemoteParticipantsMuted script: {error=invalid session id, message=invalid session id, stacktrace=#0 0x55a88f9df859 <unknown>
} class com.google.common.collect.Maps$TransformedEntriesMap
2020-09-08 07:29:07.341 INFO: [118] org.jitsi.jibri.selenium.JibriSelenium.run() Jibri client receive bitrates: {}, all clients muted? true
2020-09-08 07:29:07.368 SEVERE: [118] org.jitsi.jibri.selenium.pageobjects.CallPage.numRemoteParticipantsMuted() error running numRemoteParticipantsMuted script: {error=invalid session id, message=invalid session id, stacktrace=#0 0x55a88f9df859 <unknown>
} class com.google.common.collect.Maps$TransformedEntriesMap
2020-09-08 07:29:07.402 INFO: [118] org.jitsi.jibri.selenium.JibriSelenium.run() Jibri client receive bitrates: {}, all clients muted? true
2020-09-08 07:29:07.522 SEVERE: [118] org.jitsi.jibri.selenium.pageobjects.CallPage.numRemoteParticipantsMuted() error running numRemoteParticipantsMuted script: {error=invalid session id, message=invalid session id, stacktrace=#0 0x55a88f9df859 <unknown>
} class com.google.common.collect.Maps$TransformedEntriesMap
2020-09-08 07:29:07.524 INFO: [3392] org.jitsi.jibri.selenium.JibriSelenium.leaveCallAndQuitBrowser() Leaving call and quitting browser
2020-09-08 07:29:07.525 INFO: [3392] org.jitsi.jibri.selenium.JibriSelenium.leaveCallAndQuitBrowser() Recurring call status checks cancelled
2020-09-08 07:29:07.591 SEVERE: [3392] org.jitsi.jibri.selenium.JibriSelenium.leaveCallAndQuitBrowser() Error trying to get chromedriver logs: java.lang.ClassCastException: com.google.common.collect.Maps$TransformedEntriesMap cannot be cast to java.util.List with stack: 
org.openqa.selenium.remote.RemoteLogs.getAvailableLogTypes(RemoteLogs.java:108)
org.jitsi.jibri.selenium.JibriSelenium.leaveCallAndQuitBrowser(JibriSelenium.kt:286)
org.jitsi.jibri.service.impl.FileRecordingJibriService.stop(FileRecordingJibriService.kt:190)
org.jitsi.jibri.JibriManager.stopService(JibriManager.kt:257)
org.jitsi.jibri.api.xmpp.XmppApi.handleStopJibriIq(XmppApi.kt:256)
org.jitsi.jibri.api.xmpp.XmppApi.handleJibriIq(XmppApi.kt:162)
org.jitsi.jibri.api.xmpp.XmppApi.handleIq(XmppApi.kt:146)
org.jitsi.xmpp.mucclient.MucClient.handleIq(MucClient.java:547)
org.jitsi.xmpp.mucclient.MucClient.access$500(MucClient.java:50)
org.jitsi.xmpp.mucclient.MucClient$2.handleIQRequest(MucClient.java:511)
org.jivesoftware.smack.AbstractXMPPConnection$4.run(AbstractXMPPConnection.java:1188)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

2020-09-08 07:29:07.591 INFO: [3392] org.jitsi.jibri.selenium.JibriSelenium.leaveCallAndQuitBrowser() Leaving web call
2020-09-08 07:29:07.596 INFO: [3392] org.jitsi.jibri.selenium.JibriSelenium.leaveCallAndQuitBrowser() Quitting chrome driver
2020-09-08 07:29:07.661 INFO: [3392] org.jitsi.jibri.selenium.JibriSelenium.leaveCallAndQuitBrowser() Chrome driver quit
2020-09-08 07:29:07.661 INFO: [3392] org.jitsi.jibri.service.impl.FileRecordingJibriService.stop() Finalizing the recording
2020-09-08 07:29:07.711 SEVERE: [118] org.jitsi.jibri.selenium.JibriSelenium.invoke() Error while running call status checks: org.openqa.selenium.WebDriverException: java.io.InterruptedIOException: thread interrupted
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: '0769ceb7461b', ip: '172.27.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-115-generic', java.version: '1.8.0_252'
Driver info: driver.version: RemoteWebDriver with stack: 
org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:92)
org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:480)
org.jitsi.jibri.selenium.pageobjects.CallPage.getNumParticipants(CallPage.kt:74)
org.jitsi.jibri.selenium.status_checks.MediaReceivedStatusCheck.run(MediaReceivedStatusCheck.kt:30)
org.jitsi.jibri.selenium.JibriSelenium$startRecurringCallStatusChecks$1$event$1.invoke(JibriSelenium.kt:204)
org.jitsi.jibri.selenium.JibriSelenium$startRecurringCallStatusChecks$1$event$1.invoke(JibriSelenium.kt:116)
kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:172)
org.jitsi.jibri.selenium.JibriSelenium$startRecurringCallStatusChecks$1.invoke(JibriSelenium.kt:310)
org.jitsi.jibri.selenium.JibriSelenium$startRecurringCallStatusChecks$1.invoke(JibriSelenium.kt:116)
org.jitsi.jibri.util.extensions.SchedulerExecutorServiceExtsKt$sam$java_lang_Runnable$0.run(SchedulerExecutorServiceExts.kt)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

2020-09-08 07:29:08.023 INFO: [3382] org.jitsi.jibri.service.impl.FileRecordingJibriService.call() /config/finalize.sh: 1: /config/finalize.sh: !/bin/bash: not found
2020-09-08 07:29:08.024 INFO: [3392] org.jitsi.jibri.service.impl.FileRecordingJibriService.finalize() Recording finalize script finished with exit value 0
2020-09-08 07:29:08.025 INFO: [3392] org.jitsi.jibri.status.JibriStatusManager.log() Busy status has changed: BUSY -> IDLE
2020-09-08 07:29:08.025 INFO: [3392] org.jitsi.jibri.api.xmpp.XmppApi.updatePresence() Jibri reports its status is now JibriStatus(busyStatus=IDLE, health=OverallHealth(healthStatus=HEALTHY, details={})), publishing presence to connections
2020-09-08 07:29:08.025 FINE: [3392] org.jitsi.xmpp.mucclient.MucClientManager.log() Setting a presence extension: org.jitsi.xmpp.extensions.jibri.JibriStatusPacketExt@445cac74
2020-09-08 07:29:08.025 FINE: [3392] org.jitsi.xmpp.mucclient.MucClientManager.log() Replacing presence extension: org.jitsi.xmpp.extensions.jibri.JibriStatusPacketExt@680f4750
2020-09-08 07:29:08.026 INFO: [3385] org.jitsi.jibri.JibriManager.stopService() No service active, ignoring stop
2020-09-08 07:29:08.031 INFO: [3390] org.jitsi.jibri.JibriManager.stopService() No service active, ignoring stop
2020-09-08 07:29:08.071 FINE: [31] org.jitsi.xmpp.extensions.DefaultPacketExtensionProvider.parse() Could not add a provider for element busy-status from namespace http://jitsi.org/protocol/jibri
2020-09-08 07:29:08.072 FINE: [31] org.jitsi.xmpp.extensions.DefaultPacketExtensionProvider.parse() Could not add a provider for element health-status from namespace http://jitsi.org/protocol/health
2020-09-08 07:29:09.280 FINE: [31] org.jitsi.xmpp.extensions.DefaultPacketExtensionProvider.parse() Could not add a provider for element busy-status from namespace http://jitsi.org/protocol/jibri
2020-09-08 07:29:09.280 FINE: [31] org.jitsi.xmpp.extensions.DefaultPacketExtensionProvider.parse() Could not add a provider for element health-status from namespace http://jitsi.org/protocol/health

**Comment by ccs1428** [comment]
Can you please refer this thread.

https://community.jitsi.org/t/solved-partially-jibri-recording-stucked-with-recording-has-stopped-then-busy/17783/22

is port 5222 is open 

please check Jitsi server log too.

**Comment by aninditasadhukhan** [comment]
@ccs1428 Yes, 5222 port is open, I am able to do recording for a single instance of Jibri. But when trying to record 2 instances is docker container chrome got hung and I am getting this error.
In jicofo log I am getting below error.

Jicofo 2019-06-17 19:22:52.231 SEVERE: [253] org.jitsi.jicofo.recording.jibri.JibriSession.log() Error sending stop iq: org.jivesoftware.smack.SmackException$NoResponseException: No response received within reply timeout. Timeout was 15000ms (~15s). Waited for response using: IQReplyFilter: iqAndIdFilter (AndFilter: (OrFilter: (IQTypeFilter: type=error, IQTypeFilter: type=result), StanzaIdFilter: id=osE5z-20334)), : fromFilter (OrFilter: (FromMatchesFilter (full): jibribrewery@internal.auth.mydomin/jibri-nickname)).

**Comment by saghul** [comment]
Please test the new stable release: https://github.com/jitsi/docker-jitsi-meet/releases/tag/stable-5870
