### ISSUE TITLE
Jigasi issues on 4627-1

### ISSUE THREAD

**Issue by ktechmidas** [jitsi/docker-jitsi-meet#621]
Hi guys, I'm trying to get Jigasi set up on the latest stable version - I'm getting some errors that look like they were solved months ago so I'm not sure what's going on... I've created /config/log and given full read/write to just and yet it still has that error... then there's another one about XMPP hosts although I see all that in my env so I'm not sure why it's complaining?

I did add the following to the sip-communicator.properties file, but it doesn't seem to have any effect.

`
org.jitsi.jigasi.MUC_SERVICE_ADDRESS=muc.meet.jitsi
`

I see from the prosody logs jigasi is connecting okay... so I'm really not sure what the issue is

`Jigasi 2020-05-29 16:05:40.474 INFO: [88] org.jitsi.jigasi.SipGateway.incomingCallReceived().216 [ctx=1590768340473728884167] Incoming call received.$
.                                                                                                                                                     
Jigasi 2020-05-29 16:05:40.479 INFO: [89] org.jitsi.jigasi.SipGatewaySession.run().1490 [ctx=1590768340473728884167] Wait thread cancelled            
Jigasi 2020-05-29 16:05:40.483 INFO: [88] org.jitsi.jigasi.JvbConference.start().430 [ctx=1590768340473728884167] Starting JVB conference room: testt$
ething3@conference.meet.althatech.com                                                                                                                 
Jigasi 2020-05-29 16:05:40.485 INFO: [88] org.jitsi.jigasi.JvbConference.setXmppProvider().561 [ctx=1590768340473728884167] Using ProtocolProviderSer$
iceJabberImpl(Jabber:60af0fa9@true/60af0fa9)                                                                                                          
Jigasi 2020-05-29 16:05:40.490 SEVERE: [29] impl.packetlogging.PacketLoggingServiceImpl.run().845 Error writing packet to file                        
java.lang.SecurityException: Insufficient rights to access this file in current user's home directory: /config/log/jitsi0.pcap                        
        at org.jitsi.impl.fileaccess.FileAccessServiceImpl.getPrivatePersistentFile(FileAccessServiceImpl.java:171)                                   
        at net.java.sip.communicator.impl.packetlogging.PacketLoggingServiceImpl.getFileNames(PacketLoggingServiceImpl.java:197)                      
        at net.java.sip.communicator.impl.packetlogging.PacketLoggingServiceImpl.savePacket(PacketLoggingServiceImpl.java:582)                        
        at net.java.sip.communicator.impl.packetlogging.PacketLoggingServiceImpl.access$100(PacketLoggingServiceImpl.java:35)                         
        at net.java.sip.communicator.impl.packetlogging.PacketLoggingServiceImpl$SaverThread.run(PacketLoggingServiceImpl.java:834)                   
Jigasi 2020-05-29 16:05:40.490 SEVERE: [29] impl.packetlogging.PacketLoggingServiceImpl.run().845 Error writing packet to file                        
java.lang.SecurityException: Insufficient rights to access this file in current user's home directory: /config/log/jitsi0.pcap                        
        at org.jitsi.impl.fileaccess.FileAccessServiceImpl.getPrivatePersistentFile(FileAccessServiceImpl.java:171)                                   
        at net.java.sip.communicator.impl.packetlogging.PacketLoggingServiceImpl.getFileNames(PacketLoggingServiceImpl.java:197)                      
        at net.java.sip.communicator.impl.packetlogging.PacketLoggingServiceImpl.savePacket(PacketLoggingServiceImpl.java:582)                        
        at net.java.sip.communicator.impl.packetlogging.PacketLoggingServiceImpl.access$100(PacketLoggingServiceImpl.java:35)                         
        at net.java.sip.communicator.impl.packetlogging.PacketLoggingServiceImpl$SaverThread.run(PacketLoggingServiceImpl.java:834)                   
Jigasi 2020-05-29 16:05:40.499 SEVERE: [91] impl.protocol.jabber.ProtocolProviderServiceJabberImpl.connectAndLogin().1003 Failed to connect to XMPP s$
rvice
org.jivesoftware.smack.XMPPException$StreamErrorException: host-unknown You can read more about the meaning of this stream error at http://xmcs/rfc6120.html#streams-error-conditions                                                                                                              
<stream:error><host-unknown xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text>This server does not serve true</text></stream:error>
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1059)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:1000)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1016)
        at java.lang.Thread.run(Thread.java:748)
Jigasi 2020-05-29 16:05:40.500 WARNING: [95] org.jivesoftware.smack.AbstractXMPPConnection.callConnectionClosedOnErrorListener() Connection XMPPTCPCon
nection[not-authenticated] (1) closed with error
org.jivesoftware.smack.XMPPException$StreamErrorException: host-unknown You can read more about the meaning of this stream error at http://xmpp.org/rf
cs/rfc6120.html#streams-error-conditions
<stream:error><host-unknown xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text>This server does not serve true</text></stream:error>
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1064)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:1000)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1016)
        at java.lang.Thread.run(Thread.java:748)
Jigasi 2020-05-29 16:05:40.501 SEVERE: [91] org.jitsi.jigasi.JvbConference.registrationStateChanged().616 [ctx=1590768340473728884167] XMPP Connection
 failed.
Jigasi 2020-05-29 16:05:40.501 WARNING: [91] org.jitsi.jigasi.JvbConference.leaveConferenceRoom().905 [ctx=1590768340473728884167] MUC room is null
Jigasi 2020-05-29 16:05:44.700 INFO: [97] impl.protocol.sip.SipLogger.logInfo().196 Info from the JAIN-SIP stack: Setting SIPMessage peerPacketSource
to: /69.167.178.6:5060
Jigasi 2020-05-29 16:05:54.415 INFO: [98] impl.protocol.sip.SipLogger.logInfo().196 Info from the JAIN-SIP stack: Setting SIPMessage peerPacketSource
to: /69.167.178.6:5060
Jigasi 2020-05-29 16:05:54.422 INFO: [98] org.jitsi.jigasi.SipGatewaySession.handleCallState().1391 [ctx=1590768340473728884167] SIP call ended: CallP
eerChangeEvent: type=CallPeerStatusChange oldV=net.java.sip.communicator.service.protocol.CallPeerState:Incoming Call newV=net.java.sip.communicator.s
ervice.protocol.CallPeerState:Disconnected for peer=anonymous <anonymous@jitsi.voximplant-altha.n2.voximplant.com>;status=Disconnected
Jigasi 2020-05-29 16:05:54.422 INFO: [98] org.jitsi.jigasi.SipGatewaySession.sipCallEnded().584 [ctx=1590768340473728884167] Sip call ended: Call: id=
15907683404331874990683 peers=0
Jigasi 2020-05-29 16:05:54.423 WARNING: [98] org.jitsi.jigasi.JvbConference.leaveConferenceRoom().905 [ctx=1590768340473728884167] MUC room is null
Jigasi 2020-05-29 16:05:54.424 INFO: [98] org.jitsi.jigasi.JvbConference.stop().521 [ctx=1590768340473728884167] Removing account Jabber:60af0fa9@true
/60af0fa9
Jigasi 2020-05-29 16:05:54.424 INFO: [98] impl.protocol.jabber.OperationSetBasicTelephonyJabberImpl.registrationStateChanged().134 Jingle : OFF
Jigasi 2020-05-29 16:05:54.425 SEVERE: [98] org.jitsi.jigasi.AbstractGateway.notifyCallEnded().120 [ctx=1590768340473728884167] Call resource not exis
ts for session.
Jigasi 2020-05-29 16:05:54.425 INFO: [98] org.jitsi.jigasi.SipGatewaySession.peerStateChanged().1457 null SIP peer state: Disconnected
Jigasi 2020-05-29 16:05:54.457 INFO: [99] impl.protocol.sip.SipLogger.logInfo().196 Info from the JAIN-SIP stack: Setting SIPMessage peerPacketSource
`

**Comment by ktechmidas** [comment]
Standby... I think I figured it out by asking "so I'm not sure why it's complaining?"

I added jigasi into the .env afterwards...so prosody may not know it's there..

**Comment by ktechmidas** [comment]
I wiped everything in jitsi-meet-cfg and it repopulated with a fresh config but.... still getting the same issue out of the box with host-unknown

**Comment by ktechmidas** [comment]
Still on this one... set up another jigasi host to try but there's something really funky going on with the internal Docker domains

> c2s5602d8b5d010 info Client connected
> c2s5602d8b5d010 info Stream encrypted (TLSv1.2 with ECDHE-RSA-AES256-GCM-SHA384)
> c2s5602d8b5d010 info Authenticated as jigasi@auth.meet.jitsi

But as soon as a call comes in it’ll disconnect with host unknown, in the jigasi log

> 2020-05-30 10:14:28.574 SEVERE: [92] impl.protocol.jabber.ProtocolProviderServiceJabberImpl.connectAndLogin().1003 Failed to connect to XMPP service
> org.jivesoftware.smack.XMPPException$StreamErrorException: host-unknown

**Comment by ktechmidas** [comment]
Alright so now I have set X-Room-Name to be test@muc.meet.jitsi as suggested here https://github.com/jitsi/docker-jitsi-meet/issues/367 but I'm still getting this issue, I've verified that the number from conferenceMapper matches the correct domain (in my case test@meet.ourdomain.com) and that all checks out...

I'm at a complete loss

**Comment by ktechmidas** [comment]
Working now thanks to this legend: https://community.jitsi.org/t/working-voximplant-example-code-for-jigasi-sip-dial-in/54999
