### ISSUE TITLE
XMPP broken

### ISSUE THREAD

**Issue by mikelpr** [jitsi/docker-jitsi-meet#714]
I've just followed [the docker guide](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker), configured my .env, opened up the ports (4443/tcp and 10000/udp), reverse proxied from my nginx (with https) to jitsi's http port. but joining the meeting, there's no audio/video. the docker logs from jvb constantly show the following:

```
Aug 15, 2020 4:25:39 AM org.jitsi.utils.logging2.LoggerImpl log
SEVERE: Health check failed in PT0S:
java.lang.Exception: Address discovery through STUN failed
            at org.jitsi.videobridge.health.Health.performCheck(Health.java:156)
            at org.jitsi.health.AbstractHealthCheckService.run(AbstractHealthCheckService.kt:155)
            at org.jitsi.utils.concurrent.RecurringRunnableExecutor.run(RecurringRunnableExecutor.java:216)
            at org.jitsi.utils.concurrent.RecurringRunnableExecutor.runInThread(RecurringRunnableExecutor.java:292)
            at org.jitsi.utils.concurrent.RecurringRunnableExecutor.access$000(RecurringRunnableExecutor.java:36)
            at org.jitsi.utils.concurrent.RecurringRunnableExecutor$1.run(RecurringRunnableExecutor.java:328)
Aug 15, 2020 4:25:45 AM org.jitsi.utils.logging2.LoggerImpl log
WARNING: [MucClient id=shard hostname=xmpp.meet.jitsi] error connecting
org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: 'xmpp.meet.jitsi:5222' failed because: xmpp.meet.jitsi/172.19.0.3 exception: java.net.NoRouteToHostException: No route to host (Host unreachable)
            at org.jivesoftware.smack.SmackException$ConnectionException.from(SmackException.java:278)
            at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:619)
            at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:902)
            at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:383)
            at org.jitsi.xmpp.mucclient.MucClient.lambda$getConnectAndLoginCallable$8(MucClient.java:664)
            at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
            at java.util.concurrent.FutureTask.run(FutureTask.java:266)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
            at java.lang.Thread.run(Thread.java:748)
```

docker logs for jitsi-web say this

```
172.20.0.1 - - [15/Aug/2020:18:15:23 +0000] "POST /http-bind?room=complexladdersarticulatedelicately HTTP/1.0" 502 568 "https://(my domain)/ComplexLaddersArticulateDelicately" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.59 Safari/537.36"
2020/08/15 18:15:25 [error] 225#225: *94 connect() failed (113: No route to host) while connecting to upstream, client: 172.20.0.1, server: _, request: "POST /http-bind?room=complexladdersarticulatedelicately HTTP/1.0", upstream: "http://172.20.0.3:5280/http-bind?room=complexladdersarticulatedelicately", host: "localhost:7000", referrer: "https://(my domain)/ComplexLaddersArticulateDelicately"
```

same issue without reverse proxy

**Comment by mikelpr** [comment]
seems to be a fedora 32 issue as they moved firewalld to nftables

**Comment by aiyotta** [comment]
I have the same issue with docker installation on Centos 8 VPS. Could somebody help please?
