### ISSUE TITLE
Address discovery through STUN failed

### ISSUE THREAD

**Issue by godpit** [jitsi/docker-jitsi-meet#823]
java.lang.Exception: Address discovery through STUN failed

	at org.jitsi.videobridge.health.JvbHealthChecker.check(JvbHealthChecker.kt:40)

	at org.jitsi.videobridge.health.JvbHealthChecker.access$check(JvbHealthChecker.kt:25)

	at org.jitsi.videobridge.health.JvbHealthChecker$healthChecker$1.invoke(JvbHealthChecker.kt:32)

	at org.jitsi.videobridge.health.JvbHealthChecker$healthChecker$1.invoke(JvbHealthChecker.kt:25)

	at org.jitsi.health.HealthChecker.run(HealthChecker.kt:144)

	at org.jitsi.utils.concurrent.RecurringRunnableExecutor.run(RecurringRunnableExecutor.java:216)

	at org.jitsi.utils.concurrent.RecurringRunnableExecutor.runInThread(RecurringRunnableExecutor.java:292)

	at org.jitsi.utils.concurrent.RecurringRunnableExecutor.access$000(RecurringRunnableExecutor.java:36)

	at org.jitsi.utils.concurrent.RecurringRunnableExecutor$1.run(RecurringRunnableExecutor.java:328)

And then, no sound

**Comment by bgrozev** [comment]
STUN discovery, when configured, is required by design, so the observed behavior is correct. If you don't need it you can disable it in the config file.
If you are trying to understand why this happened, we'll need more details.
