### ISSUE TITLE
Prosody does not have the ability to add the callcontrol component

### ISSUE THREAD

**Issue by khaliqgant** [jitsi/docker-jitsi-meet#833]
In the [Jigasi README.md](https://github.com/jitsi/jigasi) it states:

4. Configure external component in your XMPP server. If your server is Prosody: edit /etc/prosody/prosody.cfg.lua and append following lines to your config (assuming that subdomain is 'callcontrol' and domain 'meet.jit.si'):
```
Component "callcontrol.meet.jit.si"
    component_secret = "topsecret"
```

However in the [prosody config](https://github.com/jitsi/docker-jitsi-meet/blob/master/prosody/rootfs/defaults/conf.d/jitsi-meet.cfg.lua) there is no logic to actually account for that component. @saghul any insight into this? Currently I am unable to get Jitsi working with Jigasi to be able to call out or receive calls and I believe it might be due to this. 

Outgoing call log excerpt:
```
Jigasi 2020-11-22 04:18:46.440 SEVERE: [146] service.protocol.AbstractProtocolProviderService.fireRegistrationStateChanged().201 An error occurred while executing RegistrationStateChangeListener#registrationStateChanged(RegistrationStateChangeEvent) of org.jitsi.jigasi.JvbConference@7f382226
java.lang.NoClassDefFoundError: org/jitsi/xmpp/extensions/jitsimeet/Nick
	at org.jitsi.jigasi.JvbConference.joinConferenceRoom(JvbConference.java:742)
	at org.jitsi.jigasi.JvbConference.registrationStateChanged(JvbConference.java:620)
	at net.java.sip.communicator.service.protocol.AbstractProtocolProviderService.fireRegistrationStateChanged(AbstractProtocolProviderService.java:187)
	at net.java.sip.communicator.service.protocol.AbstractProtocolProviderService.fireRegistrationStateChanged(AbstractProtocolProviderService.java:141)
	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.connectAndLogin(ProtocolProviderServiceJabberImpl.java:1389)
	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.connectAndLogin(ProtocolProviderServiceJabberImpl.java:970)
	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.initializeConnectAndLogin(ProtocolProviderServiceJabberImpl.java:795)
	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.register(ProtocolProviderServiceJabberImpl.java:500)
	at org.jitsi.jigasi.util.RegisterThread.run(RegisterThread.java:59)
Caused by: java.lang.ClassNotFoundException: org.jitsi.xmpp.extensions.jitsimeet.Nick
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 9 more
Jigasi 2020-11-22 04:18:51.287 SEVERE: [143] org.jitsi.jigasi.xmpp.CallControlMucActivator.processIQ().601 Error processing RayoIq
java.lang.Exception: Fail to join muc!
```

Thanks!

**Comment by bgrozev** [comment]
Note that the component config is no longer necessary (we just merged a commit updating the readme and removing the feature). The exception is unrelated, but I don't know why it occurs.

**Comment by khaliqgant** [comment]
Got it, thanks for the response!
