### ISSUE TITLE
Video fails with more than two members?

### ISSUE THREAD

**Issue by pwFoo** [jitsi/docker-jitsi-meet#926]
Video conference fails with more than 2 participants with docker images version stable-5390-1. 
Audio / video connection lost.
```
INFO: Start connectivity checks.
Jan 31, 2021 1:05:54 PM org.jitsi.utils.logging2.LoggerImpl log
INFO: Update remote candidate for stream-13fe2798.RTP: 192.168.178.45:37390/udp
Jan 31, 2021 1:05:54 PM org.jitsi.utils.logging2.LoggerImpl log
INFO: new Pair added: 172.21.0.25:10000/udp/host -> 192.168.178.45:37390/udp/host (stream-13fe2798.RTP).
Jan 31, 2021 1:05:54 PM org.jitsi.utils.logging2.LoggerImpl log
INFO: new Pair added: 10.0.71.14:10000/udp/host -> 192.168.178.45:37390/udp/host (stream-13fe2798.RTP).
Jan 31, 2021 1:05:54 PM org.jitsi.utils.logging2.LoggerImpl log
INFO: new Pair added: 10.255.0.249:10000/udp/host -> 192.168.178.45:37390/udp/host (stream-13fe2798.RTP).
Jan 31, 2021 1:05:54 PM org.jitsi.utils.logging2.LoggerImpl log
INFO: Pair failed: 172.21.0.25:10000/udp/host -> 192.168.178.45:37390/udp/host (stream-13fe2798.RTP)
Jan 31, 2021 1:05:54 PM org.jitsi.utils.logging2.LoggerImpl log
INFO: Pair failed: 172.21.0.25:10000/udp/host -> 192.168.178.45:37390/udp/host (stream-13fe2798.RTP)
Jan 31, 2021 1:05:54 PM org.jitsi.utils.logging2.LoggerImpl log
WARNING: Returning a candidate matching the address, while no candidates match both address (<DOCKER_HOST_IP>:10000/udp) and base (candidate:3 1 udp 2113932031 10.255.0.249 10000 typ host): candidate:4 1 udp 1677724415 <DOCKER_HOST_IP> 10000 typ srflx raddr 172.21.0.25 rport 10000 with base candidate:1 1 udp 2130706431 172.21.0.25 10000 typ host
Jan 31, 2021 1:05:54 PM org.jitsi.utils.logging2.LoggerImpl log
INFO: Pair succeeded: 10.255.0.249:10000/udp/host -> 10.255.0.2:22598/udp/prflx (stream-13fe2798.RTP).
Jan 31, 2021 1:05:54 PM org.jitsi.utils.logging2.LoggerImpl log
INFO: Adding allowed address: 10.255.0.2:22598/udp
Jan 31, 2021 1:05:54 PM org.jitsi.utils.logging2.LoggerImpl log
INFO: Pair validated: <DOCKER_HOST_IP>:10000/udp/srflx -> 10.255.0.2:22598/udp/prflx (stream-13fe2798.RTP).
Jan 31, 2021 1:05:54 PM org.jitsi.utils.logging2.LoggerImpl log
WARNING: Returning a candidate matching the address, while no candidates match both address (<DOCKER_HOST_IP>:10000/udp) and base (candidate:3 1 udp 2113932031 10.255.0.249 10000 typ host): candidate:4 1 udp 1677724415 <DOCKER_HOST_IP> 10000 typ srflx raddr 172.21.0.25 rport 10000 with base candidate:1 1 udp 2130706431 172.21.0.25 10000 typ host
Jan 31, 2021 1:05:54 PM org.jitsi.utils.logging2.LoggerImpl log
INFO: Nominate (first valid): <DOCKER_HOST_IP>:10000/udp/srflx -> 10.255.0.2:22598/udp/prflx (stream-13fe2798.RTP).
Jan 31, 2021 1:05:54 PM org.jitsi.utils.logging2.LoggerImpl log
INFO: verify if nominated pair answer again
Jan 31, 2021 1:05:54 PM org.jitsi.utils.logging2.LoggerImpl log
INFO: Pair succeeded: 10.255.0.249:10000/udp/host -> 10.255.0.2:22598/udp/prflx (stream-13fe2798.RTP).
Jan 31, 2021 1:05:54 PM org.ice4j.stack.NetAccessManager handleFatalError
SEVERE: Unexpected Error!
java.lang.NullPointerException
        at org.ice4j.socket.MergingDatagramSocket.initializeActive(MergingDatagramSocket.java:577)
        at org.ice4j.ice.ComponentSocket.propertyChange(ComponentSocket.java:176)
        at org.ice4j.ice.IceMediaStream.firePairPropertyChange(IceMediaStream.java:877)
        at org.ice4j.ice.CandidatePair.nominate(CandidatePair.java:629)
        at org.ice4j.ice.Agent.nominate(Agent.java:1788)
        at org.ice4j.ice.DefaultNominator.strategyNominateFirstValid(DefaultNominator.java:144)
        at org.ice4j.ice.DefaultNominator.propertyChange(DefaultNominator.java:120)
        at org.ice4j.ice.IceMediaStream.firePairPropertyChange(IceMediaStream.java:877)
        at org.ice4j.ice.CandidatePair.validate(CandidatePair.java:667)
        at org.ice4j.ice.IceMediaStream.addToValidList(IceMediaStream.java:675)
        at org.ice4j.ice.Agent.validatePair(Agent.java:1752)
        at org.ice4j.ice.ConnectivityCheckClient.processSuccessResponse(ConnectivityCheckClient.java:641)
        at org.ice4j.ice.ConnectivityCheckClient.processResponse(ConnectivityCheckClient.java:405)
        at org.ice4j.stack.StunClientTransaction.handleResponse(StunClientTransaction.java:314)
        at org.ice4j.stack.StunStack.handleMessageEvent(StunStack.java:1040)
        at org.ice4j.stack.MessageProcessingTask.run(MessageProcessingTask.java:196)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Jan 31, 2021 1:05:54 PM org.jitsi.utils.logging2.LoggerImpl log
INFO: Pair validated: <DOCKER_HOST_IP>:10000/udp/srflx -> 10.255.0.2:22598/udp/prflx (stream-13fe2798.RTP).
Jan 31, 2021 1:05:54 PM org.jitsi.utils.logging2.LoggerImpl log
INFO: IsControlling: true USE-CANDIDATE:false.
Jan 31, 2021 1:05:54 PM org.jitsi.utils.logging2.LoggerImpl log
INFO: Pair failed: 10.0.71.14:10000/udp/host -> 192.168.178.45:37390/udp/host (stream-13fe2798.RTP)
Jan 31, 2021 1:05:54 PM org.jitsi.utils.logging2.LoggerImpl log
INFO: Pair failed: 10.255.0.249:10000/udp/host -> 192.168.178.45:37390/udp/host (stream-13fe2798.RTP)
Jan 31, 2021 1:05:56 PM org.jitsi.utils.logging2.LoggerImpl log
INFO: Performed a successful health check in PT0S. Sticky failure: false
```

**Comment by pwFoo** [comment]
Problem is related to port mapping!

Fixed it by change my ports section of jvb
```
        ports:
            - target: ${JVB_PORT}
              published: ${JVB_PORT}
              protocol: udp
              mode: host
            - target: ${JVB_TCP_PORT}
              published: ${JVB_TCP_PORT}
              protocol: tcp
              mode: host
            #- '${JVB_PORT}:${JVB_PORT}/udp'
            #- '${JVB_TCP_PORT}:${JVB_TCP_PORT}'
```
