### ISSUE TITLE
Jibri: livestream or recording fails

### ISSUE THREAD

**Issue by matheusfillipe** [jitsi/docker-jitsi-meet#966]
I built with:

`docker-compose -f docker-compose.yml -f jibri.yml up -d`

``` 
$ lsmod | grep snd_aloop
snd_aloop              24576  0
snd_pcm               106496  1 snd_aloop
snd                    90112  3 snd_timer,snd_aloop,snd_pcm

```

Trying to setup a livestream always fails with "Livestream failed to start". These are the docker compose logs:

``` 
jicofo_1   | Jicofo 2021-02-26 07:33:31.322 INFO: [81] org.jitsi.jicofo.recording.jibri.JibriSession.log() Starting session with Jibri jibribrewery@internal-muc.meet.jitsi/jibri-instanse-062316974
jicofo_1   | Jicofo 2021-02-26 07:33:31.322 INFO: [81] org.jitsi.jicofo.recording.jibri.JibriSession.log() Starting Jibri jibribrewery@internal-muc.meet.jitsi/jibri-instanse-062316974 for stream ID: z0qe-9uf8-0se9-dwy6-be51 in room: matf@muc.meet.jitsi
jicofo_1   | Jicofo 2021-02-26 07:33:31.682 INFO: [81] org.jitsi.jicofo.recording.jibri.JibriSession.log() Updating status from JIBRI: <iq to='focus@auth.meet.jitsi/focus561985838507882' from='jibribrewery@internal-muc.meet.jitsi/jibri-instanse-062316974' id='ukOGr-459' type='result'><jibri xmlns='http://jitsi.org/protocol/jibri' status='pending'/></iq> for matf@muc.meet.jitsi
jicofo_1   | Jicofo 2021-02-26 07:33:31.682 INFO: [81] org.jitsi.jicofo.recording.jibri.JibriSession.log() Got Jibri status update: Jibri jibribrewery@internal-muc.meet.jitsi/jibri-instanse-062316974 has status pending and failure reason null, current Jibri jid is jibribrewery@internal-muc.meet.jitsi/jibri-instanse-062316974
jicofo_1   | Jicofo 2021-02-26 07:33:31.683 INFO: [81] org.jitsi.jicofo.recording.jibri.JibriRecorder.log() Started Jibri session
jicofo_1   | Jicofo 2021-02-26 07:33:31.683 INFO: [30] org.jitsi.jicofo.recording.jibri.JibriDetector.log() Received Jibri jibribrewery@internal-muc.meet.jitsi/jibri-instanse-062316974 status <jibri-status xmlns='http://jitsi.org/protocol/jibri'><busy-status xmlns='http://jitsi.org/protocol/jibri' status='busy'/><health-status xmlns='http://jitsi.org/protocol/health' status='healthy'/></jibri-status>
jicofo_1   | Jicofo 2021-02-26 07:33:31.755 INFO: [81] org.jitsi.jicofo.recording.jibri.JibriSession.log() Updating status from JIBRI: <iq to='focus@auth.meet.jitsi/focus561985838507882' from='jibribrewery@internal-muc.meet.jitsi/jibri-instanse-062316974' id='Zm9jdXNAYXV0aC5tZWV0LmppdHNpL2ZvY3VzNTYxOTg1ODM4NTA3ODgyAHBlVnQ4LTg2AFaRlx1un8Q6A9vhrZSFfMs=' type='set'><jibri xmlns='http://jitsi.org/protocol/jibri' status='off' failure_reason='error' should_retry='true'/></iq> for matf@muc.meet.jitsi
jicofo_1   | Jicofo 2021-02-26 07:33:31.756 INFO: [81] org.jitsi.jicofo.recording.jibri.JibriSession.log() Got Jibri status update: Jibri jibribrewery@internal-muc.meet.jitsi/jibri-instanse-062316974 has status off and failure reason error, current Jibri jid is jibribrewery@internal-muc.meet.jitsi/jibri-instanse-062316974
jicofo_1   | Jicofo 2021-02-26 07:33:31.756 INFO: [81] org.jitsi.jicofo.recording.jibri.JibriSession.log() Jibri failed, trying to fall back to another Jibri
jicofo_1   | Jicofo 2021-02-26 07:33:31.756 SEVERE: [81] org.jitsi.jicofo.recording.jibri.JibriSession.log() Unable to find an available Jibri, can't start
jicofo_1   | Jicofo 2021-02-26 07:33:31.756 INFO: [81] org.jitsi.jicofo.recording.jibri.JibriSession.log() Failed to fall back to another Jibri, this session has now failed: org.jitsi.jicofo.recording.jibri.JibriSession$StartException$AllBusy: All jibri instances are busy
jicofo_1   | org.jitsi.jicofo.recording.jibri.JibriSession$StartException$AllBusy: All jibri instances are busy
jicofo_1   |    at org.jitsi.jicofo.recording.jibri.JibriSession.startInternal(JibriSession.java:339)
jicofo_1   |    at org.jitsi.jicofo.recording.jibri.JibriSession.start(JibriSession.java:315)
jicofo_1   |    at org.jitsi.jicofo.recording.jibri.JibriSession.retryRequestWithAnotherJibri(JibriSession.java:625)
jicofo_1   |    at org.jitsi.jicofo.recording.jibri.JibriSession.handleJibriStatusUpdate(JibriSession.java:695)
jicofo_1   |    at org.jitsi.jicofo.recording.jibri.JibriSession.processJibriIqFromJibri(JibriSession.java:476)
jicofo_1   |    at org.jitsi.jicofo.recording.jibri.JibriSession.processJibriIqRequestFromJibri(JibriSession.java:457)
jicofo_1   |    at org.jitsi.jicofo.recording.jibri.CommonJibriStuff.handleIQRequest(CommonJibriStuff.java:225)
jicofo_1   |    at org.jitsi.jicofo.recording.jibri.OperationSetJibri.handleIQRequest(OperationSetJibri.java:98)
jicofo_1   |    at org.jivesoftware.smack.AbstractXMPPConnection$4.run(AbstractXMPPConnection.java:1188)
jicofo_1   |    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
jicofo_1   |    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
jicofo_1   |    at java.lang.Thread.run(Thread.java:748)
jicofo_1   | Jicofo 2021-02-26 07:33:31.756 INFO: [81] org.jitsi.jicofo.recording.jibri.JibriRecorder.log() Got jibri status off and failure error
jicofo_1   | Jicofo 2021-02-26 07:33:31.756 INFO: [81] org.jitsi.jicofo.recording.jibri.JibriRecorder.log() Publishing new jibri-recording-status: <jibri-recording-status xmlns='http://jitsi.org/protocol/jibri' status='off' failure_reason='error' session_id='yxnxqpinjrgarvfd' recording_mode='stream'/> in: matf@muc.meet.jitsi
jicofo_1   | Jicofo 2021-02-26 07:33:31.757 INFO: [81] org.jitsi.jicofo.recording.jibri.JibriSession.log() Cleaning up current JibriSession
jicofo_1   | Jicofo 2021-02-26 07:33:31.856 INFO: [30] org.jitsi.jicofo.recording.jibri.JibriDetector.log() Received Jibri jibribrewery@internal-muc.meet.jitsi/jibri-instanse-062316974 status <jibri-status xmlns='http://jitsi.org/protocol/jibri'><busy-status xmlns='http://jitsi.org/protocol/jibri' status='idle'/><health-status xmlns='http://jitsi.org/protocol/health' status='healthy'/></jibri-status>
jvb_1      | Feb 26, 2021 7:33:32 AM org.jitsi.utils.logging2.LoggerImpl log
jvb_1      | INFO: Performed a successful health check in PT0S. Sticky failure: false

```

Jibri .env config:

``` 
 3 # Enable recording
  2 ENABLE_RECORDING=1
  1 
315 # XMPP domain for the jibri recorder
  1 XMPP_RECORDER_DOMAIN=recorder.meet.jitsi
  2 
  3 # XMPP recorder user for Jibri client connections
  4 JIBRI_RECORDER_USER=recorder
  5 
  6 # Directory for recordings inside Jibri container
  7 JIBRI_RECORDING_DIR=/config/recordings
  8 
  9 # The finalizing script. Will run after recording is complete
 10 JIBRI_FINALIZE_RECORDING_SCRIPT_PATH=/config/finalize.sh
 11 
 12 # XMPP user for Jibri client connections
 13 JIBRI_XMPP_USER=jibri
 14 
 15 # MUC name for the Jibri pool
 16 JIBRI_BREWERY_MUC=jibribrewery
 17 
 18 # MUC connection timeout
 19 JIBRI_PENDING_TIMEOUT=90
 20 
 21 # When jibri gets a request to start a service for a room, the room
 22 # jid will look like: roomName@optional.prefixes.subdomain.xmpp_domain
 23 # We'll build the url for the call by transforming that into:
 24 # https://xmpp_domain/subdomain/roomName
 25 # So if there are any prefixes in the jid (like jitsi meet, which
 26 # has its participants join a muc at conference.xmpp_domain) then
 27 # list that prefix here so it can be stripped out to generate
 28 # the call url correctly
 29 JIBRI_STRIP_DOMAIN_JID=muc
 30 
 31 # Directory for logs inside Jibri container
 32 JIBRI_LOGS_DIR=/config/logs
 33 
 34 # Disable HTTPS: handle TLS connections outside of this setup                                                                                                                                                      
 35 DISABLE_HTTPS=1           
```

I am on  c89ccc9727d45d76c013798801d6fdc83887023b. 

Any other version to check, any reason this wouldn't work?

**Comment by matheusfillipe** [comment]
Also I am using apache reverse proxy like:
``` 
...
SSLProxyEngine on                                        
                                                               
ProxyPreserveHost On                                      
RequestHeader set X-Forwarded-Proto "https"              
ProxyPass "/" "http://localhost:8000/"                         
ProxyPassReverse "/" "http://localhost:8000/"                         
                                                                      
ProxyPass "/http-bind" "http://localhost:8000/http-bind/"      
ProxyPassReverse "/http-bind" "http://localhost:8000/http-bind"       
                                                                      
RewriteEngine on
RewriteCond %{HTTP:Connection} Upgrade [NC]            
RewriteCond %{HTTP:Upgrade} websocket [NC]
RewriteRule ^/?(.*) "ws://127.0.0.1:8000/$1" [P,L] 
ErrorLog     /var/log/apache2/meet-error_log                
CustomLog          /var/log/apache2/meet-access_log common

...
```

**Comment by matheusfillipe** [comment]
Got it working by setting on the env:
```
DISABLE_HTTPS=0  
```
